### ISSUE TITLE
"If you move me I'll just come back here..."

### ISSUE THREAD

**Issue by Kyokou** [bevacqua/dragula#1]
It let's me move it so I'm confused. It makes it sound like it should remain in its place in the element, even if I try to drag it to another box.

Poorly worded or not functioning?

Chrome 41 in case that matters.

**Comment by bevacqua** [comment]
Poorly worded! Haha. The point is that you can only move it to the container on the right, or place it somewhere else in its own container. Dropping it anywhere else will cancel the action, bringing it back to where it originally was.
