### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by wookoouk** [bevacqua/dragula#10]
Why does this not have a logo and more specifically, why is the logo not Dracula in drag.

https://orwhatyouwill.files.wordpress.com/2010/12/tim-curry-as-frank-n-furter.jpg

**Comment by bevacqua** [comment]
All I know about the logo is that it should have some sort of "dark" theme. Can you come up with a logo?

![eyes](https://github.com/bevacqua/dragula/raw/master/resources/eyes.png)

**Comment by markrebec** [comment]
Additionally, how is it possible there is not a single Rob Zombie reference to be found anywhere?! :smile:

**Comment by bevacqua** [comment]
Have you tried clicking on the eyes in the `README` off and on again?

**Comment by markrebec** [comment]
:+1:

**Comment by bevacqua** [comment]
\*Psst\*, `dragula` may be getting a logo soon!

+@debone
