### ISSUE TITLE
Error after calling drake.cancel() in "drop" event handler

### ISSUE THREAD

**Issue by jdanyow** [bevacqua/dragula#101]
```javascript
drake.on('drop', (el, container, source) => {
  drake.cancel();
});
```

![error](http://i.imgur.com/GwAePOG.png)

**Comment by bevacqua** [comment]
Thanks for reporting it like that

**Comment by jdanyow** [comment]
:sparkles::+1::muscle: Thanks!  :muscle::+1::sparkles:

**Comment by jdanyow** [comment]
dragula made [this](http://jdanyow.github.io/aurelia-solitaire/) really easy- thanks again!

**Comment by bevacqua** [comment]
cool demo!

**Comment by jdanyow** [comment]
This doesn't work in the latest release.  Calling `drake.cancel()` in the drop event handler doesn't cancel the drop anymore.

Here's the use case:  MVVM framework, the view is a `<ul>` data-bound to a view-model with an array property.  Dragula is used to get the user's drag-and-drop "intent", however the drop is always canceled so that we can mutate the array in the view-model code and let the binding/templating engine update the dom the usual way.

What do you think- should this be a supported use-case?  Maybe I can work around this by using the `accepts` option?

**Comment by bevacqua** [comment]
Can you look into fixing this?

**Comment by gsouf** [comment]
@bevacqua I'm using version 3.7.1 and i'm getting the following issue:

```js
drake.on('drop', function(){
    drake.cancel();
});
```

```
Uncaught RangeError: Maximum call stack size exceededatoa 
@ atoa.js:1(anonymous function) 
@ emitter.js:43thing.emit 
@ emitter.js:38cancel 
@ dragula.js:297(anonymous function) 
@ application.vue:27emitter
@ emitter.js:47forEach @ (program):959(anonymous function) 
@ emitter.js:46thing.emit 
@ emitter.js:38cancel 
@ dragula.js:297
```

**Comment by gsouf** [comment]
Calling ``cancel(true)`` worked as specified in the API. But the maximum call stack size exceeded error shouldnt be there

**Comment by bevacqua** [comment]
Please file a separate issue.
