### ISSUE TITLE
Crossvent preventing the setting of breakpoints in Chrome Debugger

### ISSUE THREAD

**Issue by mtj8033** [bevacqua/dragula#102]
When viewing source in chrome and trying to add break points my code keeps going to crossvent which looks like another library you've written. Any way to prevent this? Basically I click on a line and it goes to line 89 of crossvent.js (1.3.2)

**Comment by bevacqua** [comment]
Just use step-over

**Comment by mtj8033** [comment]
@bevacqua  That doesn't seem to fix it. I used step-over and it just stays in the crossvent.js file. I also tried blackboxing crossvent.js but that didn't resolve it either. Basically in the call stack in crossvent.js I can see my method in the call stack but it says it goes to crossvent.js

Any other ideas?

**Comment by benjamin-smith** [comment]
I'm seeing the same result as @mtj8033 when stepping over or blackboxing crossvent in Dev Tools. The entire stack shows as the last (blank) line of crossvent.js ([screenshot](https://www.dropbox.com/s/poh9mw9tu92psuc/Screenshot%202015-07-13%2015.34.30.png?dl=0))

**Comment by bevacqua** [comment]
Are you guys using the compiled version or are you using browserify?

**Comment by benjamin-smith** [comment]
I am not explicitly using browserify, but it appears to be loading using browserify. I am using requirejs and r.js to concat all JS to a single file (see [screenshot](https://www.dropbox.com/s/q5sgr48gyrab3zw/Screenshot%202015-07-13%2015.48.27.png?dl=0), the compiled file is `output.js`). The Dragula file I am referencing is [`dist/dragula.js`](https://github.com/bevacqua/dragula/blob/master/dist/dragula.js).

**Comment by bevacqua** [comment]
Ahá, in that case it's an issue with your module system

**Comment by benjamin-smith** [comment]
It appears loading  [`dist/dragula.min.js`](https://github.com/bevacqua/dragula/blob/master/dist/dragula.min.js) does not cause the same issue, nor is browserify loaded. I'm not sure what the difference in this file is, as it is minified, and I don't see any build scripts in the repo.

For reference, or those wandering in from Google, the relevant portion of my require config is:

```javascript
require.config({
    paths: {
        dragula: '../bower_components/dragula.js/dist/dragula.min'
    }
});
```

And a sample backbone view looks like:

```javascript
define([
    'underscore',
    'backbone',
    'templates',
    'dragula'
], function (_, Backbone, JST, dragula) {
    ...
```

**Comment by bevacqua** [comment]
I'd presume any generic googling for "fix r.js sourcemap issues" should help you here

**Comment by mtj8033** [comment]
I'm using webpack, but I imagine you are saying it would be the same problem with that?

**Comment by bevacqua** [comment]
Well, my assessment is that using the source files directly should work in most cases, so you should be using those if possible (e.g not the ones in `dist`). Webpack supports commonjs http://webpack.github.io/docs/commonjs.html
