### ISSUE TITLE
containers can't accept an array

### ISSUE THREAD

**Issue by coogleyou** [bevacqua/dragula#105]
I have to do this:
```
var drake = dragula();
var array = document.getElementsByClassName('container');
for(var i=0, len=array.length; i<len; i++){
  drake.containers.push(array[i]);
}
```
and  why this code blew not work?
```
...
var drake = dragula({containers: document.getElementsByClassName('container')});
```

**Comment by bevacqua** [comment]
See this line: https://github.com/bevacqua/dragula/blob/master/dragula.js#L8

The [`document.getElementsByClassName`][1] method returns an array-like object of all child elements which have all of the given class names.

[1]: https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByClassName

**Comment by coogleyou** [comment]
Thanks very much!

**Comment by HarmIt85** [comment]
var arraylike = document.getElementsByClassName('draggable');
var containers = Array.prototype.slice.call(arraylike);
var drake = dragula({ containers: containers });

this worked for me when the page loaded for the first time.
but, when i am adding the element with class "draggable" dynamically, drag and drop is not working for that particluar container.
Do i need to re-initialize? 
I am badly in need of help!!
Stuck with this issue from past 3 days.
Thanks in advance
