### ISSUE TITLE
Simple dragging and firing event when dropped

### ISSUE THREAD

**Issue by 57even** [bevacqua/dragula#108]
Can I also drag an element onto another element and fire an event when it's done - without putting the new element into the element to which is was dragged?

I have found many libraries which provides 'sortable list' and since this library is about dragging and dropping, I wonder if it also features such simple functionality as described?

**Comment by bevacqua** [comment]
Drag and drop without actually dropping? What'd be the use case?

**Comment by 57even** [comment]
To tell that 2 items belong together. When the dragged item is dropped onto the other item, the dragged item should disappear.

So I am looking for the drag and drop functionality with possibility to fire an event when dropping the dragged element.

**Comment by bevacqua** [comment]
```js
dragula([a,b], { copy: true, moves: moves }).on('drop', drop);
function moves (el, from) {
  return from === a;
}
function drop (el, to, from) {
  if (to === b) {
    el.parentElement.removeChild(el);
  }
}
```
