### ISSUE TITLE
Are CSS scale-transformed elements supported?

### ISSUE THREAD

**Issue by naugtur** [bevacqua/dragula#110]
Hi, 
I'm happy to see a lightweight drag-and-drop, but I remember how problematic it was to get jQueryUI to work with containers and/or dragables transformed with CSS scale transform.
Mouse coordinate system and document coordinate system were not separated at all and I had to find all variables in equations that required scaling one way or another.

So, even if there is no explicit support, can anyone tell me if coordinate systems are separated by an abstraction here? (I'm willing to contribute scaling support one day if there's separation)

**Comment by bevacqua** [comment]
Given the way this was built I don't foresee any issues with CSS scale-transformed containers. Do you want to new up a demo on codepen or jsfiddle and figure out whether it works properly?

Thanks

**Comment by naugtur** [comment]
I'll test it out.
The biggest problem with jQueryUI was that when I implemented a zoom-in/zoom-out feature on a rectangle full of draggables, the draggables would fly away on mousedown or move just a 1/zom fraction while dragging.

**Comment by bevacqua** [comment]
Let me know if this is an issue, and if it is we can re-open this one.

**Comment by elgubenis** [comment]
this is an issue

**Comment by orthes** [comment]
The same problem here. @naugtur, @elgubenis have you fixed it in your projects?

**Comment by elgubenis** [comment]
@orthes nope, but I think digging into the source and adding the ratio to the calculations won't take more then an hour, perfect thing would be adding the ratio or a function returning the 'variable' ratio to the options, but i had no chance yet to check that out. good luck

**Comment by orthes** [comment]
@elgubenis I was able to fix it on my project, but I'm worried it's just an ad-hoc solution for my use case. I'll try to make it universal and submit a pr if it goes well.

**Comment by naugtur** [comment]
I actually didn't get back to it since memosort.com didn't catch on and there was no incentive for a rewrite.

**Comment by zypo** [comment]
@orthes, feel free to give us a quick paste or Gist, maybe someone can go on with it. It would be almost insanely great to have that one resolved too.

**Comment by naugtur** [comment]
I'm not playing with these technologies anymore but can share a quick tip.

The best thing you can do is assume mouse and elements are in totally different coordinate systems and, just like in webGL you need logic to determine where the mouse is pointing.
It's easy to include any transforms then.

**Comment by zypo** [comment]
@naugtur, seems I posted too early. After reading this thread, I just expected it not to work without further attention, as was the case with [Gridly](https://github.com/ksylvest/jquery-gridly). But in the end I didn't notice any issues with Dragula in combination with transform/scale3d.

**Comment by koraysels** [comment]
this is still an issue.. one that is causing me a headache for a couple of weeks.. did anybody find a solution eventually ?
