### ISSUE TITLE
Not working properly on Windows Phone devices

### ISSUE THREAD

**Issue by cihadturhan** [bevacqua/dragula#111]
When I hold and move my finger, page moves too. I'm not sure how to fix but maybe IE mobile needs a different function similar to `e.preventDefault()`. This issue doesn't happen with some other libraries such as [greensock draggable](https://greensock.com/draggable)

**Comment by bevacqua** [comment]
Unfortunately, I don't have a Windows Phone device handy. Could you try and work out a fix for this issue? Pretty please with sugar on top :astonished:

**Comment by bevacqua** [comment]
@cihadturhan this should've been fixed in `3.0.1`, let me know if it persists.
