### ISSUE TITLE
Sort order miscalculation on edges

### ISSUE THREAD

**Issue by bevacqua** [bevacqua/dragula#114]
<img width="787" alt="screen shot 2015-07-20 at 16 14 32" src="https://cloud.githubusercontent.com/assets/934293/8784872/6cf6181a-2efa-11e5-930c-d97c89af96e7.png">

Screencast [screencast.com/t/Jw3No0wryqJ](http://screencast.com/t/Jw3No0wryqJ)

Source [news.yc.com _(comment)_](https://news.ycombinator.com/item?id=9914270)

**Comment by darkstar112358** [comment]
hey, I was working on this bug. Can you tell me what tool do you use to create the files in the dist folder. Is it Grunt? if that's the case then can you share your Gruntfile.js. I am a novice in Javascript

**Comment by mnt** [comment]
I think I found what the problem is. When dragging there is a slight moment where

`immediate = <div id="right-defaults" class="container">`. This will cause the function to execute `outside()`. Which causes the reference to become the 2nd Item on the list.

**Comment by bevacqua** [comment]
`3.6.7`
