### ISSUE TITLE
Ticky browser?

### ISSUE THREAD

**Issue by rohan-deshpande** [bevacqua/dragula#117]
Hi, cool library!

I was wondering if there's any reason for ticky browser being included? This has somehow mucked up my console, when an error gets thrown, I can't see where the error was thrown in my code I just see

```
var si = typeof setImmediate === 'function', tick;
if (si) {
  tick = function (fn) { setImmediate(fn); };
} else {
  tick = function (fn) { setTimeout(fn, 0); };
}

module.exports = tick;
```

**Comment by bevacqua** [comment]
It's probably your module system. Using webpack? See #102

**Comment by rohan-deshpande** [comment]
Am using gulp, including the minified version fixed the issue for me. Not sure what's going on there.

**Comment by bevacqua** [comment]
Okay. FWIW `ticky` is a dependency of `contra`, and we use `contra/emitter`.

**Comment by rohan-deshpande** [comment]
Any reason for not using EventEmitter (git.io/ee)? It has no dependencies.

**Comment by bevacqua** [comment]
Yup. It's huge in comparison to `contra/emitter`.

```
» browserify emitter.js | uglifyjs -c -m | gzip-size | pretty-bytes
(node) util.error is deprecated. Use console.error instead.
WARN: Dropping unused function argument exports [-:1,471]
WARN: Dropping unused function argument exports [-:13,42]
WARN: Dropping unused function argument exports [-:69,56]
WARN: Dropping unused function argument exports [-:72,33]
(node) util.print is deprecated. Use console.log instead.
759 B
```

**Comment by rohan-deshpande** [comment]
EventEmitter is only 472 lines of code...18kb

**Comment by bevacqua** [comment]
18kB is 15+ times as big as 759 bytes, why would I use that? :dancer:

**Comment by rohan-deshpande** [comment]
Fair enough
