### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by apavlinovic** [bevacqua/dragula#118]
Would be great if this library got some kind of first class author support in Angular

**Comment by bevacqua** [comment]
Should be a 10 LOC directive, that's why I haven't yet written an "official directive" for it, although given it's popularity I might have to.

**Comment by apavlinovic** [comment]
It depends on how rich you want to make the directive and it's API - if the plan is to wrap only events then it is 10 LOC. If you plan to make a rich, well documented and well thought out directive, then its not 10 LOC  :)

**Comment by bevacqua** [comment]
Well we could start with the 10-LOC directive and go from there :)

**Comment by apavlinovic** [comment]
Makes sense, let's start like that :) :+1: 

![Angularize all the things](http://cdn.meme.am/instances/59501805.jpg)

**Comment by bevacqua** [comment]
See https://github.com/bevacqua/angular-dragula

**Comment by erquhart** [comment]
@bevacqua you are such a beast for this. Thank you.
