### ISSUE TITLE
Use a function as copy option value

### ISSUE THREAD

**Issue by guillaumepiot** [bevacqua/dragula#119]
I have a scenario when I would to decide whether the element to be dragged should be copied of not based on its status/class.

The copy option function would return true or false based on this condition.

For example, it could work like this:

    copy: function (el, target) { // whether element should be copied & dragged or dragged only
        return el.className === 'copy-able';
    },

**Comment by bevacqua** [comment]
Sounds reasonable. Can you submit a PR to this effect?

**Comment by beatfreaker** [comment]
is it reliable to alter the "copy" property to function and change the code accordingly or is it good to add new property for this feature??

**Comment by bevacqua** [comment]
I'd just make `copy` polymorphic and accept all of `true`, `false`, `function (el, container, target)`.

**Comment by beatfreaker** [comment]
so if we make it a generic property then we have to change the code every where we are accessing copy's value right??
sorry to bug for these simple things as i am a naive

**Comment by bevacqua** [comment]
yeah that's the idea.

**Comment by beatfreaker** [comment]
```javascript
 if (o.copy instanceof Function) { // check its a function or not
		if(o.copy(item, container, handle)) {
			_copy = item.cloneNode(true);
			api.emit('cloned', _copy, item);
                }
    } else if(o.copy){ // if not a function access the value
			_copy = item.cloneNode(true);
			api.emit('cloned', _copy, item);
   }
```
does this looks promising?

**Comment by bevacqua** [comment]
Wrap the check in a method.

```js
function isCopy () {
  if (typeof o.copy === 'boolean') {
    return o.copy;
  }
  return o.copy(el, container, target);
}
```

Then wherever we were doing `if (o.copy)` you can do `if (isCopy())` instead.

**Comment by beatfreaker** [comment]
i have made few changes in dist/dragula.js do i need to update dist/dragula.min.js too and then submit the PR?

**Comment by bevacqua** [comment]
Files in `dist` are autogenerated, change the file in the root directory instead.

**Comment by beatfreaker** [comment]
Submitted a PR [#127](https://github.com/bevacqua/dragula/pull/127) please check.

**Comment by nickleus** [comment]
+1 for letting "copy" accept a function

**Comment by nickleus** [comment]
here's my workaround:
```
var drake = dragula([dragulaCopyWithSort,dragulaNonCopyWithSort], {
    accepts: function (el, target, source, sibling) {
        if(target.id == 'dragulaCopyWithSort' && source != target) {
            return false;
        } else {
            return true;
        }
    },
    revertOnSpill: true
});

drake.on('drop', function(el, container, source) {
    if(container != source) {
        var clonedMovedElem = el.cloneNode(true);
        clonedMovedElem.classList.remove("gu-transit");
        source.appendChild(clonedMovedElem);
    }
});
```
support for "classList" is pretty good:
http://caniuse.com/#search=classlist

alternatively, using jquery:
$(clonedMovedElem).removeClass("gu-transit");

**Comment by bevacqua** [comment]
Implemented in `3.1.0`

**Comment by nickleus** [comment]
just implemented this in the project i'm making n it works great, thx!!! makes my code smaller n less complex! :)

**Comment by keithmclaughlin** [comment]
Re: [this comment](https://github.com/bevacqua/dragula/issues/119#issuecomment-125694373); is there any way to leave the item being copied in the same position in the source instead of appending it to the bottom?

**Comment by Indu1234** [comment]
Any example with ng2 for one way drag and drop?
