### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by knownasilya** [bevacqua/dragula#12]
Would love for there to be tests..

Here's a use case: https://github.com/IvyApp/ivy-sortable/issues/3#issuecomment-74893997

**Comment by bevacqua** [comment]
You're welcome to do the time, as long as you use `tape`, `sinon`, and `proxyquire`. I'm blazing through other stuff at the moment

**Comment by joesephforDianite** [comment]
hmmm mabey I can help to but on my free time. I'm trying to learn in coding different sites

**Comment by gh0stonio** [comment]
Is anyone on this? Maybe i can help too

**Comment by bevacqua** [comment]
Nope. Give it a shot!

**Comment by gh0stonio** [comment]
Ok i will try to help you. 
I just need to look how to use tape, i never use it and don't know how it's work.

**Comment by bevacqua** [comment]
Example: https://github.com/taunus/taunus/blob/master/test/browser/componentCache.js

**Comment by knownasilya** [comment]
Nice example.

**Comment by gh0stonio** [comment]
Thanks, i will have a look at it

**Comment by blacksonic** [comment]
some higher level tests, for example with protractor?

**Comment by bevacqua** [comment]
I'd rather just have tests using `tape` that doesn't need any confusing setup

**Comment by blacksonic** [comment]
You mean a simple protractor config and a static webserver would be confusing?
E2E could sit on top of unit tests ensuring that the component is usable in a real word scenario not just in a unit test. For example an element drag is easily reproducable with Protractor.

**Comment by bevacqua** [comment]
You can also use `testling` which is just a unixy CLI tool

**Comment by naugtur** [comment]
testling seems abandoned, I saw multiple repos switching to zuul+saucelabs and I made that switch in one repo - easy as a breeze (unless browsers start timing out ;) )

**Comment by bevacqua** [comment]
Agreed, `zuul` would be great. Anyone willing to take this on?

**Comment by bevacqua** [comment]
I'm giving this a shot with `testron` and `hihat`, the project has become popular enough that it sort of must have tests

**Comment by knownasilya** [comment]
Yay! :+1:

**Comment by bevacqua** [comment]
Okay, dragula got a bunch of tests. There's a ton of corner cases missing, but it's definitely way better than where it was before. Also, I need to set up CI with travis or circle at some point. For now it's just running locally on development environments.
