### ISSUE TITLE
How do you know element is over a container?

### ISSUE THREAD

**Issue by AtheistP3ace** [bevacqua/dragula#120]
Is there a way to determine easily that an element being dragged is over a container it could be dropped in? An event available? I can't find anything in docs. Thanks.

EDIT: Granted I could attach my own events to handle it but just wondering if its built into dragula at all?

**Comment by bevacqua** [comment]
The `shadow` event fires whenever the element is over a container and position it can be dropped in.

**Comment by AtheistP3ace** [comment]
Well I did read the docs. I suppose the name of that event just confused me. I was expecting something like 'over'. Thanks for quick response.

**Comment by bevacqua** [comment]
This event wouldn't fire if the `shadow` weren't moving, which may happen in some situations. May I ask why you need the event?

**Comment by AtheistP3ace** [comment]
Basically, I have a panel with some items in it. I also have a tree with some nodes. Those nodes (which i suppose will be individual containers in your world) allow the draggable items to be dropped on. When a draggable item is being dragged and held over the node I change a class on the node to show that this draggable item is in a position to be dropped on the node.

While I am at it and have your attention I am also wondering is there a way to assign individual options to containers. I have a bunch of containers al using the same instance of dragula but at runtime I want to be be able to decide if I I want to remove the item from the source and if I should add the item to the target. Can I do that with the current implementation?

**Comment by AtheistP3ace** [comment]
In the case of the tree node, I don't ever want to add this item they dropped to the node. I just want to kick off some event to the server with some information that I have about what the user did.

**Comment by AtheistP3ace** [comment]
Also is there an event that fires when the item has left the container it was being held over during dragging? I suppose the opposite of shadow.

**Comment by bevacqua** [comment]
There's no such granularity atm, feel free to create a PR with `enter` and `leave` events that fire on entering and leaving any container during a drag

**Comment by AtheistP3ace** [comment]
https://github.com/bevacqua/dragula/pull/122
