### ISSUE TITLE
How to set dragging element's style.

### ISSUE THREAD

**Issue by zhoukekestar** [bevacqua/dragula#124]
I don't know how to set my dragging element's style.
https://img.alicdn.com/imgextra/i2/776955218/TB2l8L9dVXXXXaBXpXXXXXXXXXX_!!776955218.png
The dragging element is different from my original element.

**Comment by bevacqua** [comment]
You probably have styles like this:

`.container .item {
  background: red;
}`

But the `.item`'s shadow doesn't match `.container .item`, while the ones in the container do.
