### ISSUE TITLE
Separate containers and custom feedback

### ISSUE THREAD

**Issue by bmpinto** [bevacqua/dragula#128]
In this repo's README you said:
> the example allows the user to drag elements from left into right, and from right into left.

Is it possible to have it just from left into right? Like separate containers: one just for dragging, and one just for dropping?

Can you remove the feedback shadow on drop and write a custom feedback function?

Thanks

**Comment by bevacqua** [comment]
You should use `moves` and `accepts` for this.

```js
dragula({
  moves: function (el, container, handle) {
   return container === left;
  },
  accepts: function accepts (el, target, source, sibling) {
    return target === right;
  }
});
```

**Comment by bmpinto** [comment]
When you're about to drop an element, it provides you a feedback of your element with a level of opacity.

**Comment by bevacqua** [comment]
What would you have it do instead?

**Comment by bmpinto** [comment]
So, what I'm trying to accomplish is this:
- drag the element from left container to the right container (you already helped me with that, thanks!)
- `on over` the right container, animate its properties (like height, width, bg color), and hide the transparent element
- `on drop` hide the dropped element

**Comment by bevacqua** [comment]
You could accomplish the second with a CSS rule: `.gu-mirror { display: none }`.

As for the third one, you could just do:

```js
drake.on('drop', function (el) {
  // hide el
});
```
