### ISSUE TITLE
No mirror element while dragging

### ISSUE THREAD

**Issue by WillyPoteloin** [bevacqua/dragula#13]
When i start dragging an element they are no mirror element that follow the mouse.

My element is just a simple img in a span : <span><img></span>

**Comment by bevacqua** [comment]
Can you create a reproducible demo on codepen on something?

**Comment by WillyPoteloin** [comment]
Eventually it was my css that make the shadow not visible.

Now i have an other issue i can drag an element but i can drop it and it doesn't move my other element in the container. In oder to make it work i need to scroll my page to the top of an element and there it works but the shadow appears like 30px above my cursor.

**Comment by bevacqua** [comment]
Can't help you without a demo

**Comment by WillyPoteloin** [comment]
I understand i will make a codepen later today.
