### ISSUE TITLE
delay: true does not work on android chrome

### ISSUE THREAD

**Issue by atheroth** [bevacqua/dragula#130]
The draggable element is not registering any click events in mobile chrome, though it works fine in desktop chrome. If you click inside the container and outside the draggable elements, the click event trickles down to the inner element. That tells me the problem is with delay: true.

**Comment by bevacqua** [comment]
This is exactly the kind of bugs I want us tracking down and melting them in mosquito-killing-spray. Can you take a look and dig deeper on this one? Thanks!

**Comment by atheroth** [comment]
I'll look into it, sure.

**Comment by atheroth** [comment]
removing this line solves the problem.

https://github.com/bevacqua/dragula/blob/master/dist/dragula.js#L108

**Comment by atheroth** [comment]
might need something more specific than preventDefault() here.

**Comment by bevacqua** [comment]
Removing that line is bound to cause issues when we have both `dragula` and `click` events on an element. Solutions to the problem are more than welcome, though.

**Comment by atheroth** [comment]
It did cause issues like scrolling/refresh while dragging and other default behavior that was suppressed by the line in question. 

I know the problem now, though. When `preventDefault` is used on `touchstart` event, the mouse events don't fire, hence the `click` event does not fire. The details are here: 

http://www.html5rocks.com/en/mobile/touchandmouse/#toc-together

**Comment by bevacqua** [comment]
Can you fix it?

**Comment by atheroth** [comment]
I dont know yet sheep:

**Comment by bevacqua** [comment]
Let me know if `3.0.0` fixed it

**Comment by atheroth** [comment]
It's fixed. Thanks!
