### ISSUE TITLE
drake.destroy IE8 'Type mismatch'

### ISSUE THREAD

**Issue by sevenbest** [bevacqua/dragula#136]
I'm having a 'Type mismatch' error in IE8.

Having a hard time debugging. Everything appears undefined.

Is there a fix or a manual way of the deleting a drake instance?

![screen shot 2015-07-28 at 16 10 59](https://cloud.githubusercontent.com/assets/4357119/8935351/38b0dc48-3544-11e5-9fed-f2bb97976e4b.png)

**Comment by bevacqua** [comment]
I'm guessing it's trying to remove an event listener from an element that didn't exist. Can you give me more context or try to debug this yourself?

**Comment by sevenbest** [comment]
Thanks. I'll take another look.

To give more context. I have made it so only one element can be in each container. To do this on 'drag', I'm removing containers which have children. Then on 'dragend', using destroy and reinitialising  drake.
