### ISSUE TITLE
Adding/removing containers

### ISSUE THREAD

**Issue by Pouja** [bevacqua/dragula#14]
I was wondering, is it possible to remove and add the containers dynamically currently?
Because it happens in our use cases a lot that we drop or add a container depending on the situation at hand.

If not: as I was looking at the code. I think it can be either done by having an `update` function in the api that checks if the `containers` variable which was passed has changed and adds and removes the elements accordingly. Or just have an `add` and `remove` function added to the api.

**Comment by bevacqua** [comment]
Could you describe those use cases? Out of curiosity

**Comment by Pouja** [comment]
One of them is that we have groups of modules, where you can move one module from one group to another. But the user can also remove and add groups which in turn should also be able to "receive" and "give" modules.

**Comment by bevacqua** [comment]
Included in `1.4.0`

**Comment by Pouja** [comment]
Wow that was fast., thanks :+1: !
