### ISSUE TITLE
Gridster-like transition

### ISSUE THREAD

**Issue by bsitruk** [bevacqua/dragula#140]
Hi,
Is there a way to add a smooth animation on element being moved by the dragged one, as with gridster ?
I can't find the snippet of code that handles that.

Thanks.

**Comment by bevacqua** [comment]
Unfamiliar with Gridster. Please ellaborate.

**Comment by bsitruk** [comment]
I think you get the idea !
But I've already tried it. And it's not working for me.
Thanks for your help.
