### ISSUE TITLE
Nesting

### ISSUE THREAD

**Issue by yuzoolcode** [bevacqua/dragula#141]
Do you have any examples of dragged items being nested?
Thanks

**Comment by bevacqua** [comment]
Is the example with the drag handles on the demo page good enough? I swear I've seen one of these in an embedded demo somewhere in the issues. Can't recall which one though!

**Comment by yuzoolcode** [comment]
Of course - and got it - this looks the ticket:
https://github.com/bevacqua/dragula/issues/31
+1:
