### ISSUE TITLE
Missing some docs about styling / CSS classes used by dragula

### ISSUE THREAD

**Issue by hezad** [bevacqua/dragula#142]
That'd be great to have some infos in the README about the classes used by dragula for dragged items, mirrors and containers.

I checked the website and the README and couldn't find anything in both. I hope I didn't miss it.

**Comment by hezad** [comment]
Damn, I just checked dragula.css and there isn't anything to explain really ... Didn't think of checking this file first, sorry "bout that.

I don't close the issue since it could somewhat be useful to explain .gu-mirror, .gu-transit or .gu-unselectable but of course you can close it if you think it's useless.

**Comment by bevacqua** [comment]
Want to add some documentation to this effect?

**Comment by bevacqua** [comment]
See #144, we may want to add something like a "troubleshooting" section.

**Comment by hezad** [comment]
I just added a troubleshooting section to the readme with some doc about it. I'll push a pull request for that matter.

'hope the wording will be okay.
