### ISSUE TITLE
Dragged Element Wrong Position

### ISSUE THREAD

**Issue by saulshanabrook** [bevacqua/dragula#144]
Whenever I drag an element, its position appear much below that  of where my mouse cursor is.

![](http://g.recordit.co/IGW4w48R7V.gif)

**Comment by bevacqua** [comment]
What styles are you using? Are you setting `position` anywhere? It looks like you are, either that or using `float`s, would be my guess.

**Comment by saulshanabrook** [comment]
Yeah I am using `position: relative`.

**Comment by saulshanabrook** [comment]
@bevacqua Do you have a recommendation for how to troubleshoot this problem? I am trying to drag Bootstrap's  `list-group-item`s

**Comment by saulshanabrook** [comment]
I tried adding `position: absolute` to `.gu-mirror` and that sort of worked, but it only followed the cursor after some weird delay. It looks very odd now, I don't understand it:

![](http://g.recordit.co/we8nmludBZ.gif)

Also, are the previews of where the element will be dropped built in? They also don't seem to be working.

**Comment by bevacqua** [comment]
I'd try and not mess with the styles that much. If you need `position: relative` or some such maybe you should wrap your items or containers in elements that have that style.

**Comment by saulshanabrook** [comment]
OK I removed the styles from `.gu-mirror`. So this is what it looks like. The item is stuck to the left side at that position no matter where I drag:

![screen shot 2015-08-02 at 10 15 02 pm](https://cloud.githubusercontent.com/assets/1186124/9029583/1115a2da-3964-11e5-9bfc-d4789127e794.png)

I think because the position is not fixed. So if I do add the `position: fixed to the `.gu-mirror`, then I am back to the other problem where it drags behind slowly and erratically. I am trying to copy the styles from the example page, but I can't figure out what is making it act so differently.

**Comment by bevacqua** [comment]
Sounds like `transition` is slowing it down maybe?

**Comment by saulshanabrook** [comment]
Yep! That was silly of me, thank you. So all I needed was

```css
.gu-mirror {
  position: fixed;
}
```

**Comment by bevacqua** [comment]
Are you not adding `dist/dragula.css` to your page?

**Comment by saulshanabrook** [comment]
@bevacqua No I am not, I will now, didn't know I should be..

**Comment by bevacqua** [comment]
Yep, you definitely should!.

**Comment by saulshanabrook** [comment]
Yep once I imported that everything worked great! :+1: Thank you so much for your help!

**Comment by 1linan** [comment]
> Are you not adding `dist/dragula.css` to your page?



> Yep! That was silly of me, thank you. So all I needed was
> 
> ```css
> .gu-mirror {
>   position: fixed;
> }
> ```

Hi, I have a question for you.
Is the element being dragged you set to absolute positioning?
Or is it that the element being dragged is not positioned, and only setting  .gu-mirror   position: fixed !important;
then you can drag and drop normally
