### ISSUE TITLE
Force drop at index

### ISSUE THREAD

**Issue by adamterlson** [bevacqua/dragula#146]
I have two containers in copy mode.  When dragging from the first to the second, is there a way to only allow the user to insert the copied item at the end of the second container's list of items?

More generally, perhaps it'd be useful to force insertion into the new container at an arbitrary index.

**Comment by bevacqua** [comment]
Yes. Check out the `accepts` method, the fourth argument is the next sibling. You can use that for your condition. See the documentation.

**Comment by adamterlson** [comment]
Excellent.  Thank you for the help.
