### ISSUE TITLE
Start dragging after a `mousemove` event

### ISSUE THREAD

**Issue by lkrids** [bevacqua/dragula#147]
This library is making the assumption that the user is going to drag an item when they mousedown on an element (https://github.com/bevacqua/dragula/blob/master/dist/dragula.js#L114), except if it is a ```<a>``` or ```<button>``` (https://github.com/bevacqua/dragula/blob/master/dist/dragula.js#L203).  This prevents the user from dragging an item if they mousedown on a child ```<a>``` or ```<button>```.

I think the best solution would be to start the drag event when a drag action takes places (delta in mouse x,y after mousedown).

**Comment by bevacqua** [comment]
Yup, but there's an option to override that behavior.

**Comment by lkrids** [comment]
Are you referencing the delay option?

**Comment by bevacqua** [comment]
Nope, `invalid` option

**Comment by lkrids** [comment]
Thanks, @bevacqua.  The invalid function is called on mousedown.  The invalid function seems to give you 2 different options when a ```<a>``` is clicked: the browser navigates to the href, or the drag event starts.  I think the more accurate use case coverage would be if the user clicks a ```<a>```, the browser navigates to the href, if the user clicks and drags a ```<a>``` the drag event starts.  Do you agree?

**Comment by bevacqua** [comment]
That's a very obscure use case. I don't want to build it into `dragula` (`dragula` would have to handle the redirection because `delay`). Outside of `dragula`, you could set `invalid` to return false, `preventDefault` on clicks to the anchor tag, and if after `delay` the `drag` event was never fired, then you navigate away.

**Comment by lkrids** [comment]
I might not be describing the use case correctly.  The scenario I'm talking about is inside a container there is a ```<a>``` tag with an href attribute and the user clicks it.  

Currently, there seem to be at least 2 ways of handling it:

1) invalid function - you can specify that any mouse events on/over an ```<a>``` shouldn't/should trigger dragging events.
2) delay - add a delay to starting the dragging events so the user who clicks something won't start a drag.  However, there is also a delay when they start dragging.

Why not just start dragging after mousedown AND after mousemove?

**Comment by bevacqua** [comment]
Off the top of my head that sounds doable and something I'd like to do. Can't think of any drawbacks right now.

**Comment by bevacqua** [comment]
Wow the API is very simplified by doing this. Yay.

**Comment by bevacqua** [comment]
Please see: https://github.com/bevacqua/dragula/tree/no-delay-clicks

**Comment by bevacqua** [comment]
Implemented in `3.0.0`
