### ISSUE TITLE
Question about containers

### ISSUE THREAD

**Issue by benjick** [bevacqua/dragula#149]
Hi.

Is it possible to have containers with different settings?

I want one container which is copy only and doesn't take new items and then I have X other containers that I want to have as targets. Like http://rubaxa.github.io/Sortable/ under "Advanced groups"

**Comment by bevacqua** [comment]
Sure. Just use `if` statements

**Comment by bevacqua** [comment]
e.g

```js
dragula(containers, {
  copy: true,
  accepts: function (el, target) {
    return target !== copySource;
  },
  moves: function (el, container) {
    return container === copySource
  }
});
```
