### ISSUE TITLE
Drop not working

### ISSUE THREAD

**Issue by WillyPoteloin** [bevacqua/dragula#15]
The drag work but there is no drop and no interaction with containers.

This is cause by setting .gu-mirror position absolute but if i don't set position absolute the mirror is not following my cursor and is just stick in the bottom left corner.

Codepen : http://codepen.io/anon/pen/yNBVqa

**Comment by bevacqua** [comment]
http://codepen.io/bevacqua/pen/mJbOQg

**Comment by WillyPoteloin** [comment]
Ok thanks just forgot to include your css !
