### ISSUE TITLE
Please consider adding more examples, including simpler ones, to the main demo page

### ISSUE THREAD

**Issue by shevegen** [bevacqua/dragula#157]
Hello. I think you lately wrote some blog entry, which I found via reddit (I think) and then I found dragula. The effects were nice, however had being the javascript noob that I am, I was not sure how to use it.

You have a lot of information, but my (poor) brain works best when I have very simple examples.

At:

http://bevacqua.github.io/dragula/

You offer lots of fancy examples.

This is all nice. I was staring at the documentation, but I was unable to distill what exactly is required to get this to work.

I think googled, and found this page:

http://ryanfunduk.com/dragula-test.html

Thanks to that simple example there, I got things to work. :)

Now this may be odd but for some reason, simple examples without eye-candy work best for me.

I do not know how this is for different users, I assume everyone is different and people want to see the flashy eye candy stuff first.

My suggestion would be any of the following, perhaps you can consider this in a later release:

- Either add more examples, including simpler ones. Perhaps on a separate page

OR

- Just that single row-example with the "unordered list" tag like in the example above.

An alternative may be to add some standalone .html file such as "simple_example.html"
or so where people can just copy/paste the source and play around with it, without
getting confused by the many other examples. Anyway, this is just a suggestion, just
close it if you feel that it won't fit - thanks.

PS: Perhaps this may be obvious to other visitors, but when I looked at the javascript
code at the main readme of the project, at "Here's an overview of the default values.", I
got totally confused and sidetracked by the many options.

**Comment by bevacqua** [comment]
I don't see how the examples could be any simpler. A standalone example would be somewhat useful, I guess?

**Comment by bevacqua** [comment]
PR for simpler or more examples are super welcome
