### ISSUE TITLE
How to disable the drop of a item to other container, just for a specific item

### ISSUE THREAD

**Issue by luanfonceca** [bevacqua/dragula#161]
Hi everyone, i have the follow scenario. I have two containers `Approved talks` and `Disapproved talks` with two kind of itens `Proposals` and `Activities`. The `Proposals` can be dragged in the two containers, but the `Activities` can be dragged just in the first container.

1. This should still work: http://recordit.co/JzvAToy4jq.gif
2. This should still work: http://recordit.co/pYOjkHeMdV.gif
3. This should still work:  http://recordit.co/wRA2AAOL4N.gif
4. This should not  work: http://g.recordit.co/wRA2AAOL4N.gif

If you guys have some though about how i can do that, please feel free and thanks in advance. 

o/

**Comment by bevacqua** [comment]
Check out the `accepts` method in the documentation.

**Comment by luanfonceca** [comment]
Thanks, i already did tried, but i was using it like `.on('accepts', ...)`.

o/
