### ISSUE TITLE
Dragula handle class names don't work when an element has mutiple classes

### ISSUE THREAD

**Issue by joe-liquid** [bevacqua/dragula#162]
If you are trying to set the handle by a class and the element has other classes the item will not drag. Is this a bug or do you not allow the handle element to have more that one class?

**Comment by joe-liquid** [comment]
In the example you have on your site if I try and add a class (my-other-handle-class) as follows then I am unable to drag the item:
<div>
    <span class="handle my-other-handle-class">+</span>
    Move me, but you can use the plus sign to drag me around.
</div>

**Comment by jameswyse** [comment]
The `handle` argument passed to the `moves` function is actually the HTML element that was clicked on. The example uses `handle.className` to check the class but that contains everything in the `class` attribute, so isn't ideal when there's multiple classes!

You could use [`classList`](http://html5doctor.com/the-classlist-api/#contains) instead, like so:

```javascript
dragula([$('left5'), $('right5')], {
  moves: function (el, container, handle) {
    return handle.classList.contains('handle');
  }
});
```

**Comment by joe-liquid** [comment]
Amazing! Thanks for the quick response.

**Comment by CalebKester** [comment]
If anyone else is having issues with this, here's how you can use jquery to solve this.

```
moves: function (el, container, handle) {
	return $(handle).hasClass('handleClass');
}
```

(I was having issues so I figured I'd post my solution here if anyone else needs it.
