### ISSUE TITLE
Dynamically added items

### ISSUE THREAD

**Issue by assimovt** [bevacqua/dragula#167]
Ahoy.

I have dragula setup and it works nicely, thanks for a nice plugin :+1: 

However, when I add or remove items dynamically to the list, it breaks. I can see in the console that in the working version there is only one instance of `gu-mirror` created, but in the broken several. Is there any fix for that?

Thanks!

**Comment by bevacqua** [comment]
Sounds like a bug. Could you look into it?

**Comment by assimovt** [comment]
Sorry, couldn't find why it happens. Mind checking it out?

**Comment by beatfreaker** [comment]
@assimovt can you be more specific or can you post your code snippet of what you are doing which leads you to this bug?

**Comment by bevacqua** [comment]
There's nothing inherent in `dragula` that causes the issues you're seeing, it must be something wrong in your code
