### ISSUE TITLE
Ignore specific elements?

### ISSUE THREAD

**Issue by voidale** [bevacqua/dragula#168]
I have to say finally! Finally I found an awesome drag and drop package it's really a joy to work with. Thanks a lot.

I'm trying to figure out how to ignore div with specific class and would love to get some guidance

here is my layout:
````
<div class="container">
  <div class="date">
    <h4>Aug 14th</h4>
  </div>
  <div class="post">..</div>
  <div class="post">..</div>
  <div class="date">
    <h4>Aug 21th</h4>
  </div>
  <div class="post">..</div>
...
</div>

````

I would like to ignore the `.date` divs because it's just a UI but it's actually part of sortable elements I have a handle on post div that I use to drag and drop so date isn't really dragable but it's part of the order when I change the order here is an example I'm trying to accomplish: http://s8.postimg.org/6uspejw2t/good.gif

You can see that "another" changes order with "fdsfsd" and not with the date like it's with my regular setup I would like to ignore it :) hopefully it makes sense? Thanks!

**Comment by bevacqua** [comment]
You need to use [`moves`](https://github.com/bevacqua/dragula#optionsmoves).

**Comment by voidale** [comment]
@bevacqua Hi, can you give me more information should I initiate the container once `dragula([document.querySelector('.container')]` or each post should be a container for this to work? like `dragula(document.querySelectorAll('.post')` if each post is separate container it seems to make more sense that it will work but when it's just once container I'm having problems figuring out the flow of it.

**Comment by ilanus** [comment]
@voidale I think it's impossible with Dragula, I understand you need to actually insert it before and after those disabled elements. It's really useful I can see how it can be used but not sure really, Maybe you need a swappable plugin where you switch one with other and not sorting

**Comment by voidale** [comment]
@ilanus yeah the jsbin is perfect example of what I'm trying to achieve `accepts` options doesn't seems to be the solution because I need to disable "ignore" those elements I tried using accepts but it doesn't seems to be right way to do this :(

**Comment by voidale** [comment]
@bevacqua can you please help?

**Comment by bevacqua** [comment]
```js
accepts: function (el, target, source, sibling) {
  return sibling === null || $(sibling).is('.post');
}
```

**Comment by voidale** [comment]
@bevacqua Thanks! Almost, It's still behaves like separated lists containers where you just move from 1 to other, Is it possible to make it "switch" this is why I mean "ignore" here is the code uploaded to jsbin

 you can see how it behaves:
http://jsbin.com/hapajapose/edit?js,output

and here is to what I'm comparing it to: 
http://jsbin.com/mapozifezu/edit?js,output

It seems to be very close but I think to accomplish this with dragula we manually need to set insert before or after `.date` is it possible? to really skip that div.

**Comment by voidale** [comment]
@bevacqua had a chance to review?

**Comment by voidale** [comment]
@bevacqua sorry to bother you but I'm still having problems with this can you see the jsbin I have posted? If this is even possible to do with dragula? Every variation I'm trying to do just comes close but I think It seems something is missing to make it work :(

Thank you.
