### ISSUE TITLE
Does this work with forms?

### ISSUE THREAD

**Issue by Jnesselr** [bevacqua/dragula#170]
I know this is more of a question and not an issue, but I couldn't find another place to ask.

I want to have two boxes, A and B where the user drags the elements from B into A in the order they want them. I want them to then be able to click a button and have it post like a normal form (CSRF token and everything). Would I just make the individual elements an input and put the container inside the form class?

**Comment by pcanterini** [comment]
If I understand your question correctly, you *should* be able to do what you described just by having the elements on the second container inside a form tag, even with hidden inputs. 

I guess this could get a bit more complicated depending on your needs but here is a very basic demo:
[Codepen Dragula form](http://codepen.io/pcanterini/pen/PPZPKY)

**Comment by Jnesselr** [comment]
Oh yeah, forgot about this. I eventually did get it working by using hidden inputs and making the block contain text that matched the hidden input.
