### ISSUE TITLE
[Question] Swipe suppressed on mobile devices?

### ISSUE THREAD

**Issue by hrstoyanov** [bevacqua/dragula#171]
When I tried the Dragula samples on my Nexus 5 phone, I noticed the swipe gestures are not working in the containers, because Dragula interprets them as drag-and-drops. This makes it difficult to scroll up and down on mobile device, especially if the Dragula-enabled  container takes most of the screen. 

I am sure this is a known issue, one workaround for which is to use handles as shown in the samples. Any other ideas?

Btw, this is a great library!

**Comment by bevacqua** [comment]
So you want to be able to drag stuff *and* swipe? Yeah you're better off using drag handles
