### ISSUE TITLE
Identifying element(s) "moved out of the way" by dragging/dropping a neighboring/new element

### ISSUE THREAD

**Issue by nickleus** [bevacqua/dragula#172]
I need to b able to identify/log (i.e. update HTML5 data attributes for [persisted] layout ordering of elements, e.g.: data-row="1" data-col="2") when a neighboring dragula element is "moved out of the way" as a result of another element being dragged n moving into its position.

i need to b able to persist the new ordering of elements in a row, in json, using ajax--that part i can manage myself, i just need to know how to "capture" that "moved out of the way" event of the element(s) NOT being dragged.

ideas?

**Comment by nickleus** [comment]
the elements i'm dropping into- or dragging around in- the row (container) r inline ckeditor instances, so here's some *metacode* i sketched out for a possible solution/implementation:

```
on.drop {

	ckeditorDivsArray = container.getchildren().find('.wysiwyg')
	// r these returned sequentially/in order? "metacode" below assumes that
	loop(ckeditorDivsArray) {
		// get previous HTML5 data attribute values for elem
		oldColNum = data-col.val
		oldRowNum = data-row.val

		// update HTML5 data attributes
		newColNum = loop var iterator current val // colNum
		newRowNum = container.data('row') // rowNum
		data-col.val(newColNum) // set
		data-row.val(newRowNum) // set

		// impl ajax>json save
			// TODO new php function: updateElemCoordinates(oldColNum, oldRowNum, newColNum, newRowNum)
			// do ajax post
	}
	
}
```

**Comment by bevacqua** [comment]
You can use `accepts` to update those attributes.

**Comment by nickleus** [comment]
i figured out how to get the "sibling" element, in the "drop" event:

// sibling to the left of moved/inserted item ("drop" parameter: "el")
`var previousSibling = el.previousElementSibling;      // returns "null" if new col position == 1; else, entire sibling DOM node`

then use jQuery to get the data attributes, e.g.:
// ...if-test code to check for null...
// get new col number/position
`var newColNum = $(previousSibling).data('col');`
