### ISSUE TITLE
Unable to drop into container which has been added dynamically via AJAX

### ISSUE THREAD

**Issue by townhouse** [bevacqua/dragula#174]
Great library, thanks for your work on this.

I have drag and drop setup and working correctly. If I replace some of the containers with HTML received from an AJAX call then those containers no longer accept any droppable elements. The `drag` and `over` callbacks still fire.

I've tried various things to rebind dragula behaviour but still unable to get these containers to accept any elements. Any ideas?

Thanks.

**Comment by bevacqua** [comment]
Use the dom instead of replacing html.
