### ISSUE TITLE
Input focus not working

### ISSUE THREAD

**Issue by nmsdvid** [bevacqua/dragula#176]
When using the awesome dragula plugin I came across a bug, the input element value can't be modified, I have test it on various browser so it doesn't seem like a browser specific bug. I have made a quick demonstration about this issue, https://jsfiddle.net/qoaqba62/

**Comment by bevacqua** [comment]
Looks like a bug. Yes. https://jsfiddle.net/qoaqba62/1/

**Comment by arthurdk** [comment]
Temporary workaround :  https://jsfiddle.net/qoaqba62/2/

**Comment by bevacqua** [comment]
It's weird because we just prevent the default event on `mousedown` and `mousemove`, but not `click`. I presume `focus` happens on `mousedown`, maybe. We need the `mousedown` prevention, so a potential fix might be to just `.focus()` on `e.target` during `mousedown`.

**Comment by bevacqua** [comment]
Yeah. `mousedown` it is

**Comment by nmsdvid** [comment]
Yes the fix works.

**Comment by bevacqua** [comment]
Can you pr?

**Comment by bevacqua** [comment]
Fixed in `3.0.5`

**Comment by nmsdvid** [comment]
thank you, works like a charm.
