### ISSUE TITLE
Is it possible to add new elements to `dragula` dynamically?

### ISSUE THREAD

**Issue by Krasnyanskiy** [bevacqua/dragula#178]
Here is my [example](http://jsfiddle.net/krasnyanskiy/6vdq32hs/3). I want to create a new element and add it to dragula list. Does dragula support such behaviour?

**Comment by bevacqua** [comment]
Sure, but you're not adding it to the list. See [demo](http://jsfiddle.net/gn3sff8v/)

**Comment by Krasnyanskiy** [comment]
Thanks.

**Comment by btoueg** [comment]
I've also made the containers dynamic. See [demo](http://jsfiddle.net/gn3sff8v/9/)
