### ISSUE TITLE
List position

### ISSUE THREAD

**Issue by btecu** [bevacqua/dragula#180]
When reordering using drag, is there any way to know the new position? Maybe also include the neighbor elements?

**Comment by bevacqua** [comment]
Yes, `sibling`, the 4th argument in `accepts` tells you what's the next sibling for the position you're dragging `element` into. It'll be `null` if it's going to the last position.

**Comment by btecu** [comment]
Seems like the wrong place to have, since it will make tens if not hundreds of calls when moving around. Shouldn't sibling be on `dragend`?

**Comment by bevacqua** [comment]
Well, you could use the `shadow` event as an alternative.
