### ISSUE TITLE
Support Dragging Multiple Items

### ISSUE THREAD

**Issue by mendeza** [bevacqua/dragula#181]
Please consider supporting multiple item dragging: at root this would depend upon  **multiple selection**. It should make no difference if the selected items are contiguous or non-contiguous. For mobile compatibility, modifier-key usage is a no-go, or else there could be more than one (configurable) option to effect the multiple selection.

**Comment by mendeza** [comment]
Forgive me, I belatedly saw this: https://github.com/bevacqua/dragula/issues/50
However, could you please elaborate on this use case in your API documentation, and perhaps add a demo?

**Comment by bevacqua** [comment]
This is unsupported by `dragula` and out of scope. If we were to implement this I'd do it outside of `dragula` core, maybe with a module that instantiates multiple `drake` instances and uses them to coordinate many drags at the same time through the programmatic api.
