### ISSUE TITLE
Forward javascript events

### ISSUE THREAD

**Issue by jnhmn** [bevacqua/dragula#183]
Is it possible to forward the events, so that I can get the mouse position of the cancel and/or drop event?

I want to use dragula to place an object at a absolute position, therefore I need the mouse position of the drop event. I do the positioning myself, so I need only the coordinates.

**Comment by bevacqua** [comment]
Drop doesn't necessarily happen after a mouse event, it could also be triggered programatically. I would do this outside of `dragula`.

```js
var lastReleased
var drake = dragula(el)
drake.on('drop', drop)
el.addEventListener('mouseup', released)
function released (e) {
  lastReleased = e
}
function drop () {
  // use lastReleased
}
