### ISSUE TITLE
Is it possible to make only a certain subelement cause drag?

### ISSUE THREAD

**Issue by xueye** [bevacqua/dragula#186]
I'm trying to devise a way to accomplish the following:

```
<div class="list">
     <div class="container">
         <div class="draggable-icon">some icon here</div>
         <div class="other-stuff">Other stuff here</div>
     </div>
</div>
```

I want to have all the `.container` items in `.list` draggable, but only by dragging on a `.draggable-icon`, but can't seem to figure out how to accomplish that. How should I go about that?

**Comment by bevacqua** [comment]
See the demo
