### ISSUE TITLE
Swap between item

### ISSUE THREAD

**Issue by claudchan** [bevacqua/dragula#189]
Hi,
Is it possible to swap between the 2 items?

**Comment by bevacqua** [comment]
Sure, move the second item in code when events fire

**Comment by claudchan** [comment]
Thanks but appreciate if someone can provide an example to code please?

**Comment by VeeK727** [comment]
This is what i used. Hope it helps


```
dragula.on('drop', function(el, target, source, sibling){
	var swappee = $(target).find('img').not(el);
	swappee.appendTo(source);
});
```

In my case, the containers hold one image so if you drag one image into another container, the other image will be moved to the first image's container.
