### ISSUE TITLE
Turning it on/off

### ISSUE THREAD

**Issue by samcov** [bevacqua/dragula#19]
I need to be able to go into drag mode, and then turn it off. 

Is there a way to do that?

The only way I think it could be done is to keep a Drake object around and add/remove containers, is that the way?

**Comment by bevacqua** [comment]
Yes. Add/Remove containers or destroy and recreate instances.

**Comment by samcov** [comment]
Actually I found a better way, using the options.moves function.

I return a variable that determines if I want drag/drop to be active, and it works perfectly.

Thanks!
