### ISSUE TITLE
Flickering when dragging something over an area that then dissappears because of a resize event

### ISSUE THREAD

**Issue by moldcraft** [bevacqua/dragula#190]
Hello,

We have [a builder](https://vimeo.com/105004388) and it has [a problem](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/25): In some cases it's hard to move an element the desired position.

Currently we use jquery-sortable. I tried other sortable plugins but dragula has the most stable behavior. 
For our builder, I want to replace jquery-sortable with dragula, but it also has [a problem](https://static.md/112f4010962bde64851dbb66a22fbc89.gif): When you try to move a shortcode from one column to another, it moves out of that column and all other columns are going under it. [Here](http://sourcebox.io/e5b9301c3d61f59b7a540af5a6f7e330/html) you can test it.

That behavior is correct, the plugin works fine, but it's not handy in case of our builder elements structure.

An idea how to fix this: Please give us a parameter `mirrorDelay`. When we drag an element (shortcode), the mirror element should not change its position until the mouse stopped and `mirrorDelay` milliseconds passed. So while moving a shortcode around, it will not change the columns positions and all columns will stay still, then when I decide in which column to place the shortcode, I will stop the mouse over it, after a small delay the mirror will appear in it, and I will drop it there.

What do you think?

**Comment by bevacqua** [comment]
If I understand correctly, something like #75 would fix this issue you're having?

**Comment by moldcraft** [comment]
No, it will not fix. The shortcode can be moved freely wherever you want, not just to the nearby column (like in that gif example). For e.g. you can move a shortcode in a column in another section (not just horizontally or vertically).

The problem is when you start to move something, elements (columns) start to reorder and shiver like crazy. That's why I think that a delay in mirror (preview) element re-position can solve this.

**Comment by bevacqua** [comment]
Oh! That's an easy fix. Missed the gif. You should use `accepts` to validate where the item is being dropped.

```js
dragula(containers, {
  accepts: function (el, target) {
    return target !== something
  }
})
```

**Comment by moldcraft** [comment]
Do you mean to deny shortcodes to be moved outside columns?

If yes, that is not a solution, in our builder you can place elements wherever you want, then in background (on post save) will be created the necessary elements to fix the grid:

* if shortcode is (alone) on first level, will be created `section > column >` for it
* if shortcode is in section, will be created `column >` for it
* if column is (alone) on first level, will be created `section >` for it

**Comment by bevacqua** [comment]
Ah okay now I see what you mean. There's no good fix for the issue you describe besides CSS at the moment. A delay would just ...well, delay the inevitable

**Comment by moldcraft** [comment]
> A delay would just ...well, delay the inevitable

Yes, but I don't know another solution.

Thank you

**Comment by moldcraft** [comment]
https://www.bountysource.com/issues/26357018

**Comment by bevacqua** [comment]
Closing as out of scope. You can use CSS to prevent flickering by making containers larger.

**Comment by moldcraft** [comment]
Which containers? Can you make a screenshot?

**Comment by moldcraft** [comment]
Sorry, I don't understand which containers. Can you make a screenshot or describe somehow what do you mean?

**Comment by bevacqua** [comment]
On line https://github.com/bevacqua/dragula/blob/master/dragula.js#L151 we should add `nextEl(el)` as the fourth parameter. We need documentation for these two changes as well.
