### ISSUE TITLE
Vue bridge

### ISSUE THREAD

**Issue by fungku** [bevacqua/dragula#192]
I am not sure how to get this to work in [vue.js](https://github.com/yyx990803/vue). Would love to see a wrapper to work with it.

Currently I get an error `Uncaught TypeError: Cannot assign to read only property 'moves' of .articles tbody`.

I'm assuming it is to do with [these being read only](http://vuejs.org/api/instance-properties.html) (derp), but as someone who just does enough javascript to make my front-end stuff bearable, I don't know what to do about it.

**Comment by bevacqua** [comment]
You should probably ask in Vue's repo. Dragula provides a very plain and simple API that doesn't do anything mystical.
