### ISSUE TITLE
Work with multiple columns in a single row

### ISSUE THREAD

**Issue by HTML-master** [bevacqua/dragula#196]
Thank you for a wonderful plugin.
I had a problem with a plugin setting to work with multiple columns in a single row.
Here are fiddle - https://jsfiddle.net/fcy7y74o/2/
It is necessary that the blocks "222" and "444" could be dragged to any location within the container with the identifier "container". Blocks "222" and "444" must always be stationed on the left and right edge of the container.
I would be grateful for any help!

**Comment by moldcraft** [comment]
I think the mixture of non-float float:left and float:right elements is weird and seems to be wrong. I would be better if all will be float:left or float:right or (non-float) display:inline-block

**Comment by HTML-master** [comment]
Unfortunately i cannot set blocks "222" and "444" to display:inline-block, because in this case I will be required to remove the padding between blocks. If someone does not know - between blocks that are set as display:inline-block appear indent 3 or 4 pixels depending on the browser.
Try to set all elements float. Thanks.
