### ISSUE TITLE
Drag Handles

### ISSUE THREAD

**Issue by fabien** [bevacqua/dragula#20]
It would be great if one could specify a css selector for drag handles.

**Comment by fabien** [comment]
A naive implementation, perhaps: https://gist.github.com/fabien/20f31a2e3f676849d7ca#file-gistfile1-js-L89

**Comment by bevacqua** [comment]
I implemented this by providing a third argument to `moves` that exposes the original `e.target`. This can be used to determine any sort of drag handling behavior. You could just check for a class on that specific element, or you might want to walk up the DOM tree and see if any parents match a class, etc. It's in `1.5.0`
