### ISSUE TITLE
Dragula in a Bootstrap Modal: incorrect offset of mirror

### ISSUE THREAD

**Issue by fabien** [bevacqua/dragula#201]
When using Dragula in a Bootstrap Modal, the offset of the Modal is not correctly handled, which doubles the `left` and `top` values of the dragged mirror (as calculated in `getOffset`). This should be compensated somehow.

Note that I'm setting `mirrorContainer` to the container within the Modal (in order to keep the styling of the elements while dragging). If I don't specify `mirrorContainer` it sort of works, but it's not really desirable - it's an important option of my use case.

**Comment by fabien** [comment]
The following hack seems to work specifically for the Modal setup.

@bevacqua I'm sure you're more familiar with the implications here - we should probably have an option to specify a parent container selector which then indicates the offset calculation to use.

```
function getOffset (el) {
  var rect = el.getBoundingClientRect();
  return {
    left: getScroll('scrollLeft'),
    top: rect.top - rect.height
  };
}
```

**Comment by bevacqua** [comment]
Read the CSS documentation

**Comment by fabien** [comment]
@bevacqua I'm puzzled? I don't see anything there that would be helpful in this case, unless you see the explanation on `mirrorContainer` to write off the issue?

**Comment by bevacqua** [comment]
Dragula relies on positioning via CSS and Bootstrap breaks a lot of the assumptions `dragula` makes

**Comment by fabien** [comment]
I think that's an over-generalization of the problem, especially considering the widespread adoption of Bootstrap. More specifically, most modal implementations (regardless of Bootstrap's CSS) will mess with the offsets of items by the very nature of the way an overlay is positioned.

Unfortunately there's no way to 'reset' this positioning in a way that Dragula will has the proper offsets in this case. Perhaps you could think about exposing `getOffset` publicly, so it at least can be overriden?

**Comment by bevacqua** [comment]
I would rather try and fix this in a generalized automagical way if possible before exposing yet another option. Can you look into doing that?

**Comment by fabien** [comment]
I think a `position: fixed` ancestor is the tell-tale sign that a different offset calculation should be used. It will probably be part of an automagical solution. What do you think? Is this something you could look into as well?

**Comment by bevacqua** [comment]
No. I don't have the time

**Comment by wkeese** [comment]
I hit (presumably) the same problem with carbon.  The mirror image is `position: fixed` so that makes it immune to effects from ancestors that are position fixed, absolute, or relative.   However, the problem as documented on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/position), and is true for me, is:

> when one of its ancestors has a transform, perspective, or filter property set to something other than none
