### ISSUE TITLE
use two dragula([])

### ISSUE THREAD

**Issue by WindWen** [bevacqua/dragula#205]
first i want to move the row (class name) from class:left to class:right, so i can write like this : dragula([document.querySelector(".left"),document.querySelector(".right")]
Then i want change the row's sort , so  i can write like this.
dragula([document.querySelector(".right"),document.querySelector(".row")]
And this code is no work,Did you tell me what happen?

**Comment by bevacqua** [comment]
Maybe use Google Translate? I have no idea what you're trying to explain here.
