### ISSUE TITLE
allow custom css class 

### ISSUE THREAD

**Issue by beatfreaker** [bevacqua/dragula#206]
Allow option to apply custom class for mirror instead of default `gu-mirror` or `gu-transit` checked this [dragular](http://luckylooke.github.io/dragular/#/docs/exampleCustomClasses)

**Comment by justalever** [comment]
I'm several years late to this issue but I'm using dragula in multiple parts of an app. CSS as you can imagine is conflicting because I can't scope/namespace it to behave a bit differently when dragging. This would be a really nice feature that I'm not sure why is out of scope. Maybe reconsider?
