### ISSUE TITLE
Double Click to select all text in an input

### ISSUE THREAD

**Issue by brett-anderson** [bevacqua/dragula#208]
Hi there, not sure if this is a bug, but double clicking to select all text does not work on input fields. An example is here https://jsfiddle.net/qoaqba62/2/. (Just used a jsfiddle from another issue). Love the plugin, is working like a charm besides this small issue.

**Comment by brett-anderson** [comment]
Ended up using jQuery to select the text on double click.

```javascript
doubleClick(input) {
    $(input).select();
  },
```
Seemed to be a fix for our UX needs.

**Comment by bevacqua** [comment]
Fun that I hadn't noticed, single clicks don't work either by default. Thanks

**Comment by beatfreaker** [comment]
@bevacqua any idea how we can handle this issue?

**Comment by bevacqua** [comment]
Well we would have to do something different than [simply `.focus()`](https://github.com/bevacqua/dragula/blob/master/dragula.js#L111) as we're currently doing.

**Comment by bevacqua** [comment]
PR #223 seems to fix it. @beatfreaker can you verify?

**Comment by beatfreaker** [comment]
@bevacqua seems to be working as expected :+1:

**Comment by bevacqua** [comment]
Fixed in `3.4.1`

**Comment by bevacqua** [comment]
You guys may also be happy to know that `3.5.1` adds an option which allows text _range_ selection in inputs. You can select text in an input using the mouse as long as you don't leave the input surface. If you leave the surface of the input element, then dragging will start (granted that you're still holding the mouse button)

**Comment by brett-anderson** [comment]
@bevacqua cool! Keep up the good work!

**Comment by beatfreaker** [comment]
@bevacqua amazing :+1:
