### ISSUE TITLE
index

### ISSUE THREAD

**Issue by dbarriga** [bevacqua/dragula#209]
Hi, just one question, what is the way to know which is the index of the element you are dragging.

Thank you

**Comment by bevacqua** [comment]
The index? Use the dom. Roughly: `el.parentElement.children.indexOf(el)`

**Comment by elgubenis** [comment]
the result of el.parentElement.children is a HTMLCollection which does not have an indexOf method, is there any native supported alternative?

**Comment by elgubenis** [comment]
should be: 
```js
[].slice.call(el.parentElement.children).indexOf(el)
```

**Comment by Hiswe** [comment]
Using es2015 you can also make:

```js
[...el.parentElement.children].indexOf(el)
```
