### ISSUE TITLE
Uncaught TypeError: Cannot read property 'msPointerEnabled'

### ISSUE THREAD

**Issue by sherbrow** [bevacqua/dragula#213]
Seen in other projects with "browserify packaging" :
https://github.com/hammerjs/hammer.js/issues/424
and their fix https://github.com/lucasgunn/hammer.js/commit/81bab8ee86cf1c8dd386796417fdbf348104b746

Browserify packaging (if it is the process that causes it) seems to pass `this` when calling as the `global` namespace [dragula.js#L825](https://github.com/bevacqua/dragula/blob/49f51d369ab6ee1b5de5d49d8c3e755e119aa0e3/dist/dragula.js#L825)
If the `<script>` is put in the body, `this` is the `document`, not the `window`, causing `global.navigator.msPointerEnabled` to be invalid (`navigator` is only a `window` property) [dragula.js#L506](https://github.com/bevacqua/dragula/blob/49f51d369ab6ee1b5de5d49d8c3e755e119aa0e3/dist/dragula.js#L506)

I propose a fix by using directly `window` to access `navigator`, since I don't see why that property should be namespaced/mocked up for tests or anything.

NB: your index.html is working fine probably thanks to the omitted html and body tags

**Comment by bevacqua** [comment]
Use the file in `dist` directory for raw use without package managers
