### ISSUE TITLE
Feature request - cleaning a container of elements before dropping a new one 

### ISSUE THREAD

**Issue by UnrulyNatives** [bevacqua/dragula#217]
I couldn't find any clue in your docs...

Consider this case: 
- I have four boxes where I drop items. They are defined and work fine:

    dragula([$('whitelist_1'), $('whitelist_2'), $('blacklist_1'), $('blacklist_2'), ],

- only one of them, say `blacklist_2',  can accept only one element. 
So if the box already contains one element, it should be spilledwhen I drop the new one. 

As of now, I simply remove the previously put elements by jQuery. 
Is such a feature already supported within your script?

**Comment by bevacqua** [comment]
Use `accepts`.

```js
accepts: function (el) {
  if (el === blacklist_2) {
    return el.children.length === 0
  }
  return true
}
```
