### ISSUE TITLE
Drag and drop content change

### ISSUE THREAD

**Issue by Milkshakeriot** [bevacqua/dragula#218]
Attached example.

What is the best way to do this with dragula, I have been unable to find any examples of this and do not really have the expertise to do it.
![help](https://cloud.githubusercontent.com/assets/8051157/10185206/1628fa1e-6778-11e5-8c93-6882b5e54e2e.png)

**Comment by ggggwffgqeg** [comment]
How to solve

**Comment by ben-pr-p** [comment]
What are you using to make the circle?

**Comment by bevacqua** [comment]
Use Slack for support requests. See #248.

**Comment by goper-leo** [comment]
How to solve? Thanks

**Comment by AllenBird** [comment]
How to solve? I didn't find in https://dragula.slack.com/messages
