### ISSUE TITLE
Customize "shadow" element / visual feedback

### ISSUE THREAD

**Issue by demrks** [bevacqua/dragula#219]
Is there any way to customize the look of the "shadow" element (visual feedback)? I could't find anything in the instructions.

Just as an example: 
![Shadow example](http://g.recordit.co/EktHxmn6tl.gif)

**Comment by bevacqua** [comment]
Sure, use CSS.

**Comment by demrks** [comment]
Thanks, I overlooked the part with the ".gu-transit" class name.

By default the item that is being dragged gets removed. Is there a way to assign a class name to that item rather than removing it? That way I could style the item that is currently being dragged  (e.g. less opacity or something)... Is something like this also possible?

In case my intention isn't clear I attached another example (see "Item 2"):
![2](https://cloud.githubusercontent.com/assets/5760429/10203907/0f029d58-67b9-11e5-866a-34957b822c74.gif)

**Comment by bevacqua** [comment]
See the demo page

**Comment by demrks** [comment]
Actually I checked the demo page, but the only option that had a similar behaviour was `copy: true`. If you have a look at the second example gif, "Item 2" doesn't get copied. It just stays in place until you drop the "mirror" element to another position. 

I just double checked the demo page and I can't find an example that does that. What example/option were you referring to?

**Comment by ben-pr-p** [comment]
You can set `copy: true` and then remove the copy on drop

**Comment by demrks** [comment]
@ben-pr-p Thanks, that'll work
