### ISSUE TITLE
Option to drop an item on top of an existing one

### ISSUE THREAD

**Issue by derwaldgeist** [bevacqua/dragula#222]
I really like the simplicity of dragula, respects for this.

However, I have a use-case that would require an extension to the drop behaviour. I am trying to build something that resembles the app-launcher on iOS (and also some Android) devices.

That means: I want to drag an item and drop it *either* in-between two existing items *or* on-top of an existing item. 

If I drop it *between* items, it should be placed in this new position, just like the existing dragula behaviour. 

But if I place it *on top* of another item, I want to react on this by creating a folder item containing both items (which would be functionality I would implement in a custom JS function).

**Comment by bevacqua** [comment]
You could easily do this `.on('drop')` modifying the DOM.

**Comment by beatfreaker** [comment]
@bevacqua yea we can handle this by modifying the DOM in `.on('drop', function (el, target, source, sibling) {});` but how we will detect on which div the item has been dropped?

- using `sibling` ?
  but if we use `sibling` to detect on which div the item has been dropped then there are some cases         in which `sibling` will be passed as null even though mouse pointer is on div in that case there will be no way to detect on which div it has been dropped.

- what is suggest is we can pass `elementBehindCursor` in `.on('drop')` this will make it easy to detect on which div item has been droped. In this case if item is been dropped on specific div `elementBehindCursor` will be that div.

what do you think?

**Comment by bevacqua** [comment]
Suppose each `----` is an item and the box is a container. When you drop an item in it, you get `target` as the container, `sibling` as the previous sibling or `null` if its the last item in the container. You could get the item itself by doing `$(sibling).prev().add($(container).children().last()).first()`.

```
 _____
|-----       |
|-----       |
|-----       |
|_____|
```

**Comment by derwaldgeist** [comment]
I tried this approach, but it did not work reliable enough for me. I ended up with putting each drop target in its own container. This worked, but I'm not sure how good the performance will be if there are tons of potential drop targets. It would be much more helpful in this case if the drop targets would react directly on hover.

**Comment by beatfreaker** [comment]
@bevacqua yeah that good i guess we can achieve what @derwaldgeist want from the suggestion you gave but consider following scenario : 

```
 _____
|-----|
|---- |<--
|-----|<~~
|_____|
```

suppose i want to add an item to the div indicated with `<--` now suppose i start to drag div from source move it over div indicated with `<~~` and then over div above it so it goes from bottom to top.

Now my cursor is over `<--` and the shadow element created will be between `<~~` and `<--`
so now when i drop the element supposedly over `<--` but in `.on(drop)` i will get `sibling = <~~` and not `sibling = <--` 

understood?

any idea how we can handle this?

**Comment by beatfreaker** [comment]
@bevacqua any updates?

**Comment by ben-pr-p** [comment]
I was able to accomplish this by dropping it inside of the item and setting the item's css to hide things of that class inside of it.

Then, I accessed the container in the drop event to have something happen on drop.

The only difference is you need to make the container the element you want to drop it on, instead of the element containing the thing you want to drop it on.

**Comment by bevacqua** [comment]
Use Slack for support requests. See #248.

**Comment by goper-leo** [comment]
How to solve this please.. http://stackoverflow.com/questions/34584931/how-to-change-elements-being-copied-on-dragging-using-dragula-js-plugin

**Comment by maverick09** [comment]
@derwaldgeist : Thanks for the advice. Can you please share code snippet or some details, how you implemented this ? I also have to achieve similar goal, create a folder when dropped on item.

Help is appreciated. 

Thanks

**Comment by maverick09** [comment]
@derwaldgeist : can you please explain more about your solution? I really need to resolve this use case. highly appreciate your help.

**Comment by derwaldgeist** [comment]
Sorry, I don't remember. It's such a long time ago, and I have not used Dragula since then.
