### ISSUE TITLE
Using isContainer is appending as many clones as containers on page

### ISSUE THREAD

**Issue by BenjaminNeilDavis** [bevacqua/dragula#224]
```
isContainer: function (el) {
     return el.classList.contains('app-groups');
}
```

When doing this every time I drag an element it is copying several instances of the element. One for every container with the class app-groups. What can I do to prevent this?

I have also tried:
```
var drake = dragula([document.querySelector('.app-groups')],{
	copy: true
});
```

Thank you very much!

**Comment by bevacqua** [comment]
I need a demo.

**Comment by BenjaminNeilDavis** [comment]
Not sure how to get react-dragula to be available in codepen but here is an example.

http://codepen.io/BenjaminNeilDavis/pen/EVmVEM

**Comment by BenjaminNeilDavis** [comment]
My fault. I was doing something incorrectly. Sorry for the trouble.

**Comment by bevacqua** [comment]
You're welcome : )
