### ISSUE TITLE
Making it work with simple HTML tables for column resize (or React tables)

### ISSUE THREAD

**Issue by mikeerickson** [bevacqua/dragula#226]
This is not a bug by an stretch!

Reaching out to all the Dragula users out there.  If you have ANY sample code which works with vanilla HTML tables, OR with React, and are willing to share, I would be grateful

Been trying to get our simple react tables to support column resizing and am not having much luck.  Ready to punch my monitor (anger management issues)   :-)

If you can help, I would be very very grateful!!!!

**Comment by bevacqua** [comment]
Use Slack for support requests. See #248.
