### ISSUE TITLE
Arbitrary Positioning

### ISSUE THREAD

**Issue by jetpacmonkey** [bevacqua/dragula#227]
Is there any way to use this library to just make it possible for an element to be positioned on the page, without worrying about all of the re-ordering functionality? I'm essentially looking for an equivalent to jQuery UI's `draggable`, without needing to actually use jQuery UI.

**Comment by bevacqua** [comment]
Not really. Suggestions are welcome though.

**Comment by bevacqua** [comment]
Use Slack for support requests. See #248.
