### ISSUE TITLE
Two separate containers problem

### ISSUE THREAD

**Issue by Myrdivar** [bevacqua/dragula#231]
Hi,

If I build two separate containers this way

				  <div class='parent'>
				    <div class='wrapper'>
				      <div id='first' class='container'>
				        <div>You can move these elements between these two containers</div>
				      </div>
				    </div>
				  </div>

				  <div class='parent'>
				    <div class='wrapper'>
				      <div id='second' class='container'>
				      </div>
				    </div>
				  </div>

I'm not able to drop the element from the first list to the second because it's empty. If I add a div in the second one it works fine but how can I 'activate' the second list to accept elements when it's empty?

Thanks!

**Comment by bevacqua** [comment]
Set a CSS `min-height` on the second.
