### ISSUE TITLE
Select input not opening in dragable item

### ISSUE THREAD

**Issue by nickdecorte** [bevacqua/dragula#232]
There seems to be a problem when using a select input field in a dragable container of dragula.

Check the following fiddle https://jsfiddle.net/97o72b1t/

**Comment by beatfreaker** [comment]
can submit a PR for this.

**Comment by nickdecorte** [comment]
Check PR #234 fixed focus for select inputs

**Comment by bevacqua** [comment]
Published as `3.5.2`
