### ISSUE TITLE
Dynamic "accepts" option

### ISSUE THREAD

**Issue by Myrdivar** [bevacqua/dragula#233]
Hi,

Is there a way to dynamically set the option 'accepts'? The best it would be to set it in drake when I push a new container.

Thanks again!

**Comment by ben-pr-p** [comment]
Two options for accomplishing this:

One, you can do: 
```
accepts: (el, target, source, sibling) => {
     return myAcceptsFunction(el, target, source, sibling);
}
```
and then redefine `myAcceptsFunction` as needed, or you can just have `if`'s:

```
accepts: (el, target, source, sibling) => {
     if scenario 1 {
          // do one accept function
     } else if scenario 2 {
          // do something else
     }
}
```
