### ISSUE TITLE
IOS and touch

### ISSUE THREAD

**Issue by jkainth** [bevacqua/dragula#236]
I am just getting started and loving Dragula, and how easy it is to use.

I searched through the issues but i couldn't figure out if Touch is supported? I am trying on IOS 9 (also tried on 8) but i can't seem to see if Dragula supports touch devices and DnD with touch.

None of the examples on the Demo page work on IOS (9 and 8)

**Comment by bevacqua** [comment]
Resolved in `3.5.3`
