### ISSUE TITLE
Suggestion: delegation for draggables, and targets.

### ISSUE THREAD

**Issue by hollowdoor** [bevacqua/dragula#241]
There is a problem for when there could be potentially 100s of elements, but those elements are not direct children of a container.

These are potentially related issues:

[Making it work with simple HTML tables for column resize](https://github.com/bevacqua/dragula/issues/226)
[Option to drop an item on top of an existing one](https://github.com/bevacqua/dragula/issues/222)

To do this maybe a field in the options would work specifying classes to target.

```javascript
var drake = dragula(document.getElementById(id), {
    drag: ['dragOne', 'dragTwo'],
    targets: ['dragOne', 'otherTarget']
});
```

Then if any elements are added anywhere in the page it just has to have the classes set in the drag, or target fields. This would pose another problem though. What about the easy functionality that dragula uses already by just passing a container:

```javascript
var drake = dragula(document.getElementById(id), {
    drag: ['dragOne', 'dragTwo'],
    targets: ['dragOne', 'otherTarget'],
    direct: false /* direct children are not moved */
});
```

The `direct` option would be default true, and disable direct children dragging. If `direct` is true, and  there is a sub-child that is set to drag then it will drag and it's parent will not unless the parent is large enough, and  its *box* is hit by the cursor first.

Alternatively another method is a delegate `on('drag', '.delegateSelector')`.

This functionality might add unwanted complexity to the already very nice dragula, but it's just a suggestion. I'm working on a project that will potentially have 1000s of elements that may, or may not be moveable based on some condition. I suppose the other option is just setting draggable false, but that wouldn't be as flexible.

I understand that some delegation can be done by checking the classList. I just wanted to see if there was some other way to have the delegation effect. There might be a better way that I haven't thought of too.

**Comment by bevacqua** [comment]
I don't understand the question. Do you want to be able to dynamically select containers? `isContainer` does that. Do you want to have append behavior instead of positioning stuff near the mouse cursor?

**Comment by hollowdoor** [comment]
I want drag, and drop events to go to specified children instead of just the immediate children. Kind of like delegate events that are used in a lot of DOM libs.

**Comment by bevacqua** [comment]
You can use the `handle` in `moves`, but if you're worried about performance there is just a single listener, not one per item

**Comment by hollowdoor** [comment]
A handle probably wouldn't work. Isn't that for an element that drags it's parent? I'm thinking of a regular drag on an element, but an element that's possibly not directly a descendent of the container. Same thing for targets.

How I've been doing it is setting the drag/drop listeners with addEventListener on one element full of children with `draggable` set. Then I use classList.contains on event.target to see if it has a class from a set of classes I've set to allow to drag. Some are nested, but some parents move with their children, and their children also move independently of those parents depending on if they are the target with an allowed class.

This is really hard for me to explain. Sorry. :)

**Comment by hollowdoor** [comment]
I'd like to say not having this functionality is not a deal breaker. What dragula does will fit most situations. I might just have to do a little work outside of dragula for special situations.

**Comment by hollowdoor** [comment]
I think the functionality of dragula is pretty well defined. It might not be a good idea to add too much to a simple interface that already does a lot. This was a hasty idea.

**Comment by voidale** [comment]
@hollowdoor dragula is not very flexible to modify I wish it could provide more control on where the shadow is being shown or to drag and drop on specific elements and to switch them if needed, the plugin is really limited. Just single sortable functionality.

**Comment by hollowdoor** [comment]
Well it does allow arbitrary targets with the isContainer method, but I agree it is not flexible. I'm thinking this is a good thing.

I'm not sure if control of the shadow is really all that good of an idea. Where would you put it?

Switching does seem like a valid problem. Though I don't know where that would be used. What kind of situation is that a problem to be solved?

Are either of your problems related to delegation as in this particular issue?
