### ISSUE TITLE
Selecting the most specific (deep) first?

### ISSUE THREAD

**Issue by AlbinoGeek** [bevacqua/dragula#243]
Currently, if I nest draggable items; the outer most item matching the querySelector is dragged (the entire tree of items, along the top level; thus you can only move the parent items (categories); which is not a bad thing, but not what I want at this particular time.)

Is there a way to do the exact opposite of this,. only allow children to be dragged and not the parents?

## Example Markup

Here's some example and markup:

From: http://semantic-ui.com/elements/list.html "nested list example"

### Best viewed as Jade

```jade
.ui.list
  each items
    .item
      .content
        .header= name
        .list
          each children
          .item
            .content
              .header= name
```

Rendered Structure:

OUTER LIST:
```
div.ui.list
  div.item
    div.content
      div.header src
      div.list
        div.item (repeats nested)
```

### Or as rendered HTML:

```html
<div class="ui list">
  <div class="item">
    <div class="content">
      <div class="header">src</div>
      <div class="list">
        <div class="item">
          <div class="content">
            <div class="header">site</div>
          </div>
        </div>
        <div class="item">
          <div class="content">
            <div class="header">themes</div>
            <div class="list">
              <div class="item">
                <div class="content">
                  <div class="header">default</div>
                </div>
              </div>
              <div class="item">
                <div class="content">
                  <div class="header">my_theme</div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="content">
            <div class="header">theme.config</div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="item">
    <div class="content">
      <div class="header">dist</div>
      <div class="list">
        <div class="item">
          <div class="content">
            <div class="header">components</div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="item">
    <div class="content">
      <div class="header">semantic.json</div>
    </div>
  </div>
</div>
```

## Intended Actions

- Person can drag sub-items (files) between their parent (CONTAINING) list, and not into or out of a parent or child list.  (keep items at their same levels.)

Any idea how I might accomplish this?

**Comment by AlbinoGeek** [comment]
Thanks @bevacqua as I understand this is a usability question, and badly asked too!

**Comment by AlbinoGeek** [comment]
Simplified the example markup, and syntax highlighted.

**Comment by ben-pr-p** [comment]
Clarification – you only want to be able to drag the lowest child no matter what? 

Is there ever a situation in which you want to drag the parent?

**Comment by AlbinoGeek** [comment]
@ben-pr-p Well, it would be nice to drag each child amongst it's peers (regardless of depth, it would be restricted to that depth (i.e: same parent))  Otherwise, inner-most works.

I suppose I answered my own question with the "same parent" bit, not sure what part of dragula lets me set a "canDrag" , I see copy/move but no "you can only if same parent".

**Comment by bevacqua** [comment]
Use Slack for support requests. See #248.
