### ISSUE TITLE
Shadowing with different content than source?

### ISSUE THREAD

**Issue by berniecz** [bevacqua/dragula#244]
I'm using Dragula to drag article from list and drop it in completely different markup to the "target" container. I was able to do so via 
```javascript
            drake.on('drop',  function (el, target, source, sibling) {
                var draggedPost = getLoadedPostByID(el.dataset.artid, posts);
                var template = $('#tpl-landed').html();
                Mustache.parse(template);
                var rendered = Mustache.render(template, draggedPost );
                $(el).html(rendered);
                $(el).contents().unwrap();
             });
```

This works fine even for unwrapping the outermost element. What I'm unable to achieve is to see previewed article when dragging source over the target container. I thought to use very similar approach and modifying 'el', but it doesn't work for outermost wrapper, just what is inside the wrapper. Could you please provide any help on that and how to control how the shadow preview is being controlled? Thanks.

**Comment by bevacqua** [comment]
Use Slack for support requests. See #248.
