### ISSUE TITLE
removeOnSpill from Copy target container

### ISSUE THREAD

**Issue by Serexx** [bevacqua/dragula#246]
**Note: I was going to use Slack for this but the "invite" button on the Demo page was non-responsive in both Chrome and Firefox so hopefully I'm forgiven for this:**

Thanks very much for all the work on this library, perfectly suited and simple!

That said, I need a Copy configuration that allows the cloned elements to be removed from the destination container by dragging (spilled)

I tried the obvious (from the example page)
```javascript
dragula([$('left-copy-1tomany'), $('right-copy-1tomany')], {
    copy: function (el, source) {
        return source === $('left-copy-1tomany');
    },
    accepts: function (el, target) {
        return target !== $('left-copy-1tomany');
    }

});
dragula([$('right-copy-1tomany')], { removeOnSpill: true });
```

When that didn't work I tried the documentation which states that Remove events will not be triggered if Copy is specified. That sounds like it might be the issue but I am wondering then how one overcomes this?

Is there a workaround? I'd prefer not to have to start adding "wastebasket" Icons and "on-clicks" messing up what is otherwise a lovely intuitive interface...

TIA for any help (or a Slack invite :-)

**Comment by bevacqua** [comment]
See #248

**Comment by bevacqua** [comment]
Use Slack for support requests. See #248.
