### ISSUE TITLE
Allow drag operations to be cancelled with Escape

### ISSUE THREAD

**Issue by lukehutch** [bevacqua/dragula#249]
Most operating systems allow users to cancel an in-progress drag event using the Escape key. It would be nice if Dragula followed that convention, adding a key event handler at the beginning of a drag operation, and removing the handler at the end of the operation.

**Comment by bevacqua** [comment]
Sure. Use the API.

**Comment by lukehutch** [comment]
Of course I can write that code manually. I was suggesting it would be a good feature for Dragula to implement by default, so that users of the library don't have to re-invent that wheel every time.

**Comment by bevacqua** [comment]
I know. But no, thanks. Dragula is a very simple API that doesn't commandeer keyboards, you'll have to do add keyboard accessibility from the outside.
