### ISSUE TITLE
Exception thrown in IE when dragging over an svg

### ISSUE THREAD

**Issue by jimf** [bevacqua/dragula#251]
I'm debugging an exception that seems to be specific to IE (only tested in IE11). The exception, thrown [here](https://github.com/bevacqua/dragula/blob/6a78c286122ab5e1ddc0fbb057d5c59bbb2a3605/dragula.js#L398), is "Unable to get property 'insertBefore' of undefined or null reference". In looking into this, I've discovered that `parentElement` (called from [`findDropTarget`](https://github.com/bevacqua/dragula/blob/6a78c286122ab5e1ddc0fbb057d5c59bbb2a3605/dragula.js#L327-L331)) is `undefined` in IE11 when `target` is an svg.

I'd be happy to open a PR for this, but I'm unsure whether it's more correct to update [this line](https://github.com/bevacqua/dragula/blob/6a78c286122ab5e1ddc0fbb057d5c59bbb2a3605/dragula.js#L327-L331) to `return target || null`, or if it would be better to use `parentNode` over `parentElement` (which seems to return the desired element/node). I'm thinking the latter, but that begs the question: should all instances of `parentElement` be replaced with `parentNode`?

**Comment by bevacqua** [comment]
Nice catch.  
I hadn't thought of that.  
We should use `parentNode` in there for sure.  
I can't think of a reason not to switch to `parentNode` everywhere.

**Comment by jimf** [comment]
Okay, cool. I'll open a PR shortly.
