### ISSUE TITLE
Build not actually passing?

### ISSUE THREAD

**Issue by jimf** [bevacqua/dragula#254]
It looks like testron statically exits 0 regardless of the result of the test run, and as such, Travis is never failing due to failing tests (and there are currently 27 failures). This is probably worth a PR against testron itself, but it's remedied easily enough by piping to something like [tap-spec](https://www.npmjs.com/package/tap-spec) or similar.

**Comment by bevacqua** [comment]
Could you PR? Fixing the tests would be greatly appreciated too. Test coverage isn't the best atm either

**Comment by jimf** [comment]
Sure, I'll take a look. Any preference whether to separate the PRs or not? I'm leaning toward keeping them together, just to keep Travis happy, but either way.

> Test coverage isn't the best atm either

Any interest in a coverage task, optionally with coveralls.io integration?

**Comment by bevacqua** [comment]
Closing, would love all things test coverage. I haven't had a lot of free time.
