### ISSUE TITLE
Stop dragging, Start dragging for all element

### ISSUE THREAD

**Issue by calebelt** [bevacqua/dragula#255]
How do I stop or start dragging all elements?

**Comment by calebelt** [comment]
So far, I made a small crutch...

  var drake = emitter({
    containers: o.containers,
    start: manualStart,
    end: end,
    cancel: cancel,
    remove: remove,
    destroy: destroy,
    dragging: false,
    stopall: false
  });

function grab (e) {
if(drake.stopall){return;}
...

**Comment by bevacqua** [comment]
See #247
