### ISSUE TITLE
Sort items with the option: copy

### ISSUE THREAD

**Issue by calebelt** [bevacqua/dragula#257]
How to sort items with the option: copy?
ul id="clone-container"
li red (this is not sortable, only clone)/li
li green (this is not sortable, only clone)/li
li blue (this is not sortable, only clone)/li
/ul
copy to
ul id="colors-container"
li green /li
li red /li
li red /li
li green /li
/ul
This is sortable

**Comment by bevacqua** [comment]
See #248
