### ISSUE TITLE
Applying dragula to list in Meteor

### ISSUE THREAD

**Issue by mazing** [bevacqua/dragula#258]
In Meteor, I have a template

    <template name="tasks">
      <ul class="list-group">
        {{#each tasks}}
          {{> task}}
        {{/each}}
      </ul>
    </template>

in which I initialize dragula with

    Template.tasks.onRendered( function () {
      dragula( [ this.find( 'ul' ) ] );
    } );

It gets initialized but when I am dragging an element, I get the errors

    Uncaught TypeError: Cannot read property 'appendChild' of null  [dragula.js:463]
    Uncaught TypeError: Cannot read property 'className' of null  [dragula.js:28]

I am loading dragula.js with `meteor-bower`.

What is wrong?

**Comment by bevacqua** [comment]
See #248
