### ISSUE TITLE
Minimum distance before movement is considered dragging

### ISSUE THREAD

**Issue by perttumyry** [bevacqua/dragula#259]
Now mouse movement is considered dragging when mouse is moved even one pixel from the original location. I have a use case in which draggable elements also contain clickable buttons. When trying to click a button mouse easily moves couple pixels so it initiates drag even instead of click.

It would probably make sense to use handles so that dragging would not be done in same spot which can be also clicked. But having this issue made me wonder would it be possible to add conf option to have minimum mouse move distance before dragging is initialized?

In my use case having something like 10px threshold before movement would be considered as dragging would be a nice solution.

I really haven't investigated the project source code so no idea would this make any sense or how big deal it would be to implement something like this in Dragula.

**Comment by bevacqua** [comment]
Too little gain

**Comment by hagenschulze** [comment]
Hey,
I have same requirements in one project, in which I also need to attach a click handler on a bag-element.
So I would appreciate if we could make a feature request for that.

**Comment by EhsanKia** [comment]
This is very important. If the elements are also used as buttons, they are nearly unusable without this optimization. Easily 50% of the time when I go to click on an element, it doesn't work because a drag initiates.

**Comment by haschu** [comment]
I've now implemented this function by myself. 
It's may be not the best possible solution, cause I didn't had time to dive that deep into the code. It works without any problems in production tough.

If anyone is interested, I would share my workaround.

**Comment by perttumyry** [comment]
There's no harm in sharing so please do. It would be interesting to see your workaround.

**Comment by yoshokatana** [comment]
I'd also really like this. I tried my hand at implementing it, but couldn't figure out the best way to get it working.

**Comment by EhsanKia** [comment]
jquery UI draggable has this setting. You basically want to track the mouse delta from the moment they do a mousedown, and only start actually dragging once it's above the threshold.

**Comment by yoshokatana** [comment]
Yeah, that makes sense. I _think_ you'd do the check right here, right? https://github.com/bevacqua/dragula/blob/master/dragula.js#L148

**Comment by Varujik** [comment]
I had the same issue, and solved it like:
Just add one more option to constructor:
`if (!o.moveDistance) { o.moveDistance = 1; }`

Function startBecauseMouseMoved is being called on mousemove.
So just check distance between saved coords and current

`// Get difference of coords
    var moveX = e.pageX - _moveX;
    var moveY = e.pageY - _moveY;
	
	// If difference is less than "n" - don't move
    if (Math.abs(moveX) < o.moveDistance && Math.abs(moveY) < o.moveDistance) {
      return;
    }`
I'll attach edited dragula.js where you can see whole code

[dragula.zip](https://github.com/bevacqua/dragula/files/2973787/dragula.zip)

**Comment by iwiedenm** [comment]
@Varujik I know this is late but thank you for posting that, it works beautifully and, for how simple it is, should really be considered as a feature for Dragula.

**Comment by Varujik** [comment]
Hey @iwiedenm . Glad to hear :)
