### ISSUE TITLE
Cannot read property 'appendChild'

### ISSUE THREAD

**Issue by webchaz** [bevacqua/dragula#262]
I setup a very simple test with the following markup:

```
    <div id="container">
      <div>Drag Me</div>
      <div>Drag Me 2</div>
    </div>
```
and initialed it using `var drake = dragula([document.querySelector('#container')]);`

However, I'm getting the following error when I attempt to drag an item:   

```
Uncaught TypeError: Cannot read property 'appendChild'
of nullrenderMirrorImage @ dragula.js:426startBecauseMouseMoved @ dragula.js:150
```

Any idea what the issue could be?  Thanks

**Comment by jaw4ik** [comment]
I have the same problem.

**Comment by jaw4ik** [comment]
I already download previous version (v3.5.3) and this version works correct.
Only last v3.5.4 version has this bug.

**Comment by bevacqua** [comment]
Could you provide a longer stack trace?

**Comment by netil** [comment]
@jaw4ik is because dragula was included in the <head> tag, prior <body> was constructed.
To solve, just include dragula file inside the <body> tag.

**Comment by bjolseth** [comment]
you might want to state this clearly ath the start of the documentation page. had the same problem, took me some time to figure out, spending it debugging the source, actually. very rare these day that we don't include js files either in the header and use jquery document init, or the newer "require" pattern

**Comment by webchaz** [comment]
@netil Yep, that was it :)

**Comment by bevacqua** [comment]
Added a note to the readme.
