### ISSUE TITLE
Replace on drop

### ISSUE THREAD

**Issue by javatheist** [bevacqua/dragula#265]
Hi, first of all, very nice work!

we are using dragula as a plugin within a content editor (similar to webflow). your tool works sweet, but we would appreciate two more features.

1) there already is this "either click or drag" - feature, but in case of click, the contenteditable caret does not start to blink. as for now, i'm dependent on a switch "edit mode/drag mode" which i'd like to get rid of.

2) on drop: is there a way to "replace" the target in certain cases? say, i drop an img on an img ...

thx for going this through.

Regards,
Peter

**Comment by javatheist** [comment]
Moreover, one more thing :)

The triggering of a drop event does not mean that dropping was successful eventually. (ex.g. modifying the isContainer and accept routines such that you can drop an img on an img, it throws "Uncaught HierarchyRequestError: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.q @ dragula.min.js:1
media.js:506 Uncaught TypeError: Cannot read property 'target' of null" which is perfectly ok. Then the dragging continues which is not bad either.

What I'm looking for is an event, which triggers after everything worked out and finished such as an "afterSuccessfulDrop" event or something similar :) Reason is that our Freazy Publisher (name of the contenteditable tool) needs to update an "undo" plugin in case something changed. If I trigger our custom "something changed"-event at drop, I have to be sure that dropping was successful (which i cannot in this specific case)

Thank you for putting some thoughts to this.

**Comment by bevacqua** [comment]
#248

**Comment by goper-leo** [comment]
How to solve this?

**Comment by queejie** [comment]
Can someone explain why this was closed? Is there a way to support this?  There is nothing in the referenced "Support and Slack Invites #248" that seemed to apply.
