### ISSUE TITLE
Is nesting of containers possible?

### ISSUE THREAD

**Issue by andreimoment** [bevacqua/dragula#266]
I'm wondering if this allows nesting of elements. 

Example: a set of todo lists, each containing todo items. Todo lists may be rearranged, todo items may be rearrange within he same list and also moved between lists. 

Thus, the todo lists are sortable but also containers for the todo items. 

Would such functionality be a possibility?

**Comment by bevacqua** [comment]
#248

**Comment by linearza** [comment]
https://github.com/bevacqua/dragula/pull/358
