### ISSUE TITLE
Can't repeatedly drop item

### ISSUE THREAD

**Issue by jaw4ik** [bevacqua/dragula#268]
When I move copied item to target first time everything is working correctly and shadow appeared.
But when I move out item from target container and try to move item to the same place I can't do this.
And only when I move item to another position I can move it to first position.

http://www.screencast.com/t/pH3CkahD

**Comment by jaw4ik** [comment]
I believe that this pull request fix this problem:
https://github.com/bevacqua/dragula/pull/269

**Comment by bevacqua** [comment]
Sorry this merge took so long! `3.6.5`
