### ISSUE TITLE
Can't use font-awesome i tag as handle

### ISSUE THREAD

**Issue by ko-porter** [bevacqua/dragula#27]
I've just discovered this library today, and i really like it.
A couple of issues i'm encountering though, first with the use of a font-awesome styled <i>, either within a span or not, this won't take it as the handle.
it will work ok with an empty span for instance, but as soon as i set the <i> tag inside the span, it stops working.
same thing with the <i> tag also holding the handle class

**Comment by bevacqua** [comment]
I'll need a demo with the bug please, could you put one up on codepen?

**Comment by ko-porter** [comment]
http://codepen.io/anon/pen/RPbXba

as requested, i've set up a codepen.
You will see i added 3 elements, one with a span with the font-awesome i tag inside, which works, one with only the i with both classes handle and font-awesome, which does not work, and one with only the span, that does work as well.
note sure why with no span, it does not work

**Comment by ko-porter** [comment]
One question relating to the codepen example: why does the element size changes will dragging, although it has fixed width from css?

**Comment by ko-porter** [comment]
you can ignore this post, the issue with the font-awesome was coming from the moves function, where the check was done on exact same class rather than has the handle class
the other question was due to the css being assigned via the container and not directly to the element, so when moving its style would change as well.
