### ISSUE TITLE
Shadow event working inconsistent

### ISSUE THREAD

**Issue by jaw4ik** [bevacqua/dragula#270]
I know that in the docs tell's about this:
### 'shadow' event
> **el**, the visual aid shadow, was moved into **container**. May trigger many times as the position of **el** changes, even within the same **container**; **el** originally came from **source**

but I think it inconsistent when in all places **shadow** event calls only once, but in most bottom place **shadow** calls more that one time.

I want to add animation to shadow element appearence, but I can't because most bottom item will be animated many times.

Screencast: http://www.screencast.com/t/CvBIz01T

**Comment by jaw4ik** [comment]
Fix: https://github.com/bevacqua/dragula/pull/271

**Comment by bevacqua** [comment]
Sorry this merge took so long! `3.6.5`
