### ISSUE TITLE
feat:  async 'accepts' support

### ISSUE THREAD

**Issue by amitport** [bevacqua/dragula#274]
would it be possible to allow `accepts` method to return a `Promise` and then the given element would "freeze" drop until the promise resolved with `true` or revert if the promise rejected or resolved with non-true

**Comment by bevacqua** [comment]
No, that'd be a bad idea.

**Comment by amitport** [comment]
why?

use-cases: 
(1) confirmation dialog before drop, e.g., when dropping into 'trash bin'.
(2) server side verification of the drop legality, e.g., "item is not in stock", "shared folder is full"

**Comment by bevacqua** [comment]
1. You can do this without async accepts
2. Precalculate, don't block user interaction on server-side logic

**Comment by amitport** [comment]
1. how (or what could be simpler than just returning a promise)?
2. IMHO, you can't always pre-calculate. For example, when there is a shared drop-bin that need to be synchronized between different clients (not all of them necessarily web-clients), having a freezing draggable (that could be overlayed with circular progress) is preferable to an element that jumps back into it's old position after five seconds.

In any case, this library is great and have a very nice API, thanks for publishing it, I understand if this doesn't fit in its design and I already found alternative solutions.
