### ISSUE TITLE
Ignore drag on element - .cancel(true/false) causes error

### ISSUE THREAD

**Issue by ConorHiggins** [bevacqua/dragula#275]
I'm currently working on a custom binding for dragula which can be used with knockout js. So far dragula looks great, but I am trying to allow for some very specific behaviour. I would like to be able to treat one container purely as a drop zone and not allow items to be dragged from inside it. 

Is there a simple way of doing this that I am missing in the docs?

The way I am doing it at the moment is as follows, on the drag event, I am checking if the container has a certain class, e.g. 'dont-allow-drag' or 'drop-only' and if so, I am calling drake.cancel(true). But this code is returning a console error: "Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null"

I get the same error when calling drake.end()

```
drake.on 'drag', (el) ->
    console.log "dragging it",el
    if el.classList.contains(className)
        console.log "should cancel it"
        drake.cancel(true)
    return
```

**Comment by ConorHiggins** [comment]
solved: 

```
invalid: (el, target) ->
    return el.classList.contains(className)
```

Would be really helpful to have an example with this behaviour in the demo

**Comment by bevacqua** [comment]
You could just do 

```js
moves: function (el, source) {
  return source !== foo
}
```

**Comment by mikesimmonds** [comment]
I came across this issue when I needed to allow the user to drag for a short time and then display an error saying 'You cannot drag this card'.
Wrapping the drake.cancel(true) in a setTimeout worked well in this case.

``` 
drake.on('drag', args => {
      const [bagName, el, target, source] = args;
      if (el.classList.contains(className)) {
        setTimeout(() => {
          drakeInstance.drake.cancel();
          this.displayNoDragMessage();
        }, 200)
      }
    }) 
```

**Comment by ZukenHammer** [comment]
I also came across this issue but I had no access to the init method. My solution was to set the style `dragElement.style.pointerEvents =  "none";` property on the elements I would not allow to drag and drop and as fallback call `drake.end();` on the drag event, accepting to live with the error if it occurs, which should not happen.
