### ISSUE TITLE
Javascript error when nested sortable

### ISSUE THREAD

**Issue by AngeIII** [bevacqua/dragula#278]
Currently it seems that with dragula hard to create nested sortable. I tried to create simplest example:
https://codepen.io/anon/pen/EPjjvr

Nothing more but when I drag item3 I get js error: 
```
 Uncaught HierarchyRequestError: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.
```

P.S;
Also no api methods available as I see for control draggable items, draggable places (where to drop) and other.

**Comment by bevacqua** [comment]
#248

**Comment by lluisnieto** [comment]
Same error here, can't find any info regarding this.
