### ISSUE TITLE
removeOnSpill should not remove element as long as moved with the various containers added

### ISSUE THREAD

**Issue by ko-porter** [bevacqua/dragula#28]
let's say i initiate dragula with 2 containers such as 
dragula([left, right], { removeOnSpill: true })
if i move an element from left to right, it would disappear.

I feel like it should be allowed to be moved as long as the element is dropped on one of the dragula containers.
How to achieve such behavior?

**Comment by bevacqua** [comment]
I just tested this and it works as expected. Did you make sure to set a minimum width/height for the containers so that they're not impossible to mouse over?

**Comment by ko-porter** [comment]
seems that my use-case was actually the culprit for it to not work as expected:
i had declared 2 dragula sets, based on 3 containers, since i want to be able to use the first one as source, copying to the other two but not allowing drop, with the other two allowing exchanging elements.
commenting one out did show correct behavior
