### ISSUE TITLE
Cannot be included in head

### ISSUE THREAD

**Issue by dennisschaaf** [bevacqua/dragula#284]
In the draglar.js file body variable is cached in the beginning of the file. This breaks if the file is included in the head, because then this code is executed before the body is initialized. 

    var doc = document;
    var documentElement = doc.documentElement;
    var body = doc.body;

You could still keep the body variable in the file root, but only initialize it in dragular() ...

**Comment by bevacqua** [comment]
Don't include it in the head.

**Comment by ajb** [comment]
Thanks for the response. One last point of clarification: I'm trying to square this with https://github.com/bevacqua/dragula/commit/3090f69cf8d6866ca38270fe1e7a80432d5890b1. Was this supported in the past, and now no longer supported?

**Comment by bevacqua** [comment]
Correct. I guess I could support the use case, but I'd rather not encourage people to add scripts to the `<head>`.

**Comment by ajb** [comment]
Gotcha, thanks for clarifying! We're looking forward to giving dragula a try.
