### ISSUE TITLE
drag silhouette (mirror) is re-sized from original during dragging

### ISSUE THREAD

**Issue by QuakePhil** [bevacqua/dragula#286]
commenting out two lines in dist/dragula.js solves the issue for me, but this "fix" looks very ugly and unnecessary, perhaps I'm missing something obvious here?

Here are the lines I commented out in renderMirrorImage()

   459      //_mirror.style.width = getRectWidth(rect) + 'px';
   460      //_mirror.style.height = getRectHeight(rect) + 'px';

**Comment by bevacqua** [comment]
You're probably relying on classes on parents of the element being dragged. See #248
