### ISSUE TITLE
Please provide examples of the use of drake events

### ISSUE THREAD

**Issue by ko-porter** [bevacqua/dragula#29]
Could you add examples on how to use the drake events, i'm thinking for instance at running a function at every time an element is dropped, but couldn't figure out how to do it properly.
This would really help.
Thx in advance

**Comment by bevacqua** [comment]
They're right on the demo page

```js
var drake = dragula(el);

drake.on('drop', function () {
  console.log('foo');
});
```

**Comment by Gmattgreenfield** [comment]
I was looking for this too, maybe its been removed from this demo page? http://bevacqua.github.io/dragula/

Thanks for the help and the great plugin!
