### ISSUE TITLE
demo confuses me

### ISSUE THREAD

**Issue by niki571** [bevacqua/dragula#290]
I am a little confused when I look at the index.html and example.min.js.
` <div id='left-defaults' class='container'>` It implies that "id" is left-defaults.
`dragula([$('left-defaults'), $('right-defaults')]);` But why there isn't a "#" before "left-defaults"? Isn't it a jquery selector?

**Comment by jameswyse** [comment]
There's no jQuery, it just happens that there is a function named $. If you look at the bottom of example.js you'll see it declared:

function $ (id) {
  return document.getElementById(id);
}

**Comment by niki571** [comment]
Thanks. It helps a lot.@jamesxyse

**Comment by elgubenis** [comment]
💃
