### ISSUE TITLE
Unable to get the target when I try to use on ajax loaded content.

### ISSUE THREAD

**Issue by rbrahul** [bevacqua/dragula#293]
Actually Dragula works fine, but when I load html content which has a class .layout-placeholder-area
after ajax success I have tried to :

   imgDrugger= dragula([document.querySelector('#img-gallery-img-list'),document.querySelector('.layout-placeholder-area')],{
                    copy:true
                });

when I use drop event  and try to receive "target" it fails 

  imgDrugger.on('drop', function (el, target, source, sibling) {
console.log($(target)); //it show sundefined

}

I would be grateful to you if you please suggest me

**Comment by bevacqua** [comment]
#248
