### ISSUE TITLE
sibling not provided for second-to-last in list drop handler

### ISSUE THREAD

**Issue by michaelmalonenz** [bevacqua/dragula#296]
Only when dragging directly down from some higher element to the second-to-last in the group, even though the element would be placed in the correct position, the sibling argument to the `drop` handler is `undefined`, when it should reference the last element.   

If the element being dragged is dragged below the last element and then back up to the second-to-last position, then the sibling is correctly given.   

I'm working slightly against the system, as I'm cancelling the drag event and then re-arranging my elements semi-manually (I am using the Aurelia framework, so it's actually easier for me to do it this way than to figure out the order at the point of saving).  But this means that for that one position, my ability to order elements in place is somewhat inhibited.

**Comment by bevacqua** [comment]
See #248

**Comment by zvermafia** [comment]
@michaelmalonenz did you solve this problem?
If yes then how to?

**Comment by michaelmalonenz** [comment]
It turned out to be a bit more complex than I thought.  Aurelia inserts some comment elements `<!--<view>-->` and `<!--</view>-->` before and after each custom element respectively.  The dragula library doesn't handle that, as it ignores comment elements as the siblings.  To solve it, I forked the library and turned it into an Aurelia plugin [here](https://github.com/michaelmalonenz/aurelia-dragula) Though now that I understand the problem more deeply, I should really put up a pull request here again (my earlier one was an incomplete solution).
