### ISSUE TITLE
drag and drop nested elements with dragula

### ISSUE THREAD

**Issue by ConorHiggins** [bevacqua/dragula#299]
Hi, I have an odd situation where I need to be able to drag and drop elements between containers, reorder them inside the same container and being able to drag nested elements also. I'm hoping to use dragula to achieve this - I have been using it in a few other places and have found it great, but this has been strictly using flat lists.

My markup follows a similar structure to the following:

```
<div class="container">
	<div class="item">
		<span class="handle"></span>
		Parent
	</div>

	<div class="item">
		<span class="handle"></span>
		Parent
		<div class="children">
			<div class="item">
				<span class="handle"></span>
				Child A
			</div>
			<div class="item">
				<span class="handle"></span>
				Child B
				<div class="children">
					<div class="item">
						<span class="handle"></span>
						Grand Child A
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="item">
		<span class="handle"></span>
		Parent
	</div>

	<div class="item">
		<span class="handle"></span>
		Parent
	</div>
</div>

<div class="container">
	<div class="item">
		<span class="handle"></span>
		Parent
	</div>
</div>

<div class="container">
	<div class="item">
		<span class="handle"></span>
		Parent
	</div>
</div>

<div class="container"></div>
```

Here I have containers and then a series of nested children. I would like to be able to drag children from any level into either their own parent nodes, or into sibling containers as well as being able to sort items. The other issue here is that I am using a drag handle because I have lots of interactive components in each item row, so dragging on the entire row doesn't work very well for me.

Is there a way to achieve this? From what I have seen so far, by dragging on the handle of a child, I am then dragging the entire parent with it too

**Comment by bevacqua** [comment]
Ask on Slack. The repo is not for support requests

**Comment by chrisjlee** [comment]
Is there a place where we can post common questions? I bet you get this question a lot. Like a wiki?

**Comment by catmeme** [comment]
Seconding @chrisjlee sentiment

**Comment by linearza** [comment]
https://github.com/bevacqua/dragula/pull/358
