### ISSUE TITLE
Add a CDN?

### ISSUE THREAD

**Issue by franciscop** [bevacqua/dragula#304]
I've written several CSS/JS libraries before and hosted them in http://jsdelivr.com/ , which is great and free. Would it be possible to do so with Dragula? I'd love to try quick things in jsfiddle this way (:

**Comment by bevacqua** [comment]
I'll add a link to the readme, here: `https://cdnjs.cloudflare.com/ajax/libs/dragula/3.6.3/dragula.min.js`
