### ISSUE TITLE
drake is not an event emitter

### ISSUE THREAD

**Issue by franciscop** [bevacqua/dragula#307]
In the documentation it's stated that `The drake is an event emitter`, however in [my testing](https://jsfiddle.net/franciscop/op0nh983/) this doesn't seem so:

```js
var drake = dragula([document.querySelector('#left-defaults'), document.querySelector('#right-defaults')]);

drake.addEventListener('drag', function(){
	alert("Works!");   // Doesn't actually work
});
```

So I suggest:

- [preferred] Making it an event emitter so the events are actually triggered in javascript's way. This would allow [more flexibility for including it in other libraries](https://jsfiddle.net/franciscop/n7o1h4Lk/). However I understand this is some more work to do, so also:
- Change the documentation to reflect that it's not really an event emitter, but that there's a convenient method that looks like it. Maybe something like `The drake has an internal method for handling events that you can use for convenience`.

**Comment by bevacqua** [comment]
No, thanks

**Comment by franciscop** [comment]
What does that mean? It is not an event emitter...

**Comment by bevacqua** [comment]
It emits events through `.on`, `.once`, and `.off`.

**Comment by franciscop** [comment]
Oh I see, I keep searching and I had the definition of event emitter all wrong, sorry. I also found a quick fix to my specific problem, just adding an alias:

```js
u.prototype.dragula = function(opts){
  var drake = dragula(this.nodes, opts);
  drake.addEventListener = drake.on;
  return u([drake]);
};

// awesome
u('#left-defaults, #right-defaults').dragula().on('drag', function(){ alert("Works!") });
```
