### ISSUE TITLE
Dragging out text from an input causes the dragging of the input itself

### ISSUE THREAD

**Issue by beppe9000** [bevacqua/dragula#309]
![Example of this issue](http://i.imgur.com/AP3yoUN.gif)

As you can see in the image above. 
I don't know if javascript has access to the text drag & drop events for inputs...

Also forgive me if somebody already reported this.

**Comment by bevacqua** [comment]
This is intentional. You can select text inside the input but unless you make the input return false in `moves` or `invalid`, it is still draggable.

**Comment by beppe9000** [comment]
Anyways the position is offset by the previous drag distance, i feel like it is wrong
