### ISSUE TITLE
Quick question: does it work nested?

### ISSUE THREAD

**Issue by luckylooke** [bevacqua/dragula#31]

**Comment by bevacqua** [comment]
No

**Comment by Tomesch** [comment]
I was looking for the same thing few days ago and came up with the following solution: http://codepen.io/tomesch/full/XbbpVR/.

Basically you can use the handle element in the moves method to prevent the parent block from moving when dragging a child.

**Comment by luckylooke** [comment]
Thank you @Tomesch, very interesting solution, I will play with it. :)

**Comment by sherbrow** [comment]
Just an update to the pen submitted above to work with newer version : (no need to reopen)
http://codepen.io/sherbrow/full/rVZoRp

The trick is in the move option :
```
.container       // top container
  .bloc          // first level draggable & second level container
    .bloc--inner // second level draggable


 moves: function(el, container, target) {
      return !target.classList.contains('bloc--inner');
}
```

**Comment by onlywei** [comment]
Can you do this? http://dbushell.github.io/Nestable/

**Comment by shaneporter** [comment]
Thanks [@Tomesch](https://github.com/Tomesch), that helped me too. However, I've struggled to extend it to work with three levels of nesting. I'm probably missing something fairly obvious.

**Comment by sherbrow** [comment]
@onlywei @shaneporter I managed some kind of nesting, although I don't have a reusable version yet
Have a look there (and play with blocks only) : http://www.sherbrow.fr/labs/flow1.html

**Comment by onlywei** [comment]
@sherbrow That's pretty cool. Would it be hard to stick a block in between top-level items without causing nesting to happen?

**Comment by sherbrow** [comment]
@onlywei It might be difficult only because of the demo layout
If you put some margin between containers, or make the _being-dragged_ element very thin in height (the higher the difference in height between the container and dragged element, the easier it gets)

To explain the little trick I used : each time an element is picked up (drag-start) the containers of the drake element are updated to every container except the children of the dragged elements.
On drag end, containers are reset to default values

**Comment by shaneporter** [comment]
@sherbrow merci beaucoup! It's very much appreciated. :+1:

**Comment by molerat619** [comment]
@sherbrow I understand how you do it. Can you share your code?

**Comment by bevacqua** [comment]
@molerat619 You may get more help here https://dragula-slackin.herokuapp.com/

**Comment by indigoshade** [comment]
http://codepen.io/trzmaxim/pen/GppXGE

This is the ticket, however I'm not sure how to make it work using the angular 1.x directive

**Comment by danielverejan** [comment]
The codepen demo above gives DOMException error when dragula tries to drop the 'shadow' element into itself, an easy solution for this is setting display: none; on the container of the element that is dragged.

**Comment by MartinJHammer** [comment]
@sherbrow Many thanks for your nice codepen. It helped me do the same for my own little app with columns and todos in ng2.

**Comment by mcelligottnick** [comment]
@indigoshade here is my code to get it working with angular1.x;

Inside controller (using ctrl as syntax with `vm`);

```
            dragulaService.options($scope, 'parent-bag', {
                removeOnSpill: false,
                moves: function (el, container, target) {
                    if (target.classList) {
                        return target.classList.contains('parent-draggable');
                    }
                    return false;
                }
            });
```

View;

```
                        <ul dragula='"parent-bag"' dragula-model="vm.allCats" dragula-scope="$scope">
                            <li ng-repeat="cat in vm.allCats">
                                <div class="parent-draggable">
                                    {{cat.name}}
                                </div>
                                <ul style="margin-left: 20px;" dragula='"child-bag"' dragula-model="cat.supportingDocumentTypes" dragula-scope="$parent">
                                    <li ng-repeat="type in cat.supportingDocumentTypes track by type.id" class="childDraggable">
                                        {{type.shortName}}
                                    </li>
                                </ul>
                            </li>
                        </ul>
```

You can also add inputs via `ng-model` to bind to the props and it all updates correctly.

**Comment by vovayatsyuk** [comment]
@indigoshade, @danielverejan I've added the following style to prevent DOMException when dragging expanded item to the bottom over its children:

```css
.gu-transit {
    pointer-events: none;
}
```

**Comment by Ajita999** [comment]
@tomesch 404 error can't see your link. Stuck with the same issue, using angular 5 and nesting in a mat-accordion.

**Comment by jeremyd23** [comment]
So I saw the example from @sherbrow and tried to implement it myself:
`<div id="container">
    <div class="bloc block0">
        <input type="hidden" id="section0" name="section0" value="First Section Updated">Section 1
        <div class="block--inner">
            <input type="hidden" id="task0" name="task0" value="New Task for section two">Task 1
        </div>
    </div>
    <div class="bloc block1">
        <input type="hidden" id="section1" name="section1" value="Section two">Section 2
        <div class="block--inner">
            <input type="hidden" id="task0" name="task0" value="First Task for Section one Updated">Task 1
        </div>
        <div class="block--inner">
            <input type="hidden" id="task1" name="task1" value="Second Task">Task 2
        </div>
    </div>
</div>

<script>
    (function() {
        dragula([document.querySelector('.container')],{
            moves: function(el, container, handle){
                return !handle.classList.contains('block-inner');
            }
        });

        dragula([].slice.apply(document.querySelectorAll('.bloc')),{
            direction: 'vertical'
        });
    })();
</script>`

I have only been able to get my sections to drag/drop or my tasks, but not both.

**Comment by jeremyd23** [comment]
`<div id="container">
    <div class="bloc block0">
        <input type="hidden" id="section0" name="section0" value="First Section Updated">Section 1
        <div class="block--inner">
            <input type="hidden" id="task0" name="task0" value="New Task for section two">Task 1
        </div>
    </div>
    <div class="bloc block1">
        <input type="hidden" id="section1" name="section1" value="Section two">Section 2
        <div class="block--inner">
            <input type="hidden" id="task0" name="task0" value="First Task for Section one Updated">Task 1
        </div>
        <div class="block--inner">
            <input type="hidden" id="task1" name="task1" value="Second Task">Task 2
        </div>
    </div>
</div>

<script>
    (function() {
        dragula([document.querySelector('.container')],{
            moves: function(el, container, handle){
                return !handle.classList.contains('block-inner');
            }
        });

        dragula([].slice.apply(document.querySelectorAll('.bloc')),{
            direction: 'vertical'
        });
    })();
</script>`

**Comment by jeremyd23** [comment]
> <div id="container">
    <div class="bloc block0">
        <input type="hidden" id="section0" name="section0" value="First Section Updated">Section 1
        <div class="block--inner">
            <input type="hidden" id="task0" name="task0" value="New Task for section two">Task 1
        </div>
    </div>
    <div class="bloc block1">
        <input type="hidden" id="section1" name="section1" value="Section two">Section 2
        <div class="block--inner">
            <input type="hidden" id="task0" name="task0" value="First Task for Section one Updated">Task 1
        </div>
        <div class="block--inner">
            <input type="hidden" id="task1" name="task1" value="Second Task">Task 2
        </div>
    </div>
</div>

<script>
    (function() {
        dragula([document.querySelector('.container')],{
            moves: function(el, container, handle){
                return !handle.classList.contains('block-inner');
            }
        });

        dragula([].slice.apply(document.querySelectorAll('.bloc')),{
            direction: 'vertical'
        });
    })();
</script>>

**Comment by sherbrow** [comment]
@jeremyd23 
You forgot the double dash in `!handle.classList.contains('block--inner');`
https://codepen.io/anon/pen/WzBmZq

**Comment by stu-fu** [comment]
I thought I'd add onto this with a similar but different approach to nesting I needed to take

- Nested Items
- Uses a handle
- Items can only be dragged within their parent.

I was able to accomplish it like this: https://codepen.io/stufu/pen/LXNdBL

On top of this thread I was able to figure it out with these resources:

https://stackoverflow.com/questions/44935014/using-a-handle-with-nested-dragula-and-slice
https://codepen.io/anon/pen/RgBNje
https://stackoverflow.com/questions/47792337/dragula-how-to-disable-dragging-in-its-parent-container

Hope it helps someone!

**Comment by sks40gb** [comment]
@sherbrow - I am trying to achieve the similar functionality in Angular 6. Could you please guide how can I achieve the same.

**Comment by smartm0use** [comment]
> I thought I'd add onto this with a similar but different approach to nesting I needed to take
> 
> * Nested Items
> * Uses a handle
> * Items can only be dragged within their parent.
> 
> I was able to accomplish it like this: https://codepen.io/stufu/pen/LXNdBL
> 
> In addition to this thread, I was able to figure it out with these resources:
> 
> https://stackoverflow.com/questions/44935014/using-a-handle-with-nested-dragula-and-slice
> https://codepen.io/anon/pen/RgBNje
> https://stackoverflow.com/questions/47792337/dragula-how-to-disable-dragging-in-its-parent-container
> 
> Hope it helps someone!

Hello, here is an updated version of @stu-fu code:

```
this.dragulaService.createGroup("VAMPIRES", {
    moves: function (el, container, handle) {
        return handle.classList.contains('handle');
    },
    accepts: (el, target, source, sibling) => {
        return !(!target || !source || (target != source));
    }
});
```
