### ISSUE TITLE
Click or Drag event not working - Require crossvent debug error

### ISSUE THREAD

**Issue by neuropass** [bevacqua/dragula#324]
I set up the demo page and and everything seems to be working, except I get a debug error for the Click or Drag! example:

```
ReferenceError: require is not defined
var crossvent = require('crossvent');
```

what does it mean? :-/ I dont get it. all works excpet that and I just followed the example from the package. I included the dragula.js and example.js

**Comment by bevacqua** [comment]
Please refer to [Slack](https://dragula-slackin.herokuapp.com/) for support requests
