### ISSUE TITLE
allow addContainer to take container id

### ISSUE THREAD

**Issue by ko-porter** [bevacqua/dragula#33]
in my use case, i'll be adding containers dynamically to the page, making them part of dragula containers. therefore those will have dynamically created ids.
it would be ideal to be able to pass the id to the drake.addContainer method (addContainer("left2")
I've also tried passing the dom object through jquery, such as addContainer($("#left2")), but i'm getting an error when doing so.
only addContainer(left2) seems to work

**Comment by bevacqua** [comment]
you need to pass raw dom elements
