### ISSUE TITLE
Can't drop until moving the item below the target (horizontal sorting)

### ISSUE THREAD

**Issue by alvarotrigo** [bevacqua/dragula#333]
[Reproduction online](https://jsfiddle.net/sztccwsx/2/)

Video:
![dragula](https://cloud.githubusercontent.com/assets/1706326/13723925/c428701c-e86b-11e5-8a01-de141db6d99d.gif)

**Comment by timfish** [comment]
I'm seeing this too. It looks like it doesn't sort until the mouse position moves below the middle.

**Comment by alvarotrigo** [comment]
Yep, which makes sense for vertical sorting, but not for horizontal one.

**Comment by timfish** [comment]
This appears to be fixed by setting the option: 
```
direction: 'horizontal'
```

https://jsfiddle.net/k4xcdg43/

**Comment by alvarotrigo** [comment]
That's so lame of me :) 
Thanks for pointing it out!

**Comment by timfish** [comment]
Don't worry, I did exactly the same!
