### ISSUE TITLE
Can't drag item into div if its css has "display: flex"

### ISSUE THREAD

**Issue by timfish** [bevacqua/dragula#334]
Not sure if flexbox is supported, but I can't drag items into a flex div. When I remove only that css it all works as you'd expect.

**Comment by rasdaniil** [comment]
Same story!

**Comment by rasdaniil** [comment]
Found out- you _must_ have all css rules mentioned in your styles

**Comment by diegoponciano** [comment]
@timfish @rasdaniil how did you sorted it out? I can't make it work with display: flex

**Comment by timfish** [comment]
@diegoponciano I'm afraid I can't remember. I should have posted it here.

**Comment by rasdaniil** [comment]
@diegoponciano 
for me the solution was to correctly specify all four css rules according to the documentation

**Comment by stephan281094** [comment]
Thank you @rasdaniil, that solved my issue. For future readers: It's important to declare the Dragula styling *after* your own styling, otherwise it might still not work.
