### ISSUE TITLE
Drag divs into recycle bin

### ISSUE THREAD

**Issue by mburger81** [bevacqua/dragula#340]
Hello,

is it possible to have some divs (widgets) which you can drag into an other div which is my recycle bin having an event if you dragged it over the recylce bin. But the recycle bin should not be able to dragging??

I hope I explained it good enough.

thx
Michael

**Comment by bevacqua** [comment]
It is doable. Please refer to our Slack channel for support requests. You can join using the link on the website.

**Comment by oodboo** [comment]
@mburger81 Have you succeeded with this, I am looking similar functionality where "Recycle bin" will behave as "black hole" it will just register that object is dropped but it will not remove it from the Source.
Additionally I would like to avoid seeing shadow on the target while dragged object is hovering, just highlight would be enough...
Have you tried anything similar do you have any examples?

**Comment by mburger81** [comment]
@oodboo Sorry for my late answer!
No I was not able to do that. I changed drag&drop  lib and  integrated one by my self.

Did you resolve the functions and can share more information  here?
