### ISSUE TITLE
Drag and drop nested

### ISSUE THREAD

**Issue by ricardoleiteff** [bevacqua/dragula#341]
Hello,

It is possible to drag and drop with nested elements?

Something like the print i send here, where i need to move "group" inside "group" or move link  to other group.

Best regards
<img width="810" alt="screen shot 2016-03-17 at 18 03 36" src="https://cloud.githubusercontent.com/assets/16288430/13855931/93cd4d04-ec6a-11e5-86dd-0ab93444c477.png">

**Comment by bevacqua** [comment]
Use the slack channel. See the website for how to join.

**Comment by catmeme** [comment]
@ricardoleiteff  here is an example I found in another issue that might help you: http://codepen.io/sherbrow/full/rVZoRp

**Comment by linearza** [comment]
https://github.com/bevacqua/dragula/pull/358

**Comment by josdejong** [comment]
Thanks for the examples @catmeme . The example http://codepen.io/trzmaxim/pen/GppXGE was exactly what I'm looking for. However, dragula throws a errors whilst dragging in the nested tree:

```js
dragula.js [sm]:406 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': 
    The new child element contains the parent.
    at HTMLHtmlElement.drag (http://rawgit.com/bevacqua/dragula/master/dist/dragula.js:443:18)
```

Any ideas?

**Comment by andreiglingeanu** [comment]
@josdejong I've got same thing while playing with it. I guess there's some flaws going on around `isContainer` function. I'll play with it a bit more and probably will come up with more info.

**Comment by syu93** [comment]
I've the same issue, It's not breaking the behavior but maybe this need to be reopened, or to be in a separate issue ?

**Comment by andreiglingeanu** [comment]
> I've the same issue, It's not breaking the behavior but maybe this need to be reopened, or to be in a separate issue ?

I'd be happy to open a new issue with more info on that subject, if I'll know that there's some interest in that. Until then I'll be using a [fork](https://github.com/Creative-Themes/dragula) where I cherry picked a couple of pull requests that are still not yet merged.

cc. @bevacqua

**Comment by paulcpederson** [comment]
I think the uncaught exception arises when you try to drag a node inside itself. I was able to get around this error with just CSS. Say I have a tree structure which is marked up with unordered lists:

```
<ul class="list">
  <li class="item">
    <ul class="list">
      <li class="item"></li>
      ...
    </ul>
  </li>
  ...
</ul>
```

Each `<li>` can be dragged into any `<ul>` so items can move up/down levels in the hierarchy. I applied the following css to hide children of a node while it is being dragged:

```
.item.gu-mirror > .list,
.item.gu-transit > .list {
  display: none;
}
```

This made the errors go away. I think it's better for users as well because it's more like how dragging works in the file system (ie. when you drag a folder the entire folder tree isn't shown dragging to the new location). Pretty old thread, but somebody in the future might find this useful...

**Comment by crummm** [comment]
This appears to be an even cleaner approach.

`accepts: (el, target, source)=> {
    // don't allow the target to be dragged into one of its children
    return !el.contains(target);
}`

As an added bonus, unlike the CSS solution, this one doesn't collapse and hide its contents when dragging.

**Comment by saurabhit49** [comment]
thank you @crummm your solution works fine to me

**Comment by jloguercio** [comment]
> accepts: (el, target, source)=> {
>     // don't allow the element to be dragged into one of its children
>     return !el.contains(target);
> }

Please can you explain with the complete code please?

**Comment by jloguercio** [comment]
> This appears to be an even cleaner approach.
> 
> ```
> accepts: (el, target, source)=> {
>     // don't allow the element to be dragged into one of its children
>     return !el.contains(target);
> }
> ```
> As an added bonus, unlike the CSS solution, this one doesn't hide its contents and collapse when dragging.

@crummm 

Can you explain with the complete code? i cant archieve how to make this works
