### ISSUE TITLE
Sorting in target containers only (copySortSource enable sorting in all)

### ISSUE THREAD

**Issue by alvarotrigo** [bevacqua/dragula#343]
Documentation states that when using `copySortSource:true` *elements in copy-source containers can be reordered*
[Reproduction online](https://jsfiddle.net/sztccwsx/3/)

I'm a bit confuse with the term `copy-source containers`. What does it exactly mean?

I'm trying to allow reordering in target containers to which elements where copied. **But I do not want to allow reordering elements in the source.**

**Comment by bevacqua** [comment]
Copy-source container is the `container` where a drag operation begins for a `drake` instance that has `copy: true`

**Comment by bevacqua** [comment]
You can set `copy` to a function that prevents the target container from creating copies. In that case you should get the behavior you want.
