### ISSUE TITLE
Ability to select option elements and drag them?

### ISSUE THREAD

**Issue by ekeric13** [bevacqua/dragula#347]
In the api we can set what moves and what doesn't, but this seems to restrict the ability to do other ux features. If we have a select tag as our container and set what moves as true to everything it doesn't seem possible to select option elements anymore.

Is there a way to make an element draggable after someone starts to try and drag it?

Ex:
```
var drake = dragula([selectEl, secondSelectEl], {
    moves: function (el, source, handle, sibling) {
         return handle.tagName !== 'OPTION';
       }
});
```
so right now the option elements are still selectable
```
drake.on('drag', function(el) { 
 dragula([selectEl, secondSelectEl], {
        moves: function (el, source, handle, sibling) {
          return true;
        }
});
```
and now we can drag them. But the problem is when you set them option elements as initially not selectable there is no way i can begin to drag them...

**Comment by bevacqua** [comment]
If you added `OPTION` here, would that fix it? Please test it and if that's the case then create a PR. Thanks

**Comment by ekeric13** [comment]
So it turns out that drag and drop doesn't really work well for option elements so my workaround was just using divs instead, and then giving the divs option element like functionality.
