### ISSUE TITLE
Unexpected copy behavior 

### ISSUE THREAD

**Issue by cinaglia** [bevacqua/dragula#348]
I believe that commit 69137e8b5dd26ce164cb9096469269984bf4b5c8 introduced a regression when dealing with elements with both `copy:true` and `revertOnSpill:true`. Here is a [jsfiddle](https://jsfiddle.net/4g23u23z/) that reproduces the issue.

![dragulabug](https://cloud.githubusercontent.com/assets/95875/13956846/a65f18bc-f020-11e5-9325-0e2dcc8e695d.gif)

I was able to fix the issue by checking if `parent` is truthy, but was unsure whether this is the ideal solution given use cases of which I might not be aware:
```js
if (initial === false && reverts) {
  if (_copy) {
    if (parent) {
      parent.removeChild(_copy);
    }
  } else {
    _source.insertBefore(item, _initialSibling);
  }
}
```

If this is an acceptable solution, I'll go ahead and make a PR.

**Comment by bevacqua** [comment]
Sounds like that should fix the issue. Thanks for catching it. Go ahead and issue a PR. Thanks

**Comment by nickleus** [comment]
great, thx @cinaglia, i applied yor patch n it seems to hav cleared things up :)

**Comment by BlueM** [comment]
Patch worked for me, too. Thanks.

**Comment by Kolyasya** [comment]
Have the same issue, thank you for fix

**Comment by nickleus** [comment]
@cinaglia unrelated q, how did u make that gif--it's a cool idea to demonstrate behavior in a post like this :)

**Comment by cinaglia** [comment]
@nickleus I used [Giphy Capture](https://itunes.apple.com/us/app/giphy-capture.-the-gif-maker/id668208984?mt=12) which used to be called GifGrabber.

**Comment by nickleus** [comment]
@cinaglia thx man

**Comment by CHH** [comment]
Hi, I'm also running into this problem. Any timeline when this fix will be released @bevacqua?

**Comment by cinaglia** [comment]
Fixed in https://github.com/bevacqua/dragula/pull/424.
