### ISSUE TITLE
Send Data to Drop Target

### ISSUE THREAD

**Issue by jdittrich** [bevacqua/dragula#354]
**Use Case**: As a user of the dragula, I want to be able to pass data (a JSON) from dragged element to the drop target. 

**Context**: This function could be useful when using MVC/reactive libraries, in which I make my changes data driven. Such a function is also part of the [HTML5 Drag/Drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API#Interfaces) (as an example).

**Comment by SamLebarbare** [comment]
Use a html `data-` attribute on your movable elements, on drop, copy the payload on the target,

`<div data-my-payload="{json: 'true'}" />`

you can access data content on an element with el.dataset.myPayload (string)
