### ISSUE TITLE
Reorder in Own Container, but Copy to Another

### ISSUE THREAD

**Issue by joelclimbsthings** [bevacqua/dragula#355]
I can't quite seem to reproduce the behavior I want with the given options. I have a few containers, each with 1 or more list elements in them that need to be draggable. If I drag them within their own container I want them to reorder, BUT if I drag them to a different container I'd like them to copy. 

I can create both sets of behavior, but not at the same time.

Is this possible?

**Comment by zetura** [comment]
Hi,

You need to use the `copy` and `copySortSource` options and pass them to `true`.
Is this working for you ?
