### ISSUE TITLE
How do I animate the gallery reordering as I drag around an image?

### ISSUE THREAD

**Issue by jdmswong** [bevacqua/dragula#362]
`transition: all .5s ease;` doesn't do the trick, it animates the opacity but not movement. 

How would one achieve an effect like this:
http://codepen.io/GreenSock/pen/dPZLEp

**Comment by nivv** [comment]
@jdmswong your codepen works for me in chrome

**Comment by bevacqua** [comment]
Please refer to our Slack channel for support requests. You can join our Slack channel through [this link](https://dragula-slackin.herokuapp.com/).

Thanks! :tada:
