### ISSUE TITLE
Dracula doesn't read jQuery triggered mouse-events for some reason

### ISSUE THREAD

**Issue by essekia** [bevacqua/dragula#366]
Hi,

I have something like this inside my Qunit test:

```
    jQuery(el).mouseover();
    jQuery(el).mousedown();
    jQuery(target).mousemove();
    jQuery(target).mouseup();
```

also tried

```
    jQuery(el).trigger('mouseover');
    jQuery(el).trigger('mousedown');
    jQuery(target).trigger('mousemove');
    jQuery(target).trigger('mouseup');
```

... to test a drag event. This does not work, while I can manually drag the elements. I populate the drake.containers in another module, by passing the DOM elements. Don't have a lot of issues with real application.

Do you have a better way to test / trigger drag?

Thanks.

**Comment by bevacqua** [comment]
Please refer to our Slack channel for support requests. You can join our Slack channel through [this link](https://dragula-slackin.herokuapp.com/).

Thanks! :tada:
