### ISSUE TITLE
How to place dragging element on drop position?

### ISSUE THREAD

**Issue by vilianfung** [bevacqua/dragula#372]
Hi:
I am in trouble in drawing text on image according to dragging element's posistion ,How can i place dragging element in drop position without revert!?
Regards,

**Comment by bevacqua** [comment]
Please refer to our Slack channel for support requests. You can join our Slack channel through [this link](https://dragula-slackin.herokuapp.com/).

Thanks! :tada:

**Comment by posherry** [comment]
I have the same question?
