### ISSUE TITLE
Window phone not working

### ISSUE THREAD

**Issue by JustasKuizinas** [bevacqua/dragula#377]
Dragula seems to not work on widnows phone (nokia lumia 925, 8.1). When I try to drag item nothing happens only page start to move.

![animation](https://cloud.githubusercontent.com/assets/5862640/15390057/626a5886-1dc2-11e6-868c-d4a646bd49f8.gif)

**Comment by justas-kuizinas** [comment]
up

**Comment by gbreeze** [comment]
Also not working on Windows Mobile 10 (Edge)
