### ISSUE TITLE
Changing clone id without changing id of original

### ISSUE THREAD

**Issue by dhananjaykhanna** [bevacqua/dragula#384]
I was using the example you gave where we can only copy from one side to another.

My issue is that no matter what I do, the ID of the copy stays the same as the ID of the original. What I want is for the copy to get a completely new ID, while the original keeps it's old ID. How do I do that?

Originally, I tried changing the id attribute of my clone after it was copied using the .on(drop event):

.on('drop', function (el) {
    counter++;
    el.id = 'dropped_' + counter;
    console.log('new ID: ' + el.id);
  });

But this didn't actually change the ID, the copy on the right still kept the ID of the original box.

I then try this:
copy: function (el, source)
  {
    counter++;
    el.id = 'dropped_' + counter;
    return source === document.getElementById('typeList');
  }

This changes the id of the original which I don't want to do

**Comment by bevacqua** [comment]
Please refer to our Slack channel for support requests. You can join our Slack channel through [this link](https://dragula-slackin.herokuapp.com/).

Thanks! :tada:
