### ISSUE TITLE
Inner dragging element

### ISSUE THREAD

**Issue by ogranada** [bevacqua/dragula#385]
I'm testing the library, is very powerful. Now I have a question. given three containers, I want convert the green container in another dragula instance to move inner elements and sort them. Is it possible?
![image](https://cloud.githubusercontent.com/assets/1445677/15747388/1aecf02a-28a0-11e6-99de-19a44c606e97.png)

Thanks.

**Comment by bevacqua** [comment]
Please refer to our Slack channel for support requests. You can join our Slack channel through [this link](https://dragula-slackin.herokuapp.com/).

Thanks! :tada:
