### ISSUE TITLE
Error when installing, issue with package?

### ISSUE THREAD

**Issue by zurnet** [bevacqua/dragula#386]
See Terminal Log:

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! ng2-dragula@1.1.9 postinstall: `typings install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ng2-dragula@1.1.9 postinstall script 'typings install'.
npm ERR! This is most likely a problem with the ng2-dragula package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-dragula
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ng2-dragula

**Comment by bevacqua** [comment]
This is not `ng2-dragula`. Please report in [their repo](https://github.com/valor-software/ng2-dragula).
