### ISSUE TITLE
Why use '.js' on bower package?

### ISSUE THREAD

**Issue by kelvinst** [bevacqua/dragula#39]
Very nice lib, but, I'm trying to use it in a rails project, and I'm getting some problems:

1. I couldn't get how to install it manually, it depends from some libs and this is not very well documented;
1. I couldn't use [rails-assets](http://rails-assets.org) for it, because the name of it on bower have the dot char, which is an invalid name for a ruby gem. This could be handled on rails-assets gem generator of course, but I don't really know which are the best practices for naming for bower packages.

So, if you could just explain which libs you depend from, to some other people that want to install it manually, it would be very helpful. The second point is optional, but IMHO it would be better a name without dot (PS: why not just 'dragula', since this package name is not in use on bower yet)

**Comment by bevacqua** [comment]
`dragula` yields `EDUPLICATE` when I attempt to register it. To install it manually grab the files in `dist` folder.

**Comment by kelvinst** [comment]
Sorry, but just get the files on `dist`, didn't work for me. I'm trying to use them with rails `asset-pipeline`, probably you handle the dependencies in a way that the asset pipeline can't get...

I'll try a little more sometime, for now, I can't spend more time investigating this things.

**Comment by bevacqua** [comment]
Just drop the script in a blank HTML page and you'll see it works well. This has nothing to do with `dragula`

**Comment by kelvinst** [comment]
I know it hasn't, it's just the way you handle your dependencies that are incompatible with rails asset pipeline, when I get something more on it, I'll let you know.

**Comment by bevacqua** [comment]
FWIW, dragula on bower is now registered as `dragula`, no dot
