### ISSUE TITLE
drag element doesn't respect the css class

### ISSUE THREAD

**Issue by gogowater** [bevacqua/dragula#393]
Hi I am new to your dragula but it is working great.  One issue I have is that the drag element doesn't have any css style in there during dragging.  I inspected the element, and it has classname in it.  The element HTML contains many inner div and each has the css style to it  (See below).  None of it respects the css.  Any idea?

`<div class="opp-card">
        <div class="opp-logo tipped-top" title="">
            <img src="https://s3.amazonaws.com/insightly.userfiles/36409/X63SVW/0af9707e-048a-4e26-a4ea-0637eafdab67.png">
        </div>
            <div class="opp-price">$100 USD</div>
    <div class="opp-name">
        <a class="nopjax" target="_blank" href="/Opportunities/Details/3">Opportunity</a>
    </div>
        <div class="opp-org">
            <a class="nopjax" target="_blank" href="/Contacts/Details/1">John Smith</a>
        </div>
    <div class="opp-date">
            Wed 22-Jun-2016
                    <span class="opp-win-perc">2 %</span>
    </div>
</div>`

**Comment by bevacqua** [comment]
Please refer to our Slack channel for support requests. You can join our Slack channel through [this link](https://dragula-slackin.herokuapp.com/).

Thanks! :tada:
