### ISSUE TITLE
Reorder rows in table

### ISSUE THREAD

**Issue by spapaseit** [bevacqua/dragula#394]
Hi, 
I want to allow the user to reorder `tr` in a `table` by means of drag and drop.

I have marked the `tbody` of a table with the classes `drag-source` and `drop-target` , `<tbody class="drag-source drop-target">...</tbody>` and I initialize dragula as follows:

```
constructor() {
    let dragApi = dragula({
            isContainer: el => {
                if (!el) {
                    return false;
                }
                if (dragApi.dragging) {
                    return el.classList.contains("drop-target");
                }
                return el.classList.contains("drag-source");
            },
            revertOnSpill: true,
            delay: 200
        });

        this.trackDrop(dragApi);
    }

    trackDrop(dragApi) {
        dragApi.on("drop", (el, container, source) => {
            dragApi.cancel();
        });
    }
```

This is part of an [Aurelia](http://aurelia.io) application, and at the time of the dragula initialization the DOM is not yet available; that's why I don't pass the `containers` option directly into dragula.

### The problem
I cannot drop the `tr` back into the table on a new position. The drag _is always reverted_. If I turn `revertOnSpill` off, the drag never ends, and the call to `dragApi.cancel()` ends up with a `Maximum call stack exceeded`

How can I achieve reordering of the table `tr`?

**Comment by spapaseit** [comment]
Ok, nevermind; the penny dropped. I need to reorder the underlying array myself, of course, otherwise Aurelia will redraw based on the original contents of the array.

**Comment by jjlorenzo** [comment]
`dragula-model` doesn't works for you?
