### ISSUE TITLE
Dynamic mirrorContainer

### ISSUE THREAD

**Issue by Namek** [bevacqua/dragula#395]
As there is possibility to dynamically add containers, there should be possibility to dynamically set the mirrorContainer. For me it would be best to set previously defined container to which belongs the moved element.

**Comment by jaschaio** [comment]
@Namek did you ever figured out a way to do that?

**Comment by jaschaio** [comment]
For future reference: I actually just found a way. As described here https://github.com/valor-software/ng2-dragula/issues/776 you can just save a reference to the options object and than modify the `mirrorContainer` attribute later.
