### ISSUE TITLE
Container ids with dashes gives an error

### ISSUE THREAD

**Issue by allan-farrell** [bevacqua/dragula#40]
Anytime I try to specify a container id with a dash in it (i.e. left-container) for the initial dragula call I get an error. So:

dragula([leftcontainer,rightcontainer]) will work but
dragula([left-container,right-container]) won't

Specifying containers currently seems to take advantage of the automatically defined properties on the Window object - it would be helpful if we could also  specify any id so long as it's valid according to the spec.

**Comment by bevacqua** [comment]
That's just a demo. Use selectors to find DOM elements, it's not a good practice to use the `window` references
