### ISSUE TITLE
Freeform Drag

### ISSUE THREAD

**Issue by sqwk** [bevacqua/dragula#410]
Is it possible to drop elements on a container and allow moving them around, overlapping one another and without sorting them against other elements? In both x and y directions? Possibly by specifying something like `direction: none`?

**Comment by jawwadfarooq** [comment]
You can even try [](http://draggabilly.desandro.com/)

**Comment by sqwk** [comment]
I have solved this using interact.js for now, but thanks for the suggestion … will look into it.
