### ISSUE TITLE
iFrame state is lost while dragging

### ISSUE THREAD

**Issue by jawwadfarooq** [bevacqua/dragula#414]
Hi,

I have made a <div> element draggable which contains an iFrame element inside it. Now, the issue is when the dragging starts, the contents of the iFrame are started to refetch. And the refetching occurs multiple times from initial state while dragging to new places. Dropping of the block/element is the last time when the contents are refetch.

Is there any way to stop refetching and reloading of iFrame?

**Comment by bvkimball** [comment]
Is there a workaround for this?

**Comment by jawwadfarooq** [comment]
Not in my knowledge. I was also looking for some solution.

**Comment by mootari** [comment]
A possibly related problem: In our case a CKEditor instance inside a draggable loses its iframe content as soon as the draggable's placeholder gets positioned.

**Comment by mootari** [comment]
Apparently most browsers will reload an iframe whenever it or its parents get detached/reattached (see https://stackoverflow.com/a/39895407/521868).
There's really nothing here to be done. It's not dragula's fault, and it can't do anything about it.
