### ISSUE TITLE
Necessity & Bug[removeOnSpill] (?)

### ISSUE THREAD

**Issue by sdkcarlos** [bevacqua/dragula#42]
![dragcopy](https://cloud.githubusercontent.com/assets/11634719/7324496/965be8e6-ea7c-11e4-8ed0-bce741e4430a.png)

I need the user drag options from white zone to the black (down), I added on the drop event the necessary thing to prevent the user drop from black to white because is not allowed but when i move from right to left in black zone it copies and i need to stop the copy.

I have the following code : 

            $(function(){
                dragula([left1, right1,top1],{
                    removeOnSpill: true,
                    copy:true,
                }).on('drop', function (el, target, source) {
                    
                    if(source == left1 && target == top1){
                        alertify.error("Sie können keine Optionen hinzufügen");
                        el.remove();
                        return false;
                    }
                        
                    if(source == right1 && target == top1){
                        alertify.error("Sie können keine Optionen hinzufügen");
                        el.remove();
                        return false;
                    }
                    
                    if(source == left1 && target == right1){
                        // I need to remove the origin element from here
                        // removeOriginElement();
                    }
                });
            });    

I would really appreciate your help with this, do i need to handle accepts method ?, how ? 
And finally , i have the removeOnSpill set to true, and is not working.

Excelent library :+1: and very useful, thanks.

**Comment by bevacqua** [comment]
Use accepts.

```js
        $(function(){
            dragula([left1, right1,top1],{
                removeOnSpill: true,
                copy:true,
                accepts: function (el, target, source) {
                  return source !== left1 && target !== right1
                }
            }).on('drop', function (el, target, source) {

                if(source == left1 && target == top1){
                    alertify.error("Sie können keine Optionen hinzufügen");
                    el.remove();
                    return false;
                }

                if(source == right1 && target == top1){
                    alertify.error("Sie können keine Optionen hinzufügen");
                    el.remove();
                    return false;
                }

                if(source == left1 && target == right1){
                    // I need to remove the origin element from here
                    // removeOriginElement();
                }
            });
        });  
```
