### ISSUE TITLE
Bug when revert on spill and drag a copy item

### ISSUE THREAD

**Issue by sdad120** [bevacqua/dragula#423]
When you drag a copy item and have not put it in any containers we will cause a null error.
Example [here](https://jsfiddle.net/sbgtkL18/)
And the problem is [here](https://github.com/bevacqua/dragula/blob/master/dist/dragula.js#L326), we forget to check if this parent is null or not

**Comment by gnujeremie** [comment]
I am having this issue, using ng2-dragula.

**Comment by gnujeremie** [comment]
I opened a pull request (https://github.com/bevacqua/dragula/pull/424) I hope it'll be merged soon :)

**Comment by bevacqua** [comment]
Fixed in `3.7.2`
