### ISSUE TITLE
Can we use dragula with iframe? Drage element into iframe?

### ISSUE THREAD

**Issue by jaypalsolanki** [bevacqua/dragula#425]
Can we use this dragula with IFrame? 

I have two section first dragable element section and second dropable section, in dropable section i want to use iframe and want to drag the element in the iframe. Is it possible?

for example:

dragula([document.getElementById('left-defaults'), window.frames["iframename"].document.getElementById("right-defaults")]);

**Comment by simonverzelen** [comment]
I would like to know that too before using this plugin.

**Comment by tiaguinho** [comment]
I create a blog post with an example of how I implement this.

https://medium.com/@_ttemporin/dragula-with-iframe-9530c0d7e9fd
