### ISSUE TITLE
IE8 compability Array.isArray

### ISSUE THREAD

**Issue by kriku** [bevacqua/dragula#43]
dragula.js line 47, character 7

You use isArray function, but this function supports from IE9.. [Array.isArray()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray)

So without polyfills your library don't work in IE less than 9.. And in Readme no info about this issue

**Comment by bevacqua** [comment]
Yes, consumer should add functional ES5 array methods as needed.

**Comment by kriku** [comment]
but this:
> Browser support includes every sane browser and __IE7+__.

change plz?

**Comment by bevacqua** [comment]
It supports them, you just need to add the polyfills

**Comment by kriku** [comment]
In my mind, if don't work without polyfills - it is necessary to say
_(and I will not say "supports")_

**Comment by yoyo1218** [comment]
I have include es5-shim.js,but I still can't drag on IE9 . Can you help me ?

**Comment by bevacqua** [comment]
Report a proper issue explaining the bug
