### ISSUE TITLE
dragulaService.add

### ISSUE THREAD

**Issue by dozen1488** [bevacqua/dragula#437]
I am new in typescript. 
I'v tried to create draggable zones in my app dynamicly, using dragulaService.add. Readme says "Typically, the directive takes care of this step". But it's not. 
dragulaService.add(name, drake) requers implementation of drake.on 
("bag.drake.on is not a function" error). 
I think it requres dragula object, wich is hidden in DragulaDirective and has no reference in DragulaProvider. So the question is : can I dynamicly create zones using typescript?

**Comment by dozen1488** [comment]
Oh. I found out how to do it 
`this.dragulaService.find('third-bag').drake.containers.push(document.getElementById('bager'))`
that code is realy dissapointing. 
I have to create at least one [dragula] component, and use it's drake property.

**Comment by apoorv-techelogy** [comment]
@dozen1488  can you share your code where you define 'drake' ?
i am confused with it.
