### ISSUE TITLE
ESC Key cancel dragging 

### ISSUE THREAD

**Issue by abnerfs** [bevacqua/dragula#439]
Would be awesome ESC key cancel drag for cases when you drag a cart accidentally

**Comment by MateusDmn** [comment]
@bevacqua 

I'd be willing to do it. Would you add it to a commit?

:)

**Comment by ChrystianOrgm** [comment]
Very nice my friend.
This code gonna help me.

**Comment by MateusDmn** [comment]
Bumping for interest. May I create a pull request?

**Comment by bevacqua** [comment]
Doesn't belong in the library. This is something that's come up repeatedly. It's a great feature to have, but also trivial to implement outside of core. Since it's kind of invasive, I prefer to leave it up to the consumer.
