### ISSUE TITLE
Angular 1 demo do not work

### ISSUE THREAD

**Issue by kubek80** [bevacqua/dragula#467]
404 error on:
http://bevacqua.github.io/angularjs-dragula/dist/angularjs-dragula.js

**Comment by eduardbosch** [comment]
Demo for Angular 1 does not work.
http://bevacqua.github.io/angularjs-dragula/

Seams that the error is the same cause that @kubek80 reported.

**Comment by MagnifierSun** [comment]
the same question

**Comment by dcantatore** [comment]
Issue in that repo not this one
