### ISSUE TITLE
Target element by class

### ISSUE THREAD

**Issue by Exerlol** [bevacqua/dragula#47]
Is it possible to pass class instead of id to target an element ? Something like: 

 <div id="left1" class="col-lg-6 container">
        <div class="">Move me, but you can only drop me in one of these containers.</div>
        <div>If you try to drop me somewhere other than these containers, I'll just come back.</div>
    </div>
    <div id="right1" class="col-lg-6 container">
        <div>You can drop me in the left container, otherwise I'll stay here.</div>
    </div>

dragula([.left1, .right1]); ??

One more thing, how can i know where dragged element is dropped? Can i see exact tag that element was dropped IN? 

Thanks in advance.

**Comment by bevacqua** [comment]
Pass in DOM elements
