### ISSUE TITLE
revertOnSpill doesn't work

### ISSUE THREAD

**Issue by twwd** [bevacqua/dragula#478]
On the [demo page](https://bevacqua.github.io/dragula/), the example for the `revertOnSpill`option doesn't work for me.

Tested on Win 10 and Ubuntu with Firefox and Chromium.

**Comment by SheW0lf** [comment]
I'm not sure if someone went ahead and fixed this issue, but it seems to be working fine for me with Windows 10 FireFox and Chrome as well as my Ubuntu machine on Chrome

**Comment by twwd** [comment]
For me, it still doesn't work, tested on Windows 10 and Android in Firefox and Chromium. The items jump back to the last container and not to the origin container.

![revertonspill](https://cloud.githubusercontent.com/assets/8222565/25129329/d9d1d9b2-243d-11e7-80ca-2f75b5b508c9.gif)

**Comment by SheW0lf** [comment]
The revertOnSpill is supposed to return the element to the last position it was in before the spill over not it's original position. It appears to be working correctly in your example above.

**Comment by twwd** [comment]
It looks like I misunderstood the description of this feature. I thought the items go back to the container where there were first listed and not just back to their last list position. That would be the feature I need...

My fault - sorry for that.
