### ISSUE TITLE
Posibillity to swap items from lists

### ISSUE THREAD

**Issue by jordyvaneijk** [bevacqua/dragula#485]
Is there a possibility to swap items from one to another list by dragging item 1 from list A to item 2 of list B

and then swap item 2 from list B over to item 1 from list A?

**Comment by glerinsonum** [comment]
@bevacqua Hi Brother of Good. 
Thank for this script that drag & drop my works from sidebar. but. can give me an script with window, exampl. change background image, edit this text heading, make center postition text. etc etc.
