### ISSUE TITLE
Problem: Figures out sort order on its own

### ISSUE THREAD

**Issue by radenkozec** [bevacqua/dragula#489]
I have a issue with Dragula. When I refresh source of the list` the.columnList = newValue;`
Dragula try to figure out sort order and mess up order I got from the server side.
Is there a way to prevent feature:
*Figures out sort order on its own*

**Comment by vatsalpande** [comment]
Did you find any solution for this? I am facing the same issue

**Comment by radenkozec** [comment]
I am using Aurelia SPA framework with Dragula.
https://github.com/aurelia/templating-resources/issues/282
Solution that worked for me is to call https://github.com/jdanyow/aurelia-solitaire/blob/master/src/drag-and-drop.js#L41 to cancel Dragula operation and then update list manually via JavaScript.

**Comment by vatsalpande** [comment]
Ultimately, I ended up doing the same thing. Thanks for your reply
