### ISSUE TITLE
Shadow position when revertOnSpill == true

### ISSUE THREAD

**Issue by ConnorKrammer** [bevacqua/dragula#49]
I was playing around with the demo and noticed that setting `revertOnSpill` to `true` results in a misleading shadow position. By this I mean that if you move the item down the list so that its shadow goes from, say, the first to the third position, moving the item out of the box leaves the shadow in the third position. This would seem to indicate to a user that letting go would snap it to the third position, when it would really return to the first.

Steps to reproduce, for clarity:

1. Grab item
2. Drag so that shadow indicates new position
3. Move item outside of drop-friendly zone
4. Note how shadow does not revert to original position

The main issue with this is that a user can't tell the difference between a box where `revertOnSpill == true` and one where `revertOnSpill == false` without making a mistake with their drag. There's a chance that it actually moves to the indicated area, but there's also a chance that it returns to the original position -- that's a confusing and potentially harmful experience. Consider the case where a user drags a document over a trash icon, then changes their mind. They attempt to cancel the drag by moving the mouse outside the drop zone, but the item is deleted anyway -- they assumed `revertOnSpill` was `true`, when it was actually `false`.

**Comment by bevacqua** [comment]
Could you try and implement this feature?

**Comment by ConnorKrammer** [comment]
I can take a look tomorrow then submit a pull request, sure.

**Comment by bevacqua** [comment]
Any progress on this? Thanks

**Comment by ConnorKrammer** [comment]
Sorry about saying that and then going dead – I’ve been unexpectedly busy recently. I should have some free time soon so I hope that I’ll be able to get around to it.

Just a confirmation beforehand: you're okay with my suggestion (no modifications)?

**Comment by bevacqua** [comment]
Yeah, just for `revertOnSpill: true`
