### ISSUE TITLE
Interfering with click functionality outside of controlled blocks

### ISSUE THREAD

**Issue by NatPlane** [bevacqua/dragula#490]
Having an issue with click functionality when using Dragula.  Complete component below.  Removing the [dragula] attribute off the first div restores click functionality to the outer nodes.  With dragula activated the outer nodes click does not fire.  To further confuse the situation, if you change the result of exampleData() call to return ["a", "b"] the clicks again work, it only appears to be an issue when binding the 2nd ngFor to a function call yielding an array of objects while having dragula enabled.
~~~~
import { Component } from '@angular/core';
import { DragulaService } from "ng2-dragula";

@Component({
    selector: 'bug',
    template: `
        <div [dragula]='"bag-one"'>
            <div *ngFor="let dataItem of data">
                <button class="btn btn-link" (click)="exampleClick()">
                    Inside Dragula :: {{ dataItem.someProperty }}
                </button>
            </div>
        </div>
        <br />
        <br />
        <br />
        <div *ngFor="let anotherItem of exampleData()">
            <button class="btn btn-link" (click)="exampleClick2()">
                Outside Dragula :: {{ anotherItem.someProperty }}
            </button>
        </div>`
})
export class BugComponent {

    data: Array<any>;

    constructor(private dragulaService: DragulaService) {
        this.data = [
            { someProperty: "Inside 1" },
            { someProperty: "Inside 2" }
        ];
    }

    exampleData(): Array<any> {
        return [
            { someProperty: "Outside 1" },
            { someProperty: "Outside 2" }
        ];
    }

    exampleClick() {
        console.log("GOT INSIDE CLICK");
    }

    exampleClick2() {
        console.log("GOT OUTSIDE CLICK");
    }
}
~~~~

**Comment by mikado2** [comment]
Experiencing the same issue. @NatPlane: How did you solve this issue?

Thanks
Michael

**Comment by NatPlane** [comment]
If I remember correctly, in my case it was due to exampleData() being continuously invoked (a simple trace should show that).  So the click event never lived long enough to be invoked.  Not sure why co-existing with Dragula was causing that to happen, but it was.
