### ISSUE TITLE
Make Element Pinned to Location

### ISSUE THREAD

**Issue by vforvasquez** [bevacqua/dragula#492]
> Please only use GitHub issues for bug reports and feature requests.
>
> - [ ] Read the [contributing guidelines][contrib]
> - [ ] Bug reports containing repro steps are likely to be fixed faster
> - [x ] Feature requests should be multi-purpose, describe use cases
> - [ ] For support requests or questions, please refer to [our Slack channel][slack]

Hey guys I was wondering if you had ever considered enabling pinning an item to its location in a bag so that 
1. It cannot be dragged
2. Even when things are added or removed from the bag that it would keep its position. 
(Ex: if a bag's second item was pinned and someone pinned something to the top of the bag the first item would be moved down to the third but the pinned item would remain it the second position)

Thanks!

**Comment by montrealist** [comment]
IMHO there is no need to add anything, since one can implement this functionality inside `options.moves`:

https://github.com/bevacqua/dragula#optionsmoves
