### ISSUE TITLE
Get the index of the dragulaModel dropped item

### ISSUE THREAD

**Issue by calebeaires** [bevacqua/dragula#494]
> - [ ] Read the [contributing guidelines][contrib]
> - [ ] Bug reports containing repro steps are likely to be fixed faster
> - [x] Feature requests should be multi-purpose, describe use cases
> - [ ] For support requests or questions, please refer to [our Slack channel][slack]

Sometimes we have to add data to the dropped item the was put on dragulaModel. This dropped item is being put on a variable position. It would be helpful if we could have the index of this dropped element.

**Comment by mariobro** [comment]
Has this issue been worked on? If not, would you want to know the index/position the item was in it's original place, or do you mean something different?

**Comment by pounard** [comment]
It's easy to get the element position: iterate over element.parentElement.childNodes, and increment a counter until node === element and you're good to go. You have also to check with node instanceof HTMLElement inside your iteration to be sure you're not counting things like whitespace or raw test. This is pure vanilla JS and is blazing fast.

**Comment by paddotk** [comment]
Related: https://github.com/bevacqua/dragula/issues/397

**Comment by paddotk** [comment]
```
const onListItemDrop = (el, target) => {
	// New index of updated item
	const index = [].slice.call(el.parentNode!.childNodes).findIndex((item) => el === item);
```
