### ISSUE TITLE
can't drag svg elements

### ISSUE THREAD

**Issue by boneskull** [bevacqua/dragula#495]
Create an SVG element, put it in a bag; default options ok.  Try to drag it.  You'll get an exception out of `classes.addClass()` because `className` is a read-only property of `SVGElement`.

Now, if you look at [MDN](https://developer.mozilla.org/en-US/docs/Web/API/SVGElement), you'll see `SVGElement` is a subclass of `Element`, and as such you'd think it would work.  Not the case; the SVG 2 specification provides [this interface](https://svgwg.org/svg2-draft/types.html#InterfaceSVGElement), in which `className` is a read-only property.  There's more relevant discussion in [this TypeScript issue](https://github.com/Microsoft/TypeScript/issues/3220).

However, it seems (in Chrome, anyhow) the `classList` property *can* be modified.  This property is apparently not available at all in older versions of IE, so it's unsafe to use wholesale.

Possible ways to address this:

1. Wrap assignment to `className` in a `try`/`catch`, then attempt to use `classList.add()` if caught
2. Use `instanceof` to detect an `SVGElement` and use `classList.add()` in that case

A naive test of the first option seems to work without error.  I made the following changes:

- use `try`/`catch` in `classes.add()` and `classes.rm()`
- replace direct modifications of `className` in `getElementBehindPoint()` with calls into `classes.add()` and `classes.rm()`

**Comment by NeonDevil** [comment]
Specifying the class and it's child (svg + path) as the handle worked for me:

`
 moves: function (el, container, handle) {
   return $(handle).is('.handle-class, .handle-class svg, .handle-class path');
 } 
`

**Comment by dcantatore** [comment]
@boneskull Can you provide a codepen or fiddle of this?

**Comment by boneskull** [comment]
no, i have no idea what this is about anymore 🤪

**Comment by dcantatore** [comment]
Ah nuts. Closing until someone else reports it
