### ISSUE TITLE
Add ability to revert element back to its source after drop.

### ISSUE THREAD

**Issue by neptunecentury** [bevacqua/dragula#499]
I noticed there was no way to send an element back to its source at its original location after dropping it onto its target.

This would be a great feature if say, dropping an element triggers an API call, and that API call fails for some reason. At that point, the element should return to its original source at the same location it came from. I can use jQuery easily enough to send it back to source, but without knowing the position in the source, I can only append to the end or insert at the beginning.

Please add some sort of argument that indicates which position in the source the element came from.

**Comment by djmattyg007** [comment]
Presumably this would be implemented with some sort of "copy" functionality, so that dragging and dropping copies the element rather than moving it.

**Comment by Levsha-cc** [comment]
I used this.cancel() for it.
`var moveInProgress = false;
dragula([selector], {...}).on('drop', function(el, target, source, sibling) {
		if (!moveInProgress) {
			moveInProgress = true;
			$.ajax({...,
				complete: function () {
					moveInProgress = false;
				}
			});
		} else {
			this.cancel();
		}
	});`
