### ISSUE TITLE
Firefox: Incorrect element position while dragging

### ISSUE THREAD

**Issue by Samardon** [bevacqua/dragula#5]
When I try to drag an element after I have scrolled down any amount, the copy element being dragged is incorrectly positioned.
Screenshots attached
Latest version of FireFox
Tested on Chrome with no issue

Before scrolling
![dragula_ff_1](https://cloud.githubusercontent.com/assets/2303534/7152633/5fdf24fc-e2f4-11e4-8c50-d2fe1c541f5a.jpg)

After scrolling
![dragula_ff_2](https://cloud.githubusercontent.com/assets/2303534/7152645/a05bce86-e2f4-11e4-9ab5-b8ec8ac2374e.jpg)

**Comment by bevacqua** [comment]
This will be fixed in `1.2.3`

**Comment by Lambdac0re** [comment]
Seeing it too.

**Comment by bevacqua** [comment]
`1.2.3` released
