### ISSUE TITLE
Drag and drop multiple items

### ISSUE THREAD

**Issue by ljammala** [bevacqua/dragula#50]
Can I select some items and then drag and drop selected items(multiple)?

**Comment by bevacqua** [comment]
Currently you can do this

- if they're all children of the same container
- using the API, when an item is dragged you drag a bunch of other items

**Comment by akisiel1** [comment]
Hi!
Can you provide any example of usage API for drag and droping multiple elements?

**Comment by ozzieperez** [comment]
Hi @akisiel1, were you able to get anywhere with this? I'm looking to do the same thing.

**Comment by akisiel1** [comment]
Hi @ozzieperez! Unfortunately, I didn't find the solution. I gave up dragula in my project.

**Comment by ozzieperez** [comment]
Thanks @akisiel1 . I hammered at it for some time yesterday and was able to get something going. It's definitely hacky, but here's my code if you or anyone else could use it. 

My requirements were to be able to multiselect from the left container to the right container. I used the 'Shift + click' event on the items to multiselect, and the floating preview also reflects the selected items.

https://jsfiddle.net/jw5e4c3c/

**Comment by akisiel1** [comment]
Thanks @ozzieperez  😃

**Comment by fermdp** [comment]
This is wonderful, but can make adding more options? Left to right and right to left in the same example? and multiple selection in the left to left? for example select item 1,3 and 4 and put just down of the item 8?

**Comment by forvy** [comment]
Found this: https://stackoverflow.com/a/55409817/3654837 not perfect but good enough I think.
