### ISSUE TITLE
Firefox throwing an error

### ISSUE THREAD

**Issue by ghost** [bevacqua/dragula#504]
Everything works perfectly in google chrome but firefox throwing an error.

I am getting this error message when i dropped an element on firefox.

TypeError: Argument 1 of Document.elementFromPoint is not a finite floating-point value.

**Comment by Meriyemelhajoui** [comment]
Hi , I m running into the same issue , with firefox i get TypeError: Argument 1 of Document.elementFromPoint is not a finite floating-point value. any idea how to resolve this ?
