### ISSUE TITLE
Using class instead of Id?

### ISSUE THREAD

**Issue by decaller** [bevacqua/dragula#51]
One night, I'm searching for the latest jquery drag and drop feature and got this from google search. Reading down the readme and then the scare jump appears! Then I decided to check it on day only. 

After some testing I realize that it's needed to be an id to be a container. Can we just use class for it so then the container will be more dynamic (I mean add new container or even container inside container)? Or are there workaround for this?

**Comment by bevacqua** [comment]
You just pass in DOM elements.
