### ISSUE TITLE
how to get mirror element?

### ISSUE THREAD

**Issue by keyiis** [bevacqua/dragula#512]
I want prevent drop in accepts method,i need judge the mirror element's previousElementSibling,so how can i get mirror element in accepts method?
```
accepts: (el, target, source, sibling)=> {
     return !(mirror element).previousElementSibling.classList.contains('add-item-btn');
}
```

**Comment by renannobile** [comment]
You could try using pure JS:

document.querySelector('.gu-mirror').previousElementSibling.classList.contains('add-item-btn');

**Comment by keyiis** [comment]
@renannobile thks reply!
