### ISSUE TITLE
Change the location of gu-mirror elsewhere than body

### ISSUE THREAD

**Issue by gregorfelkar** [bevacqua/dragula#514]
Hello,

I have an issue with gu-mirror location, by default it's placed as the last element in `<body>` element. But i have a situation where i have `<div>` container which is scaling it's content and my dragula dnd is located inside that scaled container. So if my container is scaled to 0.5 then when i grab an element to move it moves gu-mirror element which is not scaled because it's outside my container.

So my question is: Is there a way to specify the gu-mirror location?

Or will i have to hack something together, something like getting current scale from container and apply it to gu-mirror?

Thank you

**Comment by mdudek** [comment]
Yes it is, check options.mirrorContainer ...

**Comment by gregorfelkar** [comment]
Thank you, that worked.
