### ISSUE TITLE
Container can't be dragged

### ISSUE THREAD

**Issue by decaller** [bevacqua/dragula#52]
Sorry for bothering you again.
I edited your first demo example so that the right container is inside the left one. The drag and drop function works perfectly but the container won't be dragged. The container moves up if I'm dropping items below it but it won't come down again since I can't drag it. Do I have to edit something or maybe this will be in the future release?
I don't have any advance experience in Javascript so I don't really know how your code works.
Thanks for the answer.

**Comment by bevacqua** [comment]
I'll need a demo

**Comment by decaller** [comment]
I Edited some your demo codes. The right1 is inside the left1
```
<div id="left1" class="container">        
        <div>If you try to drop me somewhere.</div>
        <div class="">Move me, but you can only drop me.</div>
        <div>Item 6.</div>
      <div class="">Item 5.</div>
    
      <div id="right1" class="container">
        <div>You can drop me in the left container, otherwise I'll stay here.</div>
        <div>Item 4.</div>
        <div class="">Item 3.</div>
      </div>
</div>
```

**Comment by bevacqua** [comment]
You can only move immediate children of a container by design

**Comment by cfenzo** [comment]
@decaller Having nested containers with dragula is possible, you just have to make sure that there is:
1. a part of the nested container that you can drag (using padding in my example)
2. a bit of code in `accepts` that prevents dragula from trying to use the dragged container as drop target (it works by default, but throws exceptions).

Here's a quick demo:  http://jsfiddle.net/cfenzo/7chaomnz/

**Comment by jri** [comment]
@cfenzo Thank you for the hint dragula _can_ deal with nested containers! And for your fiddle about the `accept` handler and node.contains() DOM method!

**Comment by Syforce** [comment]
To prevent the "Uncaught HierarchyRequestError: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent." error, just make the selected element's shadow reject all mouse events:

.gu-transit {
pointer-events: none;
}

**Comment by csjasonwong** [comment]
@Syforce  THANK YOU! THANK YOU! AND!!! THANK YOU!!!
