### ISSUE TITLE
ReferenceError: document is not defined when reload page.

### ISSUE THREAD

**Issue by jose920405** [bevacqua/dragula#521]
![captura de pantalla 2017-09-04 a la s 12 06 36 p m](https://user-images.githubusercontent.com/12536184/30034907-28849cc2-916a-11e7-967f-db9ae2ab1840.png)

>Line 4 in `dragula.js`

`var crossvent = require('crossvent');`

>Line 24 in `custom-event/index.js`

`'function' === typeof document.createEvent ? function CustomEvent (type, params) {`

This error happens each time when i reload a page with dragula import.

**Comment by Splaktar** [comment]
This is due to dragula depending on custom-event#1.0.0 and not 1.0.1 which fixed this in https://github.com/webmodules/custom-event/commit/58c6815304500488893e0a12a9489508be22775c.

**Comment by Splaktar** [comment]
Oh and `custom-event@1.0.0` is a dependency of `crossvent@1.5.4`. Updating to `crossvent@1.5.5` pulls in `custom-event@1.0.1`.
