### ISSUE TITLE
Bug with loss of focus input inside container directive

### ISSUE THREAD

**Issue by Ts-alan** [bevacqua/dragula#527]
If we place the input inside dragula directive -we have bug with loss of focus from input when we click on container of dragula directive.

![test](https://user-images.githubusercontent.com/9947228/30915425-77901f02-a39f-11e7-869a-0f252ffdb865.png)
It seems a problem in this part of the code
![test2](https://user-images.githubusercontent.com/9947228/30915454-8f79e5ee-a39f-11e7-8915-95aeb767101d.png)

If I click on input then the focus is not removed from an input when clicking on a green square(hence the event blue does not work)

https://plnkr.co/edit/aY5CXoh7nCrGE3YIWAb7?p=preview

Is it possible to fix this something?

**Comment by amk221** [comment]
Also experiencing this: inability to focus the element being dragged

**Comment by amk221** [comment]
@Ts-alan In the above code (in your screenshot), the prevent default is only reached if dragula considers the click is for a draggable element.

Therefore, it's possible to work around the issue by telling dragula to ignore the element you want to focus:

```javascript
{
  invalid: function(el) {
    return el.classList.contains('ignore-me');
  }
}

...but I agree, it's still classed as an issue.
