### ISSUE TITLE
Question - is this project still alive?

### ISSUE THREAD

**Issue by rmcsharry** [bevacqua/dragula#531]
I understand that people are busy but I notice there have been no commits since Jun 11th.

It would be a shame for such a popular repo to bite the dust. My skills are not good enough to maintain it I'm afraid, but maybe there are others who could be given access to help close some of the pull requests?

**Comment by pounard** [comment]
You're not the only user, I do see from time to time the maintainer answer to issues, so I guess that, at the very least, the maintainer is alive :) Still, I think it is, but is is stable enough to be slow, I guess.

**Comment by rmcsharry** [comment]
@pounard Sorry I don't understand why you state the obvious fact that I am not the only user.

I can see the maintainer is alive but he is clearly very busy on other projects (if you examine what he is committing to on his profile, for example, 179 private repos committed to in Oct - so clearly a busy person!)

I am simply putting out the idea that if he is too busy perhaps it would be a good idea to seek volunteers to enlarge the team of people who can review/close outstanding pull requests and help address the growing list of issues being raised. That's all.

**Comment by pounard** [comment]
Yes, I understand, I don't know what his plans are, but as I can see it, I didn't step through any major or blocking bug I always had a way to do whatever I needed to do, so I guess it's pretty normal for this project to be slow if you consider it as stable enough.

**Comment by rmcsharry** [comment]
@pounard Ok fair point, it is pretty stable. I suppose if it is normal for it to be slow, I can understand and accept that. :)
