### ISSUE TITLE
event dragenter/dragover

### ISSUE THREAD

**Issue by darlanmendonca** [bevacqua/dragula#537]
Hello guys!!

reading the doc, I cannot found any event to dragenter, or dragover.

Is my mistake, or dragula dont have any event like that? E.g., on drag a element over other element inside container, I want to track time over other element, to make things like a group

**Comment by royJang** [comment]
same problem

**Comment by webtop** [comment]
Similar: I want to know if the group I'm hovering over has been expanded, and if not to expand it so I can drop into it. I haven't dug into the code yet, but I imagine that this module is taking complete control of the dragover event.

@darlanmendonca Did you find a resolution to your issue?

Thx

**Comment by webtop** [comment]
@bevacqua Any thoughts on where this is being blocked? Do the events need to be registered with emitter?

**Comment by webtop** [comment]
Actually I think I figured a way around it: Add the groups as containers so they receive the "over" event, and then during over expand the group, and if they get a drop, move the node that dropped into the expanded group. :)

**Comment by dcantatore** [comment]
https://github.com/bevacqua/dragula#drakeon-events
