### ISSUE TITLE
Differentiate between drag and click events

### ISSUE THREAD

**Issue by Tomesch** [bevacqua/dragula#54]
What do you think about differentiating between drag and click events by introducing a minHold duration option or something similar?

**Comment by bevacqua** [comment]
What's your use case? You could just stop propagation.

**Comment by dougludlow** [comment]
@bevaqua, can you give an example of using stop propagation? I'm using dragula with angular and I have click handlers on children elements that no longer work now that I added dragula.

**Comment by bevacqua** [comment]
Dragula [ignores clicks on anchors and buttons by default](https://github.com/bevacqua/dragula/blob/master/dragula.js#L135-L137). You can use `accepts` to further ignore clicks on other things that are event-bound.

**Comment by dougludlow** [comment]
@bevacqua I wrapped the items I had click events on with anchors and it works perfectly, thanks!

**Comment by zhongqf** [comment]
This is useful in some cases. 
For example, when you click on an item you may want to select it, not moving it. But when you hold the left buttton on mouse and start to move, obviously this is a drag behavior.

**Comment by qq286735628** [comment]
this is a good feature!

i need differentiate click and drag in the same DIV.

when i mousedown & mouseup quickly, it mean i want trigger click for this div.

when i mousedown but have a long time mouseup and i mousemove, it mean i want trigger drag for this div.

**Comment by askdesigners** [comment]
Is this no longer true? The linked code snippet is not anything related to the topic, and in the source I can't see any logic for ignoring buttons and anchors...
