### ISSUE TITLE
How to get current position of dragend?

### ISSUE THREAD

**Issue by Lanseer** [bevacqua/dragula#541]
> Please only use GitHub issues for bug reports and feature requests.
>
> - [ ] Read the [contributing guidelines][contrib]
> - [ ] Bug reports containing repro steps are likely to be fixed faster
> - [ ] Feature requests should be multi-purpose, describe use cases
> - [ ] For support requests or questions, please refer to [our Slack channel][slack]

[contrib]: https://github.com/bevacqua/dragula/blob/master/.github/contributing.markdown
[slack]: https://dragula-slackin.herokuapp.com/

**Comment by Lanseer** [comment]
dragulaService.dragend.subscribe((value) => {
          let [el, target, source] = value.slice(1);
          var rect = el.getBoundingClientRect().top;
          console.log(rect.top);
          console.log(el);
          console.log(target);
          console.log(source);
      });
the log is the original position of el,I need get current position when dragend occurred,anyone can help me ,thx in advance!

**Comment by phamtienmanh** [comment]
let dragEl = value[1];
      let list = Array.prototype.filter.call(value[1].parentNode.childNodes, (node) => {
        return node.tagName === 'TR';
      });
      this.newIndex = list.findIndex((node) => {
        return node === dragEl;
      });
