### ISSUE TITLE
Class based instead of id based

### ISSUE THREAD

**Issue by CalebKester** [bevacqua/dragula#55]
How hard would it be to fork the code and change it to be class based instead of ID based?

**Comment by dougludlow** [comment]
It's element based. Given the following html, you can add the containers to dragula by passing in the elements.
```
<div class="container">
    ...
</div>
<div class="container">
    ...
</div>
```

Vanilla
```
var containers = document.getElementsByClassName('container');
dragula(conatiners);
```

jQuery
```
var containers = $('.container').toArray();
dragula(conatiners);
```
