### ISSUE TITLE
Issues with videos in Chrome

### ISSUE THREAD

**Issue by laggingreflex** [bevacqua/dragula#554]
Awesome library!

Found an issue with videos and Chrome. Repro: http://jsfiddle.net/1k7ke9f3/

Dragging the video causes it to pause for some reason. Only in chrome, works in FF, not tested in others.

**Comment by tuberains** [comment]
I didn't dig too much into it, but it seems like Chromes implementation of `cloneNode()` does not clone the state of a video element.

As a quick fix, i think you can use Dragula's event system to manually propagate the current time of the video to the clone.

**Comment by dcantatore** [comment]
@laggingreflex Try using the on drag event to get the videos current state like @tuberains said, then on drop set the video time.
