### ISSUE TITLE
Invariant Violation when using React.js

### ISSUE THREAD

**Issue by j0hn** [bevacqua/dragula#56]
When using dragula to drag and drop react element's an error is throw because cloning elements will end up having two elements with same **data-reactid** attribute.

This is what the log says:

    Uncaught Error: Invariant Violation: ReactMount: Two valid but unequal nodes with the same `data-reactid`: .0.0.0.1:$0.0.4.1.0.0.3.0

**Comment by bevacqua** [comment]
Okay. Let me know if you find the fix. Ideally I wouldn't make React-specific changes to `dragula`

**Comment by j0hn** [comment]
A possible fix is adding an optional callback to transform the mirror node right after cloning it. That would let the user do whatever it wants with it without adding a `react` specific fix.

**Comment by bevacqua** [comment]
Is there the same issue when copying with `copy: true`?

**Comment by j0hn** [comment]
Same issue, the copied element will have the same attributes and mess up with react.

**Comment by bevacqua** [comment]
Resolved in `1.6.0` with event `cloned`

**Comment by bevacqua** [comment]
Also if you make a `react-dragula` component let me know and I'll promote it on the README :balloon:

**Comment by j0hn** [comment]
Awesome, thank you. Will consider doing a react component but dragula is simple enough to just use it as is.

**Comment by bevacqua** [comment]
That's good to know

**Comment by saulshanabrook** [comment]
@j0hn Would you be willing to show some of your react code using dragula? A simple example would be great to see.

**Comment by j0hn** [comment]
@saulshanabrook Here's somehow what i'm doing...

```javascript
dragula([...], {
  direction: 'horizontal',
}).on("cloned", function(clone){
  clone.removeAttribute('data-reactid');
  var descendents = clone.getElementsByTagName('*');
  Array.prototype.slice.call(descendents).forEach(function(child){
    child.removeAttribute('data-reactid');
  });
});
```

**Comment by saulshanabrook** [comment]
@j0hn Why do you have to remove the data-reactid? What happens if you dont?

**Comment by j0hn** [comment]
@saulshanabrook if you don't remove the reactid, there would be two elements on the dom with the same reactid and the react engine will fire warnings about that.

**Comment by saulshanabrook** [comment]
@j0hn thank you. Also, when do you call the dragula? Like if I have a list of elements from the props, would I call `dragula(...)` in `componentDidMount`?

**Comment by j0hn** [comment]
@saulshanabrook yes, i did a component that renders the list of elements and uses dragula in the `componentDidMount`

**Comment by bevacqua** [comment]
FWIW everyone, made `react-dragula` so we can further tweak `react`-specific `dragula` there. Of course, we would still need to expose primitives in `dragula` if they're needed by `react-dragula`.

https://github.com/bevacqua/react-dragula

**Comment by saulshanabrook** [comment]
@bevacqua Thats great! thank you so much :+1:
