### ISSUE TITLE
lot improvements

### ISSUE THREAD

**Issue by f0rmat1k** [bevacqua/dragula#57]
i gonna add pr with gulpfile with the following tasks:
1. Minification
2. Adding banner (info in top of dist files about plugin, author and repo)
3. Much module systems in dist? (es6, amd, jquery plugin). i offer to rewrite general library to `globals` format and then to build for different module systems. 

may I send such a pr?

**Comment by bevacqua** [comment]
There's no gulpfile

**Comment by f0rmat1k** [comment]
I  know.I was going to add it.

**Comment by bevacqua** [comment]
I'll pass, thanks. `dragula` builds using `npm run`

**Comment by bevacqua** [comment]
https://github.com/bevacqua/dragula/blob/master/package.json#L6-L14
