### ISSUE TITLE
how to catch a drop event ?

### ISSUE THREAD

**Issue by ahmedcastres** [bevacqua/dragula#580]
Hi,
I'm trying to catch the event when an object is already dragged in another container.
So, when I drag an objet, the function is called hundreds of times.
But how can I catch this event once the object is dragged successfully ?
Thank you :)

**Comment by leonardors95** [comment]
`        
your html :
<div class='container' ng-repeat="group in groups" dragula="'first-bag'" dragula-scope="$parent">
        <div ng-repeat='item in group.items' ng-bind='item.name'></div>
</div>

in your controller will be:
$scope.$on('first-bag.drop', function (e, el) {
            console.log("DROP EVENT !");
        });`

**Comment by leonardors95** [comment]
Example if your dragula bag name is "first-bag":

`        $scope.$on('first-bag.drop', function (e, el) {
            console.log("DROP EVENT !");
        });`

**Comment by MostafaEbrahimi** [comment]
if you use `drag event` across all dragging time your function will be called.so if you need to call your function once ( eg. when item dropped to target) you must use drop event.

```javascript
drake.on('drop',function(el,target,source,sibling){
    //call your function here
})
```
