### ISSUE TITLE
Do not remove original item when copy is dragged and drop is canceled

### ISSUE THREAD

**Issue by petronellius** [bevacqua/dragula#584]
When I am dragging copy of item and drop is cancelled, original item is removed from DOM.
See https://jsfiddle.net/petronellius/y9pkL0wq/

**Comment by MostafaEbrahimi** [comment]
What do you want to do ? and why you put `drake.cancel(true)` in this part of code
```javascript 
drake.on('drop', function(el) {
    console.log('drop');
    drake.cancel(true);
});
```

**Comment by MostafaEbrahimi** [comment]
At the moment I don't have best solution but I think you can use `accept` method to solve this problem.
```javascript
dragula(containers, {
    accepts: function (el, target, source, sibling) {
       //check if target equal to your intended container return false
      // so dom will revert to last position
    }
}
``` 
check and if it can not resolve the problem please inform me to find another way

**Comment by dcantatore** [comment]
https://github.com/bevacqua/dragula#drakecancelrevert
