### ISSUE TITLE
Add class to drop area - question

### ISSUE THREAD

**Issue by Subha** [bevacqua/dragula#585]
Hi,

I really like this library which is very handy and easy to use. 

Looks like the dragula in slack is not active hence my question here.

So I am trying to add a class to set a border to the element that i am dragging(target) and once I drop the element I will have to remove that class which I can do it in the drop event. 
![screen shot 2018-09-17 at 1 18 06 pm](https://user-images.githubusercontent.com/12513265/45638797-3acca000-ba7c-11e8-8907-1ec1a5c5d97f.png)

Any suggestions on this? 

I tried to add the class  in **over** event. 

    drake.on('over', (el, container) => {
      console.log('over params', el);

      container.classList.add('drag-hover-style');
    });

**Comment by MostafaEbrahimi** [comment]
please test:
```javascript
drake.on('drag', function (el) {
    el.classList.add('drag-hover-style');
})
drake.on('drop', function (el) {
    el.classList.remove('drag-hover-style');
})
```

**Comment by Subha** [comment]
Thank you for your response. 

I don't want to add style while dragging just onDrop but need to add a hover style something like what I have in the attached gif. 

I am trying it in the over and out events
![2018-10-02_10-42-43](https://user-images.githubusercontent.com/12513265/46356920-ba886c00-c631-11e8-8702-71faa9264b76.gif)

**Comment by dooky96** [comment]
dragula([component.find("d1").getElement()])
            .on('drag', function (el) {
                el.className = el.className.replace('ex-moved', '');
            }).on('drop', function (el) {
                el.className += ' ex-moved';
            }).on('over', function (el, container) {
                container.className += ' ex-over';
            }).on('out', function (el, container) {
                container.className = container.className.replace('ex-over', '');
**************
            });

**** - can I call any method after change className ?
