### ISSUE TITLE
How to get click events?

### ISSUE THREAD

**Issue by leefsmp** [bevacqua/dragula#59]
Hi, thanks for the great lib. I'm creating dynamically a div container with div's inside that I want to drag, but I also want to be able to click on each div to trigger some code. However when I use dragula on my container, it hides the click event, unless I do a CMD + click (on mac). I want to get the click event without user having to press additional keys... Any suggestion? Thank you.

**Comment by bevacqua** [comment]
Yes, prevent drag in `accepts` or use `a`, `button` elements
