### ISSUE TITLE
How to add the extra toolbar in mirror container ?

### ISSUE THREAD

**Issue by sks40gb** [bevacqua/dragula#590]
Whenever an element from the container getting dragged, dragula creates the exact mirror of it and moves along with the mouse.

Now the use case is to have additional toolbar (which contains the button to move and copy item ) which is outside of container.

1. How can we make the toolbar as a part of mirror container so that it can look like toolbar is stick with item ?
2. How can we enable the drag functionality when the toolbar is out of container ?

Sample Image for toolbar -
![screen shot 2018-10-06 at 2 36 02 pm](https://user-images.githubusercontent.com/36327/46569603-432a4380-c975-11e8-8a31-60429e86093f.png)

**Comment by paddotk** [comment]
The container is the element that contains all the draggable items, it's not draggable itself.
Aside from that, if I understand you right you want to apply a toobar to the item that is being dragged? How would you click any of those icons if you're already dragging?
