### ISSUE TITLE
npm install is unauthorized

### ISSUE THREAD

**Issue by rodgersgb** [bevacqua/dragula#597]
$ npm install @swimlane/dragula
npm ERR! code E401
npm ERR! 401 Unauthorized: @swimlane/dragula@latest

Debug log:
-------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\grodgers\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@swimlane/dragula' ]
2 info using npm@6.0.0
3 info using node@v8.11.1
4 verbose npm-session 55ba4580c8053486
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 401 https://registry.npmjs.org/@swimlane%2fdragula 181ms
8 silly fetchPackageMetaData error for @swimlane/dragula@latest 401 Unauthorized: @swimlane/dragula@latest
9 timing stage:rollbackFailedOptional Completed in 3ms
10 timing stage:runTopLevelLifecycles Completed in 2192ms
11 verbose stack Error: 401 Unauthorized: @swimlane/dragula@latest
11 verbose stack     at fetch.then.res (C:\Users\grodgers\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
11 verbose stack     at tryCatcher (C:\Users\grodgers\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\grodgers\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
11 verbose stack     at Promise._settlePromise (C:\Users\grodgers\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (C:\Users\grodgers\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
11 verbose stack     at Promise._settlePromises (C:\Users\grodgers\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
11 verbose stack     at Async._drainQueue (C:\Users\grodgers\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
11 verbose stack     at Async._drainQueues (C:\Users\grodgers\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues (C:\Users\grodgers\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
11 verbose stack     at runCallback (timers.js:794:20)
11 verbose stack     at tryOnImmediate (timers.js:752:5)
11 verbose stack     at processImmediate [as _immediateCallback] (timers.js:729:5)
12 verbose cwd D:\projects\blademodules\ang5\git\blade
13 verbose Windows_NT 10.0.17134
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\grodgers\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "@swimlane/dragula"
15 verbose node v8.11.1
16 verbose npm  v6.0.0
17 error code E401
18 error 401 Unauthorized: @swimlane/dragula@latest
19 verbose exit [ 1, true ]

**Comment by bevacqua** [comment]
This isn't `@swimlane/dragula`
