### ISSUE TITLE
not usable on IE mobile

### ISSUE THREAD

**Issue by indus** [bevacqua/dragula#6]
I have troubles to use your demo on a Windows Phone. It seems default behaviour (e.g. scrolling) of touch events isn't blocked correctly. That makes it unusable.

**Comment by bevacqua** [comment]
I'm not entirely sure I understand, could you ellaborate? Thanks

**Comment by bevacqua** [comment]
I don't have a Windows Phone. Please clone the `ms-pointer-events` branch and let me know if that fixes the issues for you.

**Comment by indus** [comment]
Further explanation: The window scrolls  when I try to drag an element vertically and the browser goes back in history when i drag an element to the right (thats both default behaviour)
Maybe I find enougth time at the weekend to give yout branch a try.

**Comment by bevacqua** [comment]
The new event handlers I registered *should* handle the event (and prevent the default behavior). Please give it a shot when you can so I can merge this

**Comment by bevacqua** [comment]
Should be fixed in `1.2.3`
