### ISSUE TITLE
How can I set dynamic containers?

### ISSUE THREAD

**Issue by AndrewEastwood** [bevacqua/dragula#60]
I have two Backbone views that are rendering in different placeholders at different time and I want to drag element from one view and drop it into another. Is it possible to do?

**Comment by bevacqua** [comment]
You could do `dragula([], options)`, creating a `drake` with no containers. Then use `drake.addContainer(containers)` whenever you have new containers to add, and `drake.removeContainer(containers)` whenever you have containers to dispose of.

**Comment by AndrewEastwood** [comment]
gotcha! thanks

**Comment by nanthil** [comment]
What is a container and what is a drake? This is not covered in the documentation.

**Comment by ha0x7c7** [comment]
var drake = dragula(container, option)
