### ISSUE TITLE
Dragula prevents all mouse events in drag mode

### ISSUE THREAD

**Issue by hassanasad** [bevacqua/dragula#607]
When an item is being dragged, Dragula prevents all mouse events. I believe this should be an option setting in container config. There are times when hover and other (mouseover/mousedown/mouseup) events are useful. Can this be fixed please. Its limiting some cool nesting features which cant be done otherwise.

**Comment by hassanasad** [comment]
Is there a way to bind mouse events when dragging starts to the item being dragged so we can some how calculate if its hitting another item?

**Comment by hughfuve** [comment]
dragula must at least know what the mouse X,Y coords are for where the element is currently positioned, is there some way that these can be exposed to us as a property that we can just read?

**Comment by macu** [comment]
I want to support dragging between content tabs within my app but I need the mouseover event on the tab in order to be able to switch to it. Not sure how I can detect that if Dragula prevents mouse events from firing on elements behind the mirror element.

**Comment by susaree** [comment]
why was this closed?
