### ISSUE TITLE
New maintainers or mark project as readonly

### ISSUE THREAD

**Issue by garygreen** [bevacqua/dragula#610]
Hey Nicolás @bevacqua 

So it seems this repository has become a bit of a pain to maintain, would it be time to now introduce new maintainers onto the project to take the burden off?

The last release was over 3 years ago and this project has nearly 20,000 stars - it's still actively used and has many issues/PRs. There are limited alternatives out there for good, lightweight sorting libraries so it's still worthwhile maintaining this project.

If you don't intend to do anymore work on it, or bring on board any maintainers, would you consider marking the repository as read-only to make your intentions clear, then developers can make a more informed decision whether to continue use this library or reluctantly find alternatives.

Cheers

**Comment by owen-m1** [comment]
https://github.com/SortableJS/Sortable

**Comment by jokamax** [comment]
+1

**Comment by vitalyp** [comment]
+1

**Comment by bevacqua** [comment]
nope

**Comment by garygreen** [comment]
Time to move on chaps. Let's all support @owen-m1 with https://github.com/SortableJS/Sortable who is hard at work maintaining the project (and currently reducing it's size / making it more modular).
