### ISSUE TITLE
unable to install swimlane/dragula

### ISSUE THREAD

**Issue by Ravinthiran** [bevacqua/dragula#618]
See Terminal Log:

D:\Projects\Project GoGreen>npm i @swimlane/dragula
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/swimlane/dragula.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by paddotk** [comment]
Maybe you should post this on that fork then..
