### ISSUE TITLE
Support Question - Is this repo still maintained? 

### ISSUE THREAD

**Issue by StephenEsser** [bevacqua/dragula#622]
Hi everyone, 

I attempted to visit the various links for the [slack channel invite](https://dragula-slackin.herokuapp.com/) but it throws an error. The heroku app must be down. 

I'm doing a little research into this library for a personal project I am working on, but I had a couple quick questions. 

Is this library still maintained? Browsing through the commit history / issues / and open pull requests it looks like things have slowed down quite a bit. Are you still accepting contributions or encouraging active development when issues arise?

**Comment by paddotk** [comment]
There hasn't been any activity here or on the slack channel for a long time, so I'd say no.

**Comment by dcantatore** [comment]
Yes

**Comment by StephenEsser** [comment]
![i_don_t_believe_you-DMID1-5g3w3fy5b-359x300](https://user-images.githubusercontent.com/6720991/94496986-806be980-01bb-11eb-8614-07e30d3618e0.gif)

**Comment by dcantatore** [comment]
I'm right here. Check the branches to see the coming merge.

**Comment by amk221** [comment]
Great news 🙂
