### ISSUE TITLE
Possibility to move an item without having it removed on drag start

### ISSUE THREAD

**Issue by directcuteo** [bevacqua/dragula#627]
Hello!

I want to be able to drag an element from the list but without the default behaviour of ng2-dragula which is removing it on drag start.

I want the element to stay where it is until I drop it (because it is moving all the elements in the list if it is removed and it's baffling). I would like something like the copy function, where the element is not removed on drag start so basically _on the drag time I will have the element in it's initial position and also attached to the mouse cursor._

One solution that I found is to create a new element, append it to the place drag started and in the end delete it on the drop event but it is just an ugly workaround when it should be a simple boolean dragula configuration.

Did someone faced this problem aswell and found a solution or could this be included as a future feature?

Thank you!

**Comment by cormacrelf** [comment]
Not possible. Remember this is a thin wrapper around Dragula, which does not have this functionality.

**Comment by brandoncc** [comment]
It sounds like what you want is to use the "copy" drag type. Hopefully you already found a solution, since this was almost a year ago, but this might be useful for others.

**Comment by dcantatore** [comment]
https://github.com/bevacqua/dragula#optionscopy
