### ISSUE TITLE
Broken image for "Slack" & "Support" in ReadMe

### ISSUE THREAD

**Issue by MrNoddyInfy** [bevacqua/dragula#632]
Please find attached screenshot.

![Screenshot (91)](https://user-images.githubusercontent.com/53807772/67386946-845ab900-f5b3-11e9-8585-9d05224fab28.png)

**Comment by MrNoddyInfy** [comment]
If someone can point me to image path, I will fix this.

**Comment by MrNoddyInfy** [comment]
any updates on this issue?

**Comment by jiahuij** [comment]
The issue is caused by slow responses from the Shields server combined with GitHub's image proxy's timeout. (The combination causes slow images to be rendered as missing images.)
