### ISSUE TITLE
Same div appears when dragging 

### ISSUE THREAD

**Issue by ismailsumercetin** [bevacqua/dragula#638]
Hi,

When I drag an element in the screen, the copy of that element somehow appears nearly at the bottom of the div that I am dragging. Is there any way to fix this problem? 

I'd like to clarify the problem with pictures:

![pic1](https://user-images.githubusercontent.com/16711249/75590957-8962d400-5a8f-11ea-92aa-646ec1eda524.png)

Here I have two bigger div containers and smaller divs inside. I am dragging "Adet" element in the left container to the right(my cursor didn't show up).

![pic2](https://user-images.githubusercontent.com/16711249/75591074-db0b5e80-5a8f-11ea-816b-f291d8b1eeeb.png)

I am still not removing the left click, in dragging state. As you can see the same div appears at the bottom. Any helps appreciated.

**Comment by ismailsumercetin** [comment]
I've tried removing mirror-related classes, increasing opacity etc. but they did not work. Thus, I decided to set mirrorContainer as head like this: 

`mirrorContainer: document.querySelector("head");`

So far this trick works well for me and haven't encountered any drawbacks.

**Comment by akhalil-xiq** [comment]
@ismailsumercetin can you tell me about mirrorContainer. I am not able to understand it. What it is? I have a complex layout for drag n drop. Please tell me in the context of '**over**' and '**drop**' event kindly.

**Comment by ismailsumercetin** [comment]
> 
> 
> @ismailsumercetin can you tell me about mirrorContainer. I am not able to understand it. What it is? I have a complex layout for drag n drop. Please tell me in the context of '**over**' and '**drop**' event kindly.
> @dannguyen

When you click and hold your left-click on an element (dragging an element), mirrorContainer creates a clone of that element (as you can see in pictures in my previous comments, a div block, in which "Adet" is written). In my case, the clone element was far below the actual element that I was dragging. I couldn't solve it by changing the position of the clone element, and I tried some other ways, which I don't remember, but they didn't work. In order to solve it, I added mirrorContainer attribute wanted to show my clone in head tag, which didn't have effect on the DOM since we don't see head tag in a webpage.

**Comment by jhwheeler** [comment]
Yes, I have the same issue. 

@ismailsumercetin Your solution does work to remove the mirror element entirely, but ideally we could have it work as expected. Were you able to find a solution that has the mirror element work as in the demo?

**Comment by jhwheeler** [comment]
@ismailsumercetin I actually found the issue! 

I didn't read the README thoroughly enough and I hadn't imported the [dragula.min.css](https://github.com/bevacqua/dragula/blob/master/dist/dragula.min.css) file. When you import that file, it works perfectly! 

More info here: https://github.com/bevacqua/dragula#including-the-css
