### ISSUE TITLE
Feature request: drop wells within capture areas

### ISSUE THREAD

**Issue by macu** [bevacqua/dragula#645]
I would like to see support added for drop target well within a capture area. The use case I have in mind is a graphical tree structure where the nodes can be dragged to any point in the tree. Currently there needs to be a container within each node representing the sublist with non-zero height even if it is empty. What I am envisioning is allowing you to drag a node over a capture area,  and the node being placed in the designated container within it. Managing a tree, you could drag a node between two other nodes, or drag onto a node to place the dragged item within the empty sublist, which could be styled using `:empty` as `display: none`. This would allow areas of sites to be capture areas while dragged nodes are inserted into a sub element.

**Comment by Yokubjon-J** [comment]
Hello! I am a first-timer. Can I pick this issue up?
