### ISSUE TITLE
Disable Shadow Transit

### ISSUE THREAD

**Issue by radenkozec** [bevacqua/dragula#649]
I am using this code 
` trackDraggingState(dragApi) {
        let handle;
        dragApi.on('drag', (el) => {
            handle = setTimeout(() => {
                this.dragging = true;
            }, 1000);
        });
        dragApi.on('dragend', (el) => {
            clearTimeout(handle);
            this.dragging = false;
        });
    }`
to add lift delay on mobile phone.
The problem is that shadow is still displayed because dragging is true even if it not executed.
Can you provide me with solution where shadow will not be display until I start dragging?

**Comment by dcantatore** [comment]
@radenkozec - Can you provide a codepen showing this?
