### ISSUE TITLE
feature request for event `accepts`: provide dragged element new index in the target array

### ISSUE THREAD

**Issue by slamjs** [bevacqua/dragula#651]
currently, in the **accepts** event I can't know what index a dragged element will have after dragging to the target array, but I need this for a validation purposes. I want to allow to drag an element only to certain range of indexes in the target array, that range of indexes will be dynamic based on the current array state and elements that it's contain.

It would be very helpful if an **accepts** event will be changed to something like
 `accepts: function (el, target, source, sibling, newIndex) {}`

**Comment by dcantatore** [comment]
You can determine the new index based on the sibling.
