### ISSUE TITLE
After moving all items to the other container, the one without any itens disappears

### ISSUE THREAD

**Issue by lucasfcosta** [bevacqua/dragula#7]
I don't know if this is the expected result when a container runs out of icons but I think it should be possible to move items back even after emptying one of the containers. I may be able to help if you need, but I would like to know if this is what you really want before making any changes to the code.

PS.: Great work!

**Comment by bevacqua** [comment]
That's just CSS, it's up to the consumer to make the CSS look pretty :) This is intended as a focused solution, not a comprehensive one

**Comment by lucasfcosta** [comment]
Oh, thanks for your explanation, sorry bothering you about this!
