### ISSUE TITLE
Drag and drop files with dragula?

### ISSUE THREAD

**Issue by henn1nk** [bevacqua/dragula#70]
Does someone have a simple example how to extend/use dragula for dropping in files coming from outside of the browser? (file explorer or something else)

On this way i could use dragula for several functions here :-)

**Comment by bevacqua** [comment]
I don't think you'd be able to do that in the current state of dragula, since it whitelists containers where a dragged element may come from. You're free to come up with a PR that implements this, as long as it keeps changes to a minimum
