### ISSUE TITLE
Very Nice but a Rube Goldberg

### ISSUE THREAD

**Issue by srqseo** [bevacqua/dragula#71]
I like what you have here but your documentation is poor and as I read your code it comes off as a Rube Goldberg job.

It is a shame you could not strive to make ti simpler or at least provide clearer documentation.

Remember, it only makes sense if OTHERS understand it.

**Comment by bevacqua** [comment]
I have no idea what you're talking about. Feel free to send a PR to improve the documentation and we can talk over the modifications.
