### ISSUE TITLE
If there's a input field in a dragged element its un clickable.

### ISSUE THREAD

**Issue by yanivkalfa** [bevacqua/dragula#72]
Say i have a '< li >' or a '< th >' with input field in it, I am unable to click in the input field as it start the drag process immediately. i am not sure why it happens(haven't tested it yet), i can assume it relates to event bubbling or capturing.

**Comment by bevacqua** [comment]
It happens because `dragula` wants to be able to capture all clicks within elements of a container. To prevent this behavior, you can use `moves`.

```js
dragula(container, {
  moves: function (el, target, handle) {
    return handle.tagName !== 'INPUT';
  }
});
```

**Comment by yanivkalfa** [comment]
that would mean i would have to specify each element i dont want captured and  i will have to treat each type of dragula differently - say i want to make a simple dnd module that would manipulate an array or something while the element being dragged are dynamically set so a '< li >' could possibly have a button in it, or '< th >' could have the input. etc, 

i will have to make a separate module or instantiate different dragula for each case.

**Comment by bevacqua** [comment]
Well you could use a class name if you have lots of stuff you don't want captured. But just saying you don't want to capture inputs or textareas should be plenty.

**Comment by yanivkalfa** [comment]
I figured it out. thanks very much.
