### ISSUE TITLE
Drag behaviour when using copy

### ISSUE THREAD

**Issue by ConnorKrammer** [bevacqua/dragula#74]
When copying an item between two fields there is currently no way to cancel the action. For a normal drag, a user can cancel the action by releasing over the element's starting position; with copy, however, once an item has been dragged into the destination field there is no way to stop. This can be circumvented by setting either `removeOnSpill` or `revertOnSpill` to `true` (as of PR #64 and #73). This happens because of how those options function, but I think it would be worth building that into the `copy` setting itself instead of relying on emergent behaviour.

Additionally, it's worth noting that there is currently no way to move an item within its own column when `copy === true`.

**Comment by bevacqua** [comment]
You could easily add a keyboard shortcut so that they can cancel with <kbd>esc</kbd>, but I agree that we should probably have the behavior you describe built into `copy`

**Comment by karellm** [comment]
I second having issue moving an element inside its own column (control the order) when `copy: true`.

**Comment by beatfreaker** [comment]
@bevacqua for allowing reorder items in same container when `copy: true` what do you think above this approach : 
when `copy: true` user will drag a element if it drops in same container then we will delete the original element and if it drops in different container then we will not delete it.

is this a good approach to allow reordering of element in same container when `copy: true`?

**Comment by beatfreaker** [comment]
@bevacqua something like this 


![demo](http://i.giphy.com/xTiTnmvCK88YXnpZQI.gif)

**Comment by bevacqua** [comment]
That looks acceptable but it should probably be behind a flag

**Comment by beatfreaker** [comment]
you means to allow this feature only if a flag is set in options??
something like
```javascript
dragula([$('left-copy-1tomany'), $('right-copy-1tomany')], {
  copy: function (el, source) {
    return source === $('left-copy-1tomany')
  },
  allowSameContainerReorder: true
});
```

**Comment by bevacqua** [comment]
Correct, but probably with a simpler name like `copySortSource`

**Comment by beatfreaker** [comment]
okay .... working on a PR for this.

**Comment by beatfreaker** [comment]
@bevacqua is anything still pending for this issue to be closed?

**Comment by brinzi** [comment]
Hello,

When i try to reorder in my source container, it created duplicates.

Any advice?
