### ISSUE TITLE
Locking axis

### ISSUE THREAD

**Issue by Krinopotam** [bevacqua/dragula#75]
Hi!

Is it possible to lock an axis of moved element, while dragging (for instance vertical or horizontal only)?

**Comment by bevacqua** [comment]
Not really

**Comment by Krinopotam** [comment]
Could you add such feature? This will allow to sort the list by dragging in the IOS style.

**Comment by bevacqua** [comment]
Sorry, but no

**Comment by cfenzo** [comment]
@bevacqua would you accept a PR with an `axis:"y"||"x"` option?
I needed it on a project and implemented it in a local fork.

**Comment by bevacqua** [comment]
Sure

**Comment by philippfrank** [comment]
@cfenzo Did you open that PR you mentioned anywhere?

**Comment by d-steinberg** [comment]
@cfenzo @bevacqua any updates on this?

**Comment by nguyenj** [comment]
I'm unclear why this issue is closed; but here's a [PR](https://github.com/bevacqua/dragula/pull/448) for restricting the dragging element to an axis.

**Comment by nguyenj** [comment]
@philippfrank @d-steinberg Take a look at the [PR](https://github.com/bevacqua/dragula/pull/448) and let me know if you have any questions.

**Comment by d-steinberg** [comment]
@nguyenj Just in time, I had literally began to look at dragula.js the moment I got an email from this thread! Thank you!

**Comment by nguyenj** [comment]
Thanks @d-steinberg 

@bevacqua how can I get [this](https://github.com/bevacqua/dragula/pull/448) merged?
