### ISSUE TITLE
Firefox slow performance

### ISSUE THREAD

**Issue by mtj8033** [bevacqua/dragula#77]
Tried in the latest firefox and it is very slow when dragging, chrome its fine.

**Comment by bevacqua** [comment]
Can you pinpoint the issue?

**Comment by daleeidd** [comment]
It's the CSS transition `transition: all 0.4s ease-in-out 0s`.

**Comment by bevacqua** [comment]
Could you create a pull request?

**Comment by daleeidd** [comment]
Done. See #78

**Comment by mtj8033** [comment]
Has this been pushed out to npm?
