### ISSUE TITLE
Drag&Drop Radio buttons

### ISSUE THREAD

**Issue by fikipollo** [bevacqua/dragula#80]
Hi

First, thanks for such awesome library!

I found an issue when dragging a div containing radio buttons, i.e. If one or more radios are marked as "checked", after dragging the div, all them lose the "checked" status.
However it doesn't happens for checkboxes.

Do you think that could be fixed?

thanks!

**Comment by fikipollo** [comment]
The origin of this issue is the JavaScript function "cloneNode" which loses the checked values for radiobuttons.

That was my solution:

1. Add the following function at the dragula class.

```javascript
function fixRadioButtons(source, target){
        var checked = source.querySelectorAll("input[type=radio]:checked");
        for (var i = 0; i < checked.length; i++) {
              target.querySelector("#" + checked[i].id).checked = true;
         }
 }
```
2. Call the previous function at the following dragula's methods.
```javascript
//AT FUNCTION renderMirrorImage
function renderMirrorImage() {
        if (_mirror) {
                 return;
        }
        var rect = _item.getBoundingClientRect();
         _mirror = _item.cloneNode(true);
                            
        fixRadioButtons(_item, _mirror);
        [...]
}

//AT FUNCTION release
function release(e) {
       if (!api.dragging) {
            return;
       }
       var item = _copy || _item;
                            
       fixRadioButtons(_mirror, item);
       [...]
}
```

Hope that helps!

Best regards and thanks!

**Comment by bevacqua** [comment]
Please:

- Create a failing demo
- Submit a PR with a fix that uses `document. getElementsByTagName`

**Comment by bevacqua** [comment]
Closing for now. Consider the PR.

**Comment by ajb** [comment]
Can confirm this is an issue, since the cloned inputs have the same `name` attribute, and only one can be checked at a time. Working on a PR right now.

**Comment by ajb** [comment]
@fikipollo would love your feedback on my PR that fixes this issue: https://github.com/bevacqua/dragula/pull/331

**Comment by xmaestro** [comment]
@bevacqua These changes (#331) do not seem to be a part of the package. Could you please merge and do a new release?

**Comment by fikipollo** [comment]
Hi all, the issue is not fixed yet, please take a look to this fiddle to get an example of the problem
https://jsfiddle.net/beb6a3rj/1/
