### ISSUE TITLE
Make the Options available in Accept callback

### ISSUE THREAD

**Issue by L-C-P** [bevacqua/dragula#86]
Please make the options (e.g. Copy) available in the accept callback. E.g.

```js
var api = emitter({
                        addContainer: manipulateContainers('add'),
                        removeContainer: manipulateContainers('remove'),
                        start: start,
                        end: end,
                        cancel: cancel,
                        remove: remove,
                        destroy: destroy,
                        dragging: false,
                        options: o
                    });
```

I'm developing a VS like designer. I have one panel on the left and one on the right. If i'm starting dragging from the left to the right panel, copy should be true. Because the controls in the designer should stay there. If i'm dragging something in the left panel (rearranging the position of controls), the copy should be false. If i see it right, that is not possible with the current version?

**Comment by bevacqua** [comment]
What you actually want is for the copy property to be available on the `drake` object, and that if you change the value it's immediately reflected on the UI. This wouldn't be a very complicated thing to do. Feel free to submit a PR
