### ISSUE TITLE
use with jquery

### ISSUE THREAD

**Issue by Smashr** [bevacqua/dragula#87]
Hi,

I have a jquery object selected, when I use dragula I get an error.
In the simplest of forms here what my code looks like:

    var contentarea = jQuery(".contentarea");
    dragula(contentarea);

doing this give me an error:

    Uncaught TypeError: e.addEventListener is not a function

I'm not a pro at js or jquery, I must be doing something wrong. Is there a guide to using Dragula on jquery elements / selected objects.

**Comment by CREEATION** [comment]
Try this, maybe:

```javascript
var contentarea = jQuery(".contentarea")[0];
dragula(contentarea);
```

**Comment by Smashr** [comment]
Thanks ... I'll give it a try. ... makes sense :)

**Comment by jordyvaneijk** [comment]
Does this make sense? 
`var contentarea = $('.contentarea')[0]` selects the first item in an array right? but what if you have multiple contentareas and want to use them all for drag and drop?

**Comment by CREEATION** [comment]
`$('.contentarea')[0]` retrieves the javascript object directly to use it with this library.

You would do this, if I understood you correctly (not tested):

```js
var contentarea1 = $("#contentarea1")[0];
var contentarea2 = $("#contentarea2")[0];
var contentarea3 = $("#contentarea3")[0];
dragula([contentarea1, contentarea2, contentarea3]);
```

**Comment by AlexNodex** [comment]
you could just use map...

```
var lists = $('.some-selector').map(function(){ return this; }).get();
// then
dragula(lists);
```
