### ISSUE TITLE
Make links and anchor tags draggable

### ISSUE THREAD

**Issue by Smashr** [bevacqua/dragula#88]
Instead of lists / divs only, we have a multitude of elements including anchor tags that need to be dragged.

We are migrating the app from jQueryUI's sortable.

Is it possible to enable dragging and dropping of links (anchor tags) ... but disable clicks on them ? So basically a drag event would trigger but not a click event.

**Comment by Smashr** [comment]
note: With jQueryUI's sortables, anchor tags drag and drop just fine.

**Comment by bevacqua** [comment]
Feel free to create a PR for an option that does this (disabled by default)

**Comment by bevacqua** [comment]
Resolved in `1.7.0`, see https://github.com/bevacqua/dragula#optionsinvalid
