### ISSUE TITLE
Angular version of dragula

### ISSUE THREAD

**Issue by luckylooke** [bevacqua/dragula#89]
I just want to let you know that I have made angular version of dragula. I will be working on it continuously and slowly diverse more and more from origin. But also I will be keeping track with your changes and optionally implementing them. Thank you very much for great code base! Its most beautiful drag&drop implementation I have seen so far now.

Link to my fork: https://github.com/luckylooke/dragular

**Comment by bevacqua** [comment]
Sounds good. I'd be more interested if you managed to use `dragula` as is in `dragular`. Do you think that's possible without changing `dragula` too drastically?

**Comment by luckylooke** [comment]
I am planning to add some other features I will use in my own projects. But
maybe I will make some simple plugin system to keep core light.

I had to change dragula code because of dubled implementations. I was using
features of framework to make dragula even lighter. There are more
posibilities to make more parts better angular-way and probably I will make
them. I hope you dont mind.

**Comment by bevacqua** [comment]
Well that was kind of my point, you could've still used `dragula` and add your custom features in the directive that wraps it. This feels like reinventing the wheel.

From the **"what have I done"** section in your readme,

- replacing crossvent with angular's thing: saves you `833B
- replacing contra.emitter by $scope.$emit: saves you from listening on the event and doing `$scope.$emit` within the directive. saves you `553B`
- encapsulation inside an angular service factory: you can still do this if you were to use `dragula`
- directive: you can still do this
- service/directive in a module: same

**Comment by luckylooke** [comment]
Well.. its just begining. And also sometimes reinventing the wheel can be useful [link](http://www.theatlantic.com/technology/archive/2013/06/this-guy-reinvented-the-wheel-by-turning-it-into-a-cube/276705/). You did the same, because there were already drag&drop libraries, it is about point of view.

I dont see any problem with my version of dragula. I think that it can be useful to people. If not, no problem, they just wont use it. I have made it for my purpose and I just share it to others. There always will be link back to original dragula so they can encapsulate it into angular service/directive by themselves. It is not difficult to anybody using angular regularly.

Building my features upon dragula would make code even bigger and less readable.
For example if I want to catch dragula events in parent scopes I have to do this:
in child controller
```javascript
dragula($('element')).on('drag', function (el) {
  $scope.$emit('drag', el);
})
```
in parent controller
```javascript
    $scope.$on('drag', function(e, el) {
       // do stuff
    });
```
Whether if I use my fork dragular it would be:
in child controller
```javascript
dragularService($element, {
      scope: $scope
    });
```
parent controller part is the same.

And some features even cannot be added without changing the dragula code. I am planning to allow custom classes if provided via options.classes. They are now hardcoded inside dragula, so I have to move them into options, which cannot be done from outside. Etc.. etc.. 

I am not gonna convince you anymore that it make sense to make separated version, it is OK to me that you dont like the idea.

Keep coding like you did and I will be glad. :)

**Comment by bevacqua** [comment]
Point was you can still make a `dragularService` wrapper around `dragula` that facilitaties its interactions with Angular without forking `dragula` as a whole. Not trying to convince you of anything, just helping out. Enjoy the cutlery!

**Comment by bevacqua** [comment]
@luckylooke ended up writing up an official Angular version of `dragula`. https://github.com/bevacqua/angular-dragula

Hope it helps and that you consider merging back. Would love you as a contributor to that repo.

**Comment by luckylooke** [comment]
I will consider it later, thank you for your offer.
