### ISSUE TITLE
rect.width is undefined at IE8

### ISSUE THREAD

**Issue by qq286735628** [bevacqua/dragula#90]
https://github.com/bevacqua/dragula/blob/master/dist/dragula.js#L299

getBoundingClientRect just have four properties: left, top, right, bottom.

width & height add in Gecko 1.9.1 but IE8 didn't support

https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect

**Comment by bevacqua** [comment]
So `right - left` and `bottom - top`, can you pull request?

**Comment by bevacqua** [comment]
They're used somewhere else too. https://github.com/bevacqua/dragula/blob/master/dist/dragula.js#L349
