### ISSUE TITLE
event.pageX is undefined at IE8

### ISSUE THREAD

**Issue by qq286735628** [bevacqua/dragula#91]
https://github.com/bevacqua/dragula/blob/master/dragula.js#L83

event.pageX & event.pageY is undefined at IE8

**Comment by bevacqua** [comment]
We can use `pageX || clientX`, `pageY || clientY`, can you submit a PR?

**Comment by qq286735628** [comment]
yes, i will fix all IE8 problem #90 #91 in one PR.

**Comment by bevacqua** [comment]
:rocket:

**Comment by qq286735628** [comment]
I have update, but i got some problem and i don't why.
dome here: http://qq286735628.github.io/dragula/

at IE8, when i click `<div>Item 3.</div>`, it will get something wrong, look like lose `</div>`
https://github.com/qq286735628/dragula/blob/master/example/example.js#L41

but ,i click `<div>Move me, but you can only drop me somewhere in this container.</div>`, everything look well.

**Comment by qq286735628** [comment]
i click `Item 3.`
![image](https://cloud.githubusercontent.com/assets/793007/8336092/7d54f2d8-1ad4-11e5-8c5a-7ef0effa7116.png)

i click `If you try to drop me somewhere other than here, I'll die a fiery death.`
![image](https://cloud.githubusercontent.com/assets/793007/8336107/8d85f4f4-1ad4-11e5-9f5c-8e9c2eb019f4.png)

**Comment by bevacqua** [comment]
Please pull the latest changes and let me know if these resolve both #90 and #91.

**Comment by bevacqua** [comment]
(you're account for scroll but that's already handled by `getOffset`)

**Comment by bevacqua** [comment]
Let me know if this and #90 are still an issue @qq286735628

**Comment by qq286735628** [comment]
IE8 can drag & drog, but not see mirror

**Comment by bevacqua** [comment]
Can you create a separate issue for that? Ty!
