### ISSUE TITLE
IE8 can't detachEvent 'ontouchend'

### ISSUE THREAD

**Issue by qq286735628** [bevacqua/dragula#92]
https://github.com/bevacqua/dragula/blob/master/dragula.js#L378

when dragula destroy in IE8, this will make error

**Comment by bevacqua** [comment]
Were the other issues fixed?

**Comment by bevacqua** [comment]
Can I see a screenshot of this issue?

**Comment by qq286735628** [comment]
![20150625103746](https://cloud.githubusercontent.com/assets/793007/8345819/019cf548-1b27-11e5-8a74-256d43c5ce49.png)

![20150625103729](https://cloud.githubusercontent.com/assets/793007/8345821/065a1f8e-1b27-11e5-81ec-52f3be1b8e47.png)

**Comment by qq286735628** [comment]
error is type mismatch

**Comment by qq286735628** [comment]
this will detachEvent 'ontouchend'

**Comment by qq286735628** [comment]
sorry, it seem my error,

I have two dragula and one is init error, so this one destroy will error
