### ISSUE TITLE
click or drag

### ISSUE THREAD

**Issue by Atheroth** [bevacqua/dragula#93]
I am making a trello clone. Trello opens a bootstrap modal for editing a clicked card. If you start dragging instead of mouseup, trello does not open the modal, starts drag instead. How can this be achieved with dragula?

I used drake.on('cancel', triggerClickEvent) but it is far from ideal. There should be a click event type exposed by drake that only fires when it is a click and not a drag.

**Comment by bevacqua** [comment]
Dupe of https://github.com/bevacqua/dragula/pull/84

**Comment by bevacqua** [comment]
Implemented as `1.7.0`, by the way

**Comment by Atheroth** [comment]
you're great! Thanks. I'll try delay=true right now.

**Comment by Atheroth** [comment]
it works! thanks.
