### ISSUE TITLE
IE8 e.which is undefined

### ISSUE THREAD

**Issue by qq286735628** [bevacqua/dragula#95]
IE use e.keyCode 

https://github.com/bevacqua/dragula/blob/7344e82831197566cdf1d261d37443cd0cce9cf1/dragula.js#L80

**Comment by qq286735628** [comment]
i think u example should add es5-shim, let user can test in IE

**Comment by bevacqua** [comment]
This is handled by `crossvent` https://github.com/bevacqua/crossvent/blob/master/src/crossvent.js#L47
