### ISSUE TITLE
Support for AngularJS

### ISSUE THREAD

**Issue by mato75** [bevacqua/dragula#97]
Is it maybe planed for the future on creating a directive for AngularJS?

**Comment by bevacqua** [comment]
No. Support should be fairly straightforward. See [angular-rome](https://github.com/Dashue/angular-rome/blob/master/angular-rome.js) for an example on how it was implemented for Rome. It should be just as easy for Dragula.

**Comment by jameswyse** [comment]
Try this: https://github.com/luckylooke/dragular

**Comment by bevacqua** [comment]
Note that that won't get patches submitted to `dragula` as it doesn't depend on it but is rather a spork

**Comment by jameswyse** [comment]
Hm yeah, just noticed that.. looks like it has been forcibly "angularized"!  

I'll just wrap this in a directive instead :)

**Comment by bevacqua** [comment]
Support for Angular is now a thing: https://github.com/bevacqua/angular-dragula
